### ISSUE TITLE
Inadequate security Error

### ISSUE THREAD

**Issue by C4n0nymous** [tatsuhiro-t/nghttp2#105]
Hi,

We are try to use your nghttp2 v0.6.6 to build a server for research on HTTP2 and SPDY. 
So,we setup a testing server by follow command.

First, i setup a nghttp server.
nghttpd --no-tls -d/var/www/ 8080

Then, i setup a http2-bridge proxy with TLS v1.2. As we need to decrypt the tls in wireshark, we can't use the ciphers which contain the DH or DHE algorithm. 

nghttpx --http2-bridge -b127.0.0.1,8080 -f0.0.0.0,443 --backend-no-tls --ciphers=AES128-GCM-SHA256 /root/key/server.key /root/key/server.crt --accesslog-file=/root/access.log --errorlog-file=/root/error.log -LINFO

And it work when i use the Google chrome to access the web server through HTTP1.1 with SPDY.
But when i try to use nghttp to access the web server through HTTP2 with SPDY , it fail.

Client log:
root@ubuntu:~# nghttp -uv https://192.168.0.109/ 
[  0.002][NPN] server offers:
          * h2-14
          * spdy/3.1
          * spdy/3
          * spdy/2
          * http/1.1
The negotiated protocol: h2-14
[  0.020] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.020] send HEADERS frame <length=32, flags=0x05, stream_id=1>
          ; END_STREAM | END_HEADERS
          (padlen=0)
          ; Open new stream
          :authority: 192.168.0.109
          :method: GET
          :path: /
          :scheme: https
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: nghttp2/0.6.6
[  0.021] recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.022] recv GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=INADEQUATE_SECURITY(0x0c), opaque_data(0)=[])
[  0.022] send SETTINGS frame <length=0, flags=0x01, stream_id=0>
          ; ACK
          (niv=0)
[ERROR] Network error
Some requests were not processed. total=1, processed=0

Server Log:
17/Nov/2014:15:56:38 +0800 PID3547 [INFO] shrpx.cc:1827 Resolving backend address
17/Nov/2014:15:56:38 +0800 PID3547 [INFO] shrpx.cc:139 Address resolution for 127.0.0.1 succeeded: 127.0.0.1
17/Nov/2014:15:56:38 +0800 PID3547 [INFO] shrpx.cc:224 Unable to get IPv6 address for 0.0.0.0: Address family for hostname not supported
17/Nov/2014:15:56:38 +0800 PID3547 [NOTICE] Listening on 0.0.0.0, port 443
17/Nov/2014:15:56:38 +0800 PID3547 [INFO] shrpx.cc:635 Entering event loop
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_listen_handler.cc:213 [LISTEN:0x7ff88ec3d780] Accepted connection. fd=11
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_client_handler.cc:128 [CLIENT_HANDLER:0x7ff88ec401d0] SSL/TLS handshake completed
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_client_handler.cc:298 [CLIENT_HANDLER:0x7ff88ec401d0] The negotiated next protocol: h2-14
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_http2_upstream.cc:587 [UPSTREAM:0x7ff88ec43900] Sending GOAWAY: last-stream-id=0, error_code=12, debug_data=
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_http2_upstream.cc:826 [UPSTREAM:0x7ff88ec43900] No more read/write for this HTTP2 session
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_client_handler.cc:220 [CLIENT_HANDLER:0x7ff88ec401d0] Deleting
17/Nov/2014:15:56:40 +0800 PID3547 [INFO] shrpx_client_handler.cc:253 [CLIENT_HANDLER:0x7ff88ec401d0] Deleted

When i try to use those ciphers which do not contain the DH or DHE algorithm,this Error happened.
I am no idea what happen? Do anyone know how to fix it?

Thanks.
C anonymous
Anonymous

**Comment by C4n0nymous** [comment]
While i update to the latest version, the problem happen again. I try to use the same method which make the check_http2_requirement function return true but it did not work in this time. When i check the pcap, i find that the server send a tls handshake failure to client. How can i void this cipher requirement in this time?

Thanks.
C anonymous
Anonymous

**Comment by tatsuhiro-t** [comment]
Latest master branch code does not require DHE or ECDHE ciphers now, but Chrome may require them.  In this case, we have no way to enable DHE or ECDHE in nghttpx to make Chrome happy.
I think Firefox has an option to disable this kind of security check if you can use Firefox instead of Chrome.

**Comment by C4n0nymous** [comment]
Thank you for your prompt reply.But the main problem is that the nghttp client only provide the DHE and ECDHE ciphers while connecting with the server. When i set the server using AES128-GCM-SHA256 chiper, i got tls handshake failure because the nghttp client do not support this chiper. Do you have any method the make the nghttp client support those chiper?

Thanks a lot.
C anonymous
Anonymous

**Comment by tatsuhiro-t** [comment]
Got it. Try b9c6162 which enables nghttp client to accept non-PFS ciphers.

**Comment by C4n0nymous** [comment]
Thanks a lot.
Problem solve.
