### ISSUE TITLE
asio Client Implementation

### ISSUE THREAD

**Issue by blakewatters** [tatsuhiro-t/nghttp2#122]
My team is currently looking at implementing an HTTP/2 implementation using nghttp2 in C++ for use across mobile clients (iOS, Android, and WinRT). We’re currently thinking of implementing it using nghttp2 with asio. 

We took note with great interest in the asio server work that has already been implemented within the project. We were wondering if there were any plans in place to extend this work into a client implementation or if there is any design documentation that we could use to pick up the effort and contribute back the implementation. We’re very keen on making this happen!

**Comment by tatsuhiro-t** [comment]
We've finally implemented client API in libnghttp2_asio: https://nghttp2.org/documentation/libnghttp2_asio.html#client-api
We also rewrite server API to make it more robust.
