### ISSUE TITLE
Firefox and chain issuer certificate problem

### ISSUE THREAD

**Issue by TrungACZNE** [tatsuhiro-t/nghttp2#132]
Hi

We've been using the nghttp2 for a while as a proxy in --http2-proxy mode. It works very well in Chrome but we have been trying to get it to work in Firefox but not as successful. 

We tried setting the proxy in Firefox through either the .pac file or (programmatically) through nsIProtocolProxyService. Whenever we attempt to connect to any page with the proxy it would say "host:port uses an invalid security certificate. The certificate is not trusted because no issuer chain was provided."

I think the issue is this one: http://www.gpickin.com/index.cfm/blog/techie-gotcha-ssl-certificate-problems-with-apache-and-issuer-chain (I found a lot of similar posts regarding Firefox & certificate chain file). I'm unsure how to set up the certificate like that for nghttp2 (since the guide in the link was for apache). 

Thanks for any help

**Comment by nubela** [comment]
@todesschaf solution worked.

Here's how you do it:

$ cat DOMAIN_CERT.crt INTERMEDIATE.crt ROOT.crt  >> bundle.crt

I figured it out from https://www.digicert.com/ssl-certificate-installation-nginx.htm

Issue is closed, thanks!
