### ISSUE TITLE
Unable to build from git on Ubuntu 12.04 (with and without threads)

### ISSUE THREAD

**Issue by nergoza** [tatsuhiro-t/nghttp2#135]
Error while compiling, with threads enabled:
make[3]: Entering directory `/home/lmimony/nghttp2/src'
  CXX    util.o
  CXX    http2.o
  CC     timegm.o
  CXX    libevent_util.o
  CXX    app_helper.o
  CXX    ssl.o
  CXX    shrpx_config.o
  CXX    shrpx_listen_handler.o
In file included from shrpx_listen_handler.cc:38:0:
shrpx_worker_config.h:45:5: error: 'thread_local' does not name a type
shrpx_listen_handler.cc: In function 'void shrpx::{anonymous}::evlistener_disable_cb(int, short int, void*)':
shrpx_listen_handler.cc:56:7: error: 'worker_config' was not declared in this scope
shrpx_listen_handler.cc: In function 'void shrpx::{anonymous}::worker_writecb(bufferevent*, void*)':
shrpx_listen_handler.cc:96:8: error: 'worker_config' was not declared in this scope
make[3]: *** [shrpx_listen_handler.o] Error 1
make[3]: Leaving directory `/home/lmimony/nghttp2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/lmimony/nghttp2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/lmimony/nghttp2'
make: *** [all] Error 2

With threads disabled:
  CXX    shrpx_downstream_queue.o
shrpx_downstream_queue.cc: In member function 'shrpx::DownstreamQueue::HostEntry& shrpx::DownstreamQueue::find_host_entry(const string&)':
shrpx_downstream_queue.cc:57:48: error: 'class std::map<std::basic_string<char>, shrpx::DownstreamQueue::HostEntry>' has no member named 'emplace'
make[3]: *** [shrpx_downstream_queue.o] Error 1
make[3]: Leaving directory `/home/lmimony/nghttp2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/lmimony/nghttp2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/lmimony/nghttp2'
make: *** [all] Error 2

Hope anyone can help, Thanks!

**Comment by tatsuhiro-t** [comment]
I think current master branch supports compilation with gcc-4.7 series.  Please reopen if this still bites you.
