### ISSUE TITLE
Support for TLS Session Tickets

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#138]
Hello,

I have been asked if nghttpx supports [TLS Session Tickets](http://www.ietf.org/rfc/rfc5077.txt). 

My packet analysis indicates that TLS Session Tickets are not supported but I wanted to confirm this, in order to rule out a configuration or environment that may be preventing this.

Lucas

**Comment by tatsuhiro-t** [comment]
TLS session ticket is disabled since it does not work with PFS ciphers nicely because default OpenSSL implementation does not rotate keys at all.
Currently I'm working with rotation of keys.  Once it is done, session ticket will be enabled by default.

**Comment by tatsuhiro-t** [comment]
Session ticket is now enabled by default via commit 52f3572d5b072c073be313d555d1bef291e60703.

**Comment by LPardue** [comment]
Great thank you!

I'll see if I can get to testing this new feature in my environment in the near future.

**Comment by LPardue** [comment]
I see in the code change that you use calls to OpenSSL EVP API. 

We are also investigating the use of AES-NI for hardware acceleration. I have tested the device with ``openssl speed`` toggling the ``-evp`` option. The tests show the machine and OpenSSL version do support AES-NI. However I am not 100% sure our deployment of nghttpx will also use AES-NI for everything possible.

My understanding is that it nghttpx should use AES-NI in this scenario but could you confirm that please?

**Comment by tatsuhiro-t** [comment]
Crypto operations including AES are solely done by OpenSSL library.  If linked OpenSSL supports AES-NI, then nghttpx will automatically get its benefit.

**Comment by LPardue** [comment]
Thank you for the clarification.
