### ISSUE TITLE
curl+nghttp2 negotiates with prohibited TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA cipher suite

### ISSUE THREAD

**Issue by bradfitz** [tatsuhiro-t/nghttp2#140]
github.com/bradfitz/http2's integration test with curl+nghttp2 is failing because curl (or nghttp2?) picks a prohibited TLS ciphersuite, which the Go server rejects, per the spec:

```
$ go get github.com/bradfitz/http2
$ cd $GOPATH/src/github.com/bradfitz/http2
$ docker build -t gohttp2/curl .   # see the Dockerfile in that directory
$ go test --run=TestServerWithCurl
2015/01/17 12:25:42 REJECTING conn: INADEQUATE_SECURITY, Prohibited TLS 1.2 Cipher Suite: c014
--- FAIL: TestServerWithCurl (0.44s)
        server_test.go:2124: Running test server for curl to hit at: https://127.0.0.1:55478
        server_test.go:2139: exit status 55: * Rebuilt URL to: https://127.0.0.1:55478/
                *   Trying 127.0.0.1...
                * Connected to 127.0.0.1 (127.0.0.1) port 55478 (#0)
                * successfully set certificate verify locations:
                *   CAfile: /etc/ssl/certs/ca-certificates.crt
                  CApath: none
                * TLSv1.2, TLS handshake, Client hello (1):
                } [272 bytes data]
                * TLSv1.2, TLS handshake, Server hello (2):
                { [59 bytes data]
                * NPN, negotiated HTTP2 (h2-14)
                * TLSv1.2, TLS handshake, CERT (11):
                { [389 bytes data]
                * TLSv1.2, TLS handshake, Server key exchange (12):
                { [141 bytes data]
                * TLSv1.2, TLS handshake, Server finished (14):
                { [4 bytes data]
                * TLSv1.2, TLS handshake, Client key exchange (16):
                } [70 bytes data]
                * TLSv1.2, TLS change cipher, Client hello (1):
                } [1 bytes data]
                * TLSv1.2, TLS handshake, Unknown (67):
                } [36 bytes data]
                * TLSv1.2, TLS handshake, Finished (20):
                } [16 bytes data]
                * TLSv1.2, TLS change cipher, Client hello (1):
                { [1 bytes data]
                * TLSv1.2, TLS handshake, Finished (20):
                { [16 bytes data]
                * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA
                * Server certificate:
                *        subject: O=Acme Co
                *        start date: 1970-01-01 00:00:00 GMT
                *        expire date: 2049-12-31 23:59:59 GMT
                *        issuer: O=Acme Co
                *        SSL certificate verify result: self signed certificate (18), continuing anyway.
                * Using HTTP2
                * http2_send len=79
                * before_frame_send() was called
                * SSL_write() returned SYSCALL, errno = 32
                * Failed sending HTTP2 data
                * Failed sending HTTP request
                * Connection #0 to host 127.0.0.1 left intact

FAIL
```

Cipher suite `0xc014` is:

```
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA      uint16 = 0xc014
```

Which is prohibited in in http://http2.github.io/http2-spec/#BadCipherSuites

Section 9.2.2 (http://http2.github.io/http2-spec/#rfc.section.9.2.2) says that the server can choose to accept it, or choose to deny it.

I've been choosing to deny it. Is there a reason that nghttp2 can't select a non-prohibited cipher?

/cc @agl @mpl

**Comment by bagder** [comment]
It is a curl/libcurl thing, not a nghttp2 thing. But yeah, libcurl doesn't (yet) implement the strict TLS requirements from the HTTP/2 spec.

**Comment by bradfitz** [comment]
@bagder, thanks. I admit I was too lazy to look into where the libcurl<->nghttp2 integration boundaries were.

I'll let @tatsuhiro-t close this if fixing this will be all on libcurl's side.

Should I open a libcurl bug at http://sourceforge.net/p/curl/bugs/? I see 20 open there, but nothing about HTTP/2 TLS requirements. Or can you file one?

**Comment by bagder** [comment]
Thanks, I filed https://sourceforge.net/p/curl/bugs/1472/ for this just now.

**Comment by tatsuhiro-t** [comment]
So, this is possible curl issue, I close this ticket.

Meanwhile, I think this issue may depend on cipher suites ordering and which side's preference (client or server) has precedence.
If I modified h2demo to prefer server's cipher suite ordering:
```
	srv.TLSConfig = &tls.Config {
		PreferServerCipherSuites: true,
	}
```

Then, TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256 is negotiated.
Without that, TLSv1.2 / ECDHE-RSA-AES256-SHA is used instead.

You may argue that HTTP/2 compliant client should order AEAD ciphers first, but as far as I know there is no such wording in HTTP/2 spec at them moment.  It might be safe to configure HTTP/2 server to list preferred ciphers first and make PreferServerCipherSuites on. But I am not expert of TLS, so not entirely sure it is a right thing to do.
