### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by szepeviktor** [tatsuhiro-t/nghttp2#144]
This project seems very complex. I plan to use it in production instead of Apache/nginx SSL/SPDY/HTTP2 support.
Do you suggest to use it on low traffic sites?

Thank you very much!!
Also very nice to have the Debian package.

**Comment by tatsuhiro-t** [comment]
The libnghttp2 API is rather low level right now to offer everything http2 can do offer.

For production use, we use nghttpx reverse proxy in front of nginx to operare https://nghttp2.org.  nghttpx supports http2, http1.1 and spdy and terminates TLS traffic, forwarding them to backend http1.1 server in cleartext http1.1.
If this deployment style suites you, you can use nghttpx out of the box.

**Comment by szepeviktor** [comment]
Thank you!
