### ISSUE TITLE
TLS 1.0 on nghttp2.org

### ISSUE THREAD

**Issue by szepeviktor** [tatsuhiro-t/nghttp2#146]
Please consider enabling TLS 1.0
https://www.ssllabs.com/ssltest/analyze.html?d=nghttp2.org

**Comment by tatsuhiro-t** [comment]
TLSv1.0 has been enabled on nghttp2.org.  Please note that HTTP/2 is only available with TLSv1.2.

**Comment by szepeviktor** [comment]
Thank you!
