### ISSUE TITLE
SNI documentation

### ISSUE THREAD

**Issue by szepeviktor** [tatsuhiro-t/nghttp2#147]
Could you point out somewhere how to set up an SNI-capable reverse proxy for multiple sites?

**Comment by szepeviktor** [comment]
Just use `--subcert=<KEYPATH>:<CERTPATH>` multiple times and `nghttpx` will find out?

**Comment by tatsuhiro-t** [comment]
Yes

**Comment by szepeviktor** [comment]
Thank you!
