### ISSUE TITLE
Keep getting HTTP status code 503 

### ISSUE THREAD

**Issue by nergoza** [tatsuhiro-t/nghttp2#148]
Hi,
this is my syntax:
nghttpx -o --http2-bridge -f172.24.178.176,8443 -b172.24.178.146,443 localhost.key localhost.crt

Each time I try to connect from http2 client and from http1.1 \ spdy client I'm getting this:
<!DOCTYPE html><html lang=en><title>503 Service Unavailable</title><body><h1>503 Service Unavailable</h1><footer>nghttpx nghttp2/0.7.4-DEV at port 8443</footer></body></html>[  0.010] recv DATA frame <length=174, flags=0x01, stream_id=1>

I can't find the cause of this issue
Hope to get help

Thanks!

**Comment by acesso** [comment]
Hello nergoza,

Is your backend running with http2(TLS) at 172.24.178.146:443 ? I could not open connection from here to it at this time. Maybe it´s running on a firewalled port, if running on the same machine you prolly better use 127.0.0.0,443 as backend addres to avoid any blocking.

**Comment by nergoza** [comment]
Please note that the backend server is NOT http/2 - it's Apache with http 1.1 and SPDY over TLS

**Comment by nergoza** [comment]
Hi acesso,
No it's 1.1 with SPDY support and I cannot get nghttpx running on the backend server.

**Comment by nergoza** [comment]
it's internal address you won't be able to connect from there

**Comment by nergoza** [comment]
Is there a mode for the proxy to accept 1.1 connections and transmit them as http2 to the backend server?
Because that's what I'm looking for

**Comment by acesso** [comment]
Hello nergoza,

As far as I know the backend shoud be using http1.1 (no tls) or http2(TLS) , since your backend accept http1.1 requests you should be good with default mode instead of --http2-bridge option, just make sure to use the proper port for this since 443 is runinig on TLS.

**Comment by tatsuhiro-t** [comment]
If you specify --http2-bridge, nghttpx requires HTTP/2 server in backend.
If you want to use HTTP/1.1 in backend link, don't use --http2-bridge. Unfortunately, nghttpx does not support TLS connection in backend HTTP/1.1 link.
So if you want to connect to HTTP/1.1 backend link, backend server must be cleartext HTTP/1.1 (no TLS).

**Comment by tatsuhiro-t** [comment]
I forgot to mention that nghttpx supports SPDY in frontend connection only.

**Comment by nergoza** [comment]
oh, that's bad for me :(
I need a way to send HTTP 1.1 requests and convert them to HTTP 2 with TLS in the backend :(

**Comment by tatsuhiro-t** [comment]
But you wrote that your backend server supports HTTP/1.1 and SPDY, not HTTP/2 right?

**Comment by tatsuhiro-t** [comment]
Note that SPDY and HTTP/2 are completely different things.  They are incompatible.

**Comment by nergoza** [comment]
I forgot to mention that it happend on HTTP2 TLS server as well

**Comment by tatsuhiro-t** [comment]
So you have proper HTTP/2 backend server accepting TLS connection (which implementation?).
Then nghttpx should connect to it.
--http2-bridge is used in this case.  If backend server's certificate is self-signed, nghttpx refuses to connect to it.  To skip certificate validation (which is insecure, but you know it now), use -k option.

**Comment by nergoza** [comment]
it's h2-14
and I did use -k but still getting 503.
When I go standalone just with the nghttp client to my server it works fine.
Issue is with the proxy

**Comment by tatsuhiro-t** [comment]
Right, then you can use -LINFO option to produce debug logging.  What does it say?

**Comment by nergoza** [comment]
Hi, with http2-bridge it looks likes the proxy is unable to connect to the backend server for unknown reason:

03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_connection_handler.cc:161 [LISTEN:0x7f13e5c28540] Accepted connection. fd=7
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_client_handler.cc:210 [CLIENT_HANDLER:0x7f13e5d13000] SSL/TLS handshake completed
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_client_handler.cc:700 [CLIENT_HANDLER:0x7f13e5d13000] No protocol negotiated. Fallback to HTTP/1.1
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_https_upstream.cc:63 [UPSTREAM:0x7f13e5c331d0] HTTP request started
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_https_upstream.cc:134 [UPSTREAM:0x7f13e5c331d0] HTTP request headers completed
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_https_upstream.cc:156 [UPSTREAM:0x7f13e5c331d0] HTTP request headers
GET / HTTP/1.1
User-Agent: curl/7.40.0-DEV
Host: 172.24.178.176:8443
Accept: */*

03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_client_handler.cc:759 [CLIENT_HANDLER:0x7f13e5d13000] Downstream connection pool is empty. Create new one
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_http2_downstream_connection.cc:100 [DCONN:0x7f13e5c23850] Attaching to DOWNSTREAM:0x7f13e5c36200
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_https_upstream.cc:219 [UPSTREAM:0x7f13e5c331d0] HTTP request completed
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_http2_session.cc:121 wrschedcb start connect
03/Feb/2015:07:41:23 +0200 PID3167 [INFO] shrpx_http2_session.cc:306 [DHTTP2:0x7f13e5d00000] Connecting to downstream server
3/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_http2_session.cc:79 [DHTTP2:0x7f13e5d00000] Timeout
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_http2_session.cc:176 [DHTTP2:0x7f13e5d00000] Disconnecting
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_http2_session.cc:206 [DHTTP2:0x7f13e5d00000] Closing fd=8
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_http2_downstream_connection.cc:53 [DCONN:0x7f13e5c23850] Deleting
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_http2_downstream_connection.cc:94 [DCONN:0x7f13e5c23850] Deleted
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_downstream.cc:147 [DOWNSTREAM:0x7f13e5c36200] Deleting
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_downstream.cc:161 [DOWNSTREAM:0x7f13e5c36200] Deleted
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_client_handler.cc:539 [CLIENT_HANDLER:0x7f13e5d13000] Deleting
03/Feb/2015:07:41:53 +0200 PID3167 [INFO] shrpx_client_handler.cc:576 [CLIENT_HANDLER:0x7f13e5d13000] Deleted

**Comment by nergoza** [comment]
It's not related to the proxy - I'm checking

**Comment by nergoza** [comment]
I fixed the connectivity issue - Now I'm getting status code 400 - bad request:

03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:1819 Resolving backend address
03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:125 Address resolution for spdy.ssltest.serverX.com succeeded: 100.64.17.171
03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:184 Unable to get IPv6 address for 172.24.178.176: Address family for hostname not supported
03/Feb/2015:09:33:47 +0200 PID3307 [NOTICE] Listening on 172.24.178.176, port 8443
03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:457 renew ticket key
03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:481 ticket keys generation done
03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:483 name: 68d39a340566809c45a00f8b1a0b875f
03/Feb/2015:09:33:47 +0200 PID3307 [INFO] shrpx.cc:596 Entering event loop
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_connection_handler.cc:161 [LISTEN:0x7f5985828540] Accepted connection. fd=7
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_ssl.cc:195 [CLIENT_HANDLER:0x7f5985913000] session ticket key 96c0147d567f01ff78e61f2f79d283ee not found
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_ssl.cc:173 [CLIENT_HANDLER:0x7f5985913000] encrypt session ticket key: 68d39a340566809c45a00f8b1a0b875f
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:210 [CLIENT_HANDLER:0x7f5985913000] SSL/TLS handshake completed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:613 [CLIENT_HANDLER:0x7f5985913000] The negotiated next protocol: spdy/3.1
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:539 [CLIENT_HANDLER:0x7f5985913000] Deleting
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:576 [CLIENT_HANDLER:0x7f5985913000] Deleted
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_connection_handler.cc:161 [LISTEN:0x7f5985828540] Accepted connection. fd=7
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_ssl.cc:173 [CLIENT_HANDLER:0x7f5985913000] encrypt session ticket key: 68d39a340566809c45a00f8b1a0b875f
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:210 [CLIENT_HANDLER:0x7f5985913000] SSL/TLS handshake completed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:613 [CLIENT_HANDLER:0x7f5985913000] The negotiated next protocol: spdy/3.1
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_spdy_upstream.cc:148 [UPSTREAM:0x7f59858ccc80] Received upstream SYN_STREAM stream_id=1
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_spdy_upstream.cc:164 [UPSTREAM:0x7f59858ccc80] HTTP request headers. stream_id=1
:host: 172.24.178.176:8443
:method: GET
:path: /1.html
:scheme: https
:version: HTTP/1.1
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding: gzip, deflate, sdch
accept-language: en-US,en;q=0.8,he;q=0.6
cache-control: max-age=0
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:759 [CLIENT_HANDLER:0x7f5985913000] Downstream connection pool is empty. Create new one
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_downstream_connection.cc:100 [DCONN:0x7f5985823610] Attaching to DOWNSTREAM:0x7f5985836200
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:121 wrschedcb start connect
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:306 [DHTTP2:0x7f5985900000] Connecting to downstream server
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:1525 [DHTTP2:0x7f5985900000] Connection established
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:1658 [DHTTP2:0x7f5985900000] SSL/TLS handshake completed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:1183 [DHTTP2:0x7f5985900000] Negotiated next protocol: h2-14
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_downstream_connection.cc:409 [DCONN:0x7f5985823610] HTTP request headers
:scheme: https
:path: /1.html
:authority: 172.24.178.176:8443
:method: GET
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding: gzip, deflate, sdch
accept-language: en-US,en;q=0.8,he;q=0.6
cache-control: max-age=0
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
x-forwarded-proto: https
via: 1.1 nghttpx

03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:819 [DHTTP2:0x7f5985900000] HTTP response headers. stream_id=1
:status: 400
content-length: 198
content-type: text/html
date: Tue, 03 Feb 2015 07:33:40 GMT
expires: Tue, 03 Feb 2015 07:33:40 GMT
mime-version: 1.0
server: ServerX

03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_spdy_upstream.cc:838 [DOWNSTREAM:0x7f5985836200] HTTP response header completed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_spdy_upstream.cc:917 [UPSTREAM:0x7f59858ccc80] HTTP response headers. stream_id=1
:status: 400 Bad Request
:version: HTTP/1.1
content-length: 198
content-type: text/html
date: Tue, 03 Feb 2015 07:33:40 GMT
expires: Tue, 03 Feb 2015 07:33:40 GMT
mime-version: 1.0
server: nghttpx nghttp2/0.7.4-DEV
via: 2.0 nghttpx

03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_spdy_upstream.cc:956 [DOWNSTREAM:0x7f5985836200] HTTP response completed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_session.cc:636 [DHTTP2:0x7f5985900000] Stream stream_id=1 is being closed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_spdy_upstream.cc:95 [UPSTREAM:0x7f59858ccc80] Stream stream_id=1 is being closed
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_http2_downstream_connection.cc:115 [DCONN:0x7f5985823610] Detaching from DOWNSTREAM:0x7f5985836200
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_client_handler.cc:739 [CLIENT_HANDLER:0x7f5985913000] Pooling downstream connection DCONN:0x7f5985823610
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_downstream.cc:147 [DOWNSTREAM:0x7f5985836200] Deleting
03/Feb/2015:09:33:49 +0200 PID3307 [INFO] shrpx_downstream.cc:161 [DOWNSTREAM:0x7f5985836200] Deleted
03/Feb/2015:09:33:54 +0200 PID3307 [INFO] shrpx_http2_session.cc:54 [DHTTP2:0x7f5985900000] connection check required

**Comment by tatsuhiro-t** [comment]
Because spdy/3.1 is negotiated.  Make sure that backend http2 server only
accept h2-14 and disable spdy.

**Comment by tatsuhiro-t** [comment]
Forget my previous comment. It was completely wrong.

**Comment by nergoza** [comment]
Yeah it didn't help as well - still getting that 400 code

**Comment by nergoza** [comment]
Please note that the backend server is another forward proxy that supports HTTP 2 on TLS

**Comment by nergoza** [comment]
Please anyone?

**Comment by tatsuhiro-t** [comment]
Since there are multiple proxies involved, I'm not sure which server sends back 400 bad request.
Can you check this out?
Could you also describe whole deployment of your servers? It would be better for us to understand situation.

I think the request header in the log is valid, but if backend proxy is too picky about :authority header field, then it might reject it.  Could you apply the following patch and see whether it makes difference?
```
diff --git a/src/shrpx_downstream.cc b/src/shrpx_downstream.cc
index d1985f8..49fe7db 100644
--- a/src/shrpx_downstream.cc
+++ b/src/shrpx_downstream.cc
@@ -528,6 +528,18 @@ const Headers::value_type *Downstream::get_response_header(int token) const {
   return http2::get_header(response_hdidx_, token, response_headers_);
 }
 
+void Downstream::rewrite_host_request_header() {
+  if (!request_http2_authority_.empty()) {
+    request_http2_authority_ = get_config()->downstream_addrs[0].hostport.get();
+  }
+  auto hd = http2::get_header(request_hdidx_, http2::HD_HOST, request_headers_);
+  if (hd) {
+    auto idx = request_hdidx_[http2::HD_HOST];
+    request_headers_[idx].value =
+        get_config()->downstream_addrs[0].hostport.get();
+  }
+}
+
 void
 Downstream::rewrite_location_response_header(const std::string &upstream_scheme,
                                              uint16_t upstream_port) {
diff --git a/src/shrpx_downstream.h b/src/shrpx_downstream.h
index 7d4e702..9c4aba9 100644
--- a/src/shrpx_downstream.h
+++ b/src/shrpx_downstream.h
@@ -166,6 +166,8 @@ public:
   int64_t get_request_content_length() const;
   void set_request_content_length(int64_t len);
   bool request_pseudo_header_allowed(int token) const;
+  void rewrite_host_request_header();
+
   bool expect_response_body() const;
   enum {
     INITIAL,
diff --git a/src/shrpx_http2_upstream.cc b/src/shrpx_http2_upstream.cc
index f7c8ee7..ec1a867 100644
--- a/src/shrpx_http2_upstream.cc
+++ b/src/shrpx_http2_upstream.cc
@@ -319,6 +319,10 @@ int on_request_headers(Http2Upstream *upstream, Downstream *downstream,
   downstream->set_request_http2_authority(http2::value_to_str(authority));
   downstream->set_request_path(http2::value_to_str(path));
 
+  if (!get_config()->http2_proxy && !get_config()->client_proxy) {
+    downstream->rewrite_host_request_header();
+  }
+
   if (!(frame->hd.flags & NGHTTP2_FLAG_END_STREAM)) {
     downstream->set_request_http2_expect_body(true);
   }
diff --git a/src/shrpx_https_upstream.cc b/src/shrpx_https_upstream.cc
index e2d5b2e..347b7c7 100644
--- a/src/shrpx_https_upstream.cc
+++ b/src/shrpx_https_upstream.cc
@@ -176,6 +176,10 @@ int htp_hdrs_completecb(http_parser *htp) {
     }
   }
 
+  if (!get_config()->http2_proxy && !get_config()->client_proxy) {
+    downstream->rewrite_host_request_header();
+  }
+
   rv = downstream->attach_downstream_connection(
       upstream->get_client_handler()->get_downstream_connection());
 
diff --git a/src/shrpx_spdy_upstream.cc b/src/shrpx_spdy_upstream.cc
index 3a20275..9f39de2 100644
--- a/src/shrpx_spdy_upstream.cc
+++ b/src/shrpx_spdy_upstream.cc
@@ -201,6 +201,10 @@ void on_ctrl_recv_callback(spdylay_session *session, spdylay_frame_type type,
 
     downstream->inspect_http2_request();
 
+    if (!get_config()->http2_proxy && !get_config()->client_proxy) {
+      downstream->rewrite_host_request_header();
+    }
+
     downstream->set_request_state(Downstream::HEADER_COMPLETE);
     if (frame->syn_stream.hd.flags & SPDYLAY_CTRL_FLAG_FIN) {
       if (!downstream->validate_request_bodylen()) {
```

**Comment by nergoza** [comment]
Really thanks for the support tatsuhiro-t!
I cannot say at the moment which deployment I'm using since it's the company I'm working for.
I checked the logs in my backend proxy my backend server is sending the 400 status code for invalid URL or HOST

I'll check the patch

**Comment by tatsuhiro-t** [comment]
Could you tell me the name of backend server implementation? Is it another nghttpx or something else?

**Comment by nergoza** [comment]
It's the company own implementation - Akamai Inc.

BTW, the patch seems to fixed the issue!
I'm going to check it now with full scale performance testing.

Thanks again!

**Comment by tatsuhiro-t** [comment]
Thanks.  I'll try to merge this fix to master, since nginx does this by default.  Probably add an option to disable rewriting for some use cases.

**Comment by nergoza** [comment]
Mate, I'll explain my current setup:
I'm using Avalanche as my loading tool - the clients can send only HTTP 1.1 - I'll send them to the NGHTTPX proxy with --http2-bridge and the backend server my forward proxy with HTTP2 enabled and TLS.

Now when I'm not using Chrome but my Avalanche clients I'm getting this in the nghttpx proxy:
03/Feb/2015:14:47:05 +0200 PID11324 [INFO] shrpx_client_handler.cc:409 [CLIENT_HANDLER:0x7f6f8a3e1000] invalid client connection header
03/Feb/2015:14:47:05 +0200 PID11324 [INFO] shrpx_client_handler.cc:539 [CLIENT_HANDLER:0x7f6f8a3e1000] Deleting
03/Feb/2015:14:47:05 +0200 PID11324 [INFO] shrpx_client_handler.cc:576 [CLIENT_HANDLER:0x7f6f8a3e1000] Deleted

**Comment by nergoza** [comment]
full log:
03/Feb/2015:15:01:15 +0200 PID11351 [INFO] shrpx_ssl.cc:173 [CLIENT_HANDLER:0x7f6d9013f000] encrypt session ticket key: 9d28afc90f1a2de9a901743627fa9957
03/Feb/2015:15:01:15 +0200 PID11351 [INFO] shrpx_client_handler.cc:210 [CLIENT_HANDLER:0x7f6d9013f000] SSL/TLS handshake completed
03/Feb/2015:15:01:15 +0200 PID11351 [INFO] shrpx_client_handler.cc:613 [CLIENT_HANDLER:0x7f6d9013f000] The negotiated next protocol: h2-16
03/Feb/2015:15:01:15 +0200 PID11351 [INFO] shrpx_client_handler.cc:409 [CLIENT_HANDLER:0x7f6d9013f000] invalid client connection header
03/Feb/2015:15:01:15 +0200 PID11351 [INFO] shrpx_client_handler.cc:539 [CLIENT_HANDLER:0x7f6d9013f000] Deleting
03/Feb/2015:15:01:15 +0200 PID11351 [INFO] shrpx_client_handler.cc:576 [CLIENT_HANDLER:0x7f6d9013f000] Deleted

**Comment by nergoza** [comment]
looks like the proxy is not accepting HTTP 1.1 requests and expecting only HTTP2 \ SPDY

**Comment by tatsuhiro-t** [comment]
h2-16 was negotiated between load test tool and nghttpx.
Make sure that load test tool does not send any NPN/ALPN related TLS extension.

**Comment by nergoza** [comment]
When TLS 1.2 (with and without TLS SNI) is selected in the client it somehow doing it as h2-16 - when I set it to use SSLv3 or TLS 1.1 this is only the output I'm getting:
03/Feb/2015:16:01:03 +0200 PID11351 [INFO] shrpx_connection_handler.cc:161 [LISTEN:0x7f6d90c28540] Accepted connection. fd=7
03/Feb/2015:16:01:03 +0200 PID11351 [INFO] shrpx_client_handler.cc:539 [CLIENT_HANDLER:0x7f6d9010b000] Deleting
03/Feb/2015:16:01:03 +0200 PID11351 [INFO] shrpx_client_handler.cc:576 [CLIENT_HANDLER:0x7f6d9010b000] Deleted

Maybe it's something related to one of the TLS 1.2 ciphers?

**Comment by tatsuhiro-t** [comment]
TLSv1.2 is required for HTTP/2 but not the other way around.  Probably, load test tool support HTTP/2?
Actually the log you showed above proves nghttpx negotiated spdy/3.1 successfully.

If TLS bothers you and load test tool can send cleartext HTTP/1.1, you can run nghttpx with --client instead of --http2-bridge, which only accepts HTTP/1.1 cleartext in frontend.

**Comment by nergoza** [comment]
With --http2-bridge and --froentend-no-tls I'm getting RST_STREAM - I can see in my backend server that the connection dropped due to RST sent - but why? 
i
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:121 wrschedcb start connect
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:306 [DHTTP2:0x7fdf830d1000] Connecting to downstream server
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1525 [DHTTP2:0x7fdf830d1000] Connection established
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_connection_handler.cc:161 [LISTEN:0x7fdf83028540] Accepted connection. fd=8
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_client_handler.cc:442 [CLIENT_HANDLER:0x7fdf830e4000] This is HTTP/1.1 connection, but may be upgraded to HTTP/2 later.
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_https_upstream.cc:63 [UPSTREAM:0x7fdf830332b0] HTTP request started
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_https_upstream.cc:134 [UPSTREAM:0x7fdf830332b0] HTTP request headers completed
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_https_upstream.cc:156 [UPSTREAM:0x7fdf830332b0] HTTP request headers
GET /1.html HTTP/1.1
Host: http2.proxy.com:8080
Connection: keep-alive
Cache-Control: max-age=0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8,he;q=0.6

03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_client_handler.cc:759 [CLIENT_HANDLER:0x7fdf830e4000] Downstream connection pool is empty. Create new one
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_downstream_connection.cc:100 [DCONN:0x7fdf83023820] Attaching to DOWNSTREAM:0x7fdf83035c00
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_https_upstream.cc:223 [UPSTREAM:0x7fdf830332b0] HTTP request completed
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1658 [DHTTP2:0x7fdf830d1000] SSL/TLS handshake completed
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1183 [DHTTP2:0x7fdf830d1000] Negotiated next protocol: h2-14
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_downstream_connection.cc:409 [DCONN:0x7fdf83023820] HTTP request headers
:scheme: http
:path: /1.html
:method: GET
host: spdy.ssltest.akamai.com:443
cache-control: max-age=0
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36
accept-encoding: gzip, deflate, sdch
accept-language: en-US,en;q=0.8,he;q=0.6
x-forwarded-proto: http
via: 1.1 nghttpx

03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:636 [DHTTP2:0x7fdf830d1000] Stream stream_id=1 is being closed
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_client_handler.cc:539 [CLIENT_HANDLER:0x7fdf830e4000] Deleting
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_client_handler.cc:576 [CLIENT_HANDLER:0x7fdf830e4000] Deleted
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_downstream.cc:147 [DOWNSTREAM:0x7fdf83035c00] Deleting
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_downstream.cc:161 [DOWNSTREAM:0x7fdf83035c00] Deleted
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_downstream_connection.cc:53 [DCONN:0x7fdf83023820] Deleting
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_downstream_connection.cc:71 [DCONN:0x7fdf83023820] Submit RST_STREAM for DOWNSTREAM:0x7fdf83035c00, stream_id=1, error_code=2
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_downstream_connection.cc:94 [DCONN:0x7fdf83023820] Deleted
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1354 [DHTTP2:0x7fdf830d1000] No more read/write for this HTTP2 session
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:176 [DHTTP2:0x7fdf830d1000] Disconnecting
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:206 [DHTTP2:0x7fdf830d1000] Closing fd=7
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:121 wrschedcb start connect
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:306 [DHTTP2:0x7fdf830d1000] Connecting to downstream server
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1525 [DHTTP2:0x7fdf830d1000] Connection established
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1658 [DHTTP2:0x7fdf830d1000] SSL/TLS handshake completed
03/Feb/2015:16:42:31 +0200 PID11677 [INFO] shrpx_http2_session.cc:1183 [DHTTP2:0x7fdf830d1000] Negotiated next protocol: h2-14
03/Feb/2015:16:42:36 +0200 PID11677 [INFO] shrpx_http2_session.cc:54 [DHTTP2:0x7fdf830d1000] connection check required

**Comment by nergoza** [comment]
I don't have info on that header - not even in the Internet.
Can I set the proxy to send this header ?

**Comment by tatsuhiro-t** [comment]
Did you ask akamai dev about this issue?
To send the header field, another patch is needed.

**Comment by nergoza** [comment]
it's an header in the HTTP request or the TCP?
They have no info on that

**Comment by tatsuhiro-t** [comment]
:authority header field is defined solely by HTTP/2 and so it is HTTP level header field. It works like Host header field in HTTP/1. HTTP/2 draft specification defines it.

**Comment by nergoza** [comment]
Oh, do you have ETA on releasing the patch that will support this header?

**Comment by nergoza** [comment]
But when I'm using Chrome it works fine - only when I'm using my loading tool I get this issue . 
Any other way to bypass it?

**Comment by nergoza** [comment]
tatsuhiro-t ? :(

**Comment by tatsuhiro-t** [comment]
I have other things to do right now. Will make a patch in a few hours.

**Comment by nergoza** [comment]
That's an amazing news mate, hope this will finally fix my issues.
I want to give you a donation for your efforts, can I get a paypal address in private?

**Comment by tatsuhiro-t** [comment]
Donation is very appreciated. Thanks.

Here is the patch to send :authority header field:
```
diff --git a/src/shrpx_http2_downstream_connection.cc b/src/shrpx_http2_downstream_connection.cc
index 6b2b17a..bacdbab 100644
--- a/src/shrpx_http2_downstream_connection.cc
+++ b/src/shrpx_http2_downstream_connection.cc
@@ -260,6 +260,10 @@ int Http2DownstreamConnection::push_request_headers() {
     host = get_config()->downstream_addrs[0].hostport.get();
   }
 
+  if (!authority) {
+    authority = get_config()->downstream_addrs[0].hostport.get();
+  }
+
   size_t nheader = downstream_->get_request_headers().size();
 
   Headers cookies;
```

This patch is applicable to latest master branch, which includes the patch I pasted yesterday.

But I really think akamai server should be fixed to accept the request without :authority header field, otherwise it is not standard compliant.

**Comment by nergoza** [comment]
Thanks mate - Please send me your PayPal address for the donation.
But I can't apply the patch

patch -p1 < newp.patch 
patching file src/shrpx_http2_downstream_connection.cc
Hunk #1 FAILED at 260.
1 out of 1 hunk FAILED -- saving rejects to file src/shrpx_http2_downstream_connection.cc.rej

**Comment by tatsuhiro-t** [comment]
patch is for latest master branch.  Can you pull latest source?
If you cannot pull, then following patch should work:
```
diff --git a/src/shrpx_http2_downstream_connection.cc b/src/shrpx_http2_downstream_connection.cc
index 72f8645..ea655f7 100644
--- a/src/shrpx_http2_downstream_connection.cc
+++ b/src/shrpx_http2_downstream_connection.cc
@@ -330,11 +330,9 @@ int Http2DownstreamConnection::push_request_headers() {
         authority += util::utos(u.port);
       }
       nva.push_back(http2::make_nv_ls(":authority", authority));
-    } else if (!downstream_->get_request_header(http2::HD_HOST)) {
-      if (LOG_ENABLED(INFO)) {
-        DCLOG(INFO, this) << "host header field missing";
-      }
-      return -1;
+    } else {
+      nva.push_back(http2::make_nv_lc(
+          ":authority", get_config()->downstream_addrs[0].hostport.get()));
     }
   }
 
```

Could you tell me your mail address? Then I'll send my address.

**Comment by nergoza** [comment]
tatsuhiro-t YOU ARE AMAZING - it worked !
Please forward me a way to give your a gift with money for this amazing fixes!

**Comment by nergoza** [comment]
reactor.leet [at] gmail [dot] com
