### ISSUE TITLE
[patch] version 0.70 doesn't build on platforms without SOCK_CLOEXEC

### ISSUE THREAD

**Issue by jrmarino** [tatsuhiro-t/nghttp2#150]
Hello,
On util.cc, SOCK_CLOEXEC and SOCK_NONBLOCK are used without testing.  The following patch will restore the build on platforms that don't have support for these:

    --- src/util.h.orig     2015-01-06 16:44:23 UTC
    +++ src/util.h
    @@ -41,6 +41,14 @@
    
     #include "http-parser/http_parser.h"
    
    +#ifndef SOCK_NONBLOCK
    +#define SOCK_NONBLOCK 0
    +#endif // !SOCK_NONBLOCK
    +
    +#ifndef SOCK_CLOEXEC
    +#define SOCK_CLOEXEC 0
    +#endif // !SOCK_CLOEXEC
    +
     namespace nghttp2 {
    
     // The additional HTTP/2 protocol ALPN ID we also supports for our

The same code is found on src/shrpx.h, so it was just copied from there.

**Comment by tatsuhiro-t** [comment]
Current master branch code checks SOCK_NONBLOCK.  Could you build the source using latest master branch?
Also I think the above patch does not work since if we don't have these flags, we have to make socket non-block and cloexec in another way (e.g., fcntl).

**Comment by jrmarino** [comment]
I  can't easily check master.  When freebsd ports is updated, I get that code the corresponds to that version.  When the version hit 0.7.0, the build failed.

I understand having non blocking / noncloexec sockets isn't supported - I was more concerned about alerting about this than fixing the port as nghttp2 is still "beta" I guess?

**Comment by tatsuhiro-t** [comment]
Well, then I think freebsd port is a bit behind.  If they get version, the problem goes away.

**Comment by jrmarino** [comment]
so you think it's already fixed on v0.7.3 ?
The non-blocking sockets are supported on v0.7.3?

**Comment by jrmarino** [comment]
By the way, this affects DragonFly BSD which uses FreeBSD ports tree.  I think FreeBSD has SOCK_CLOEXEC support.

**Comment by tatsuhiro-t** [comment]
v0.7.3 should work.
If SOCK_NONBLOCK is not found, we don't use both SOCK_NONBLOCK and SOCK_CLOEXEC,  instead use fnctl.  You may argue that we should check SOCK_CLOEXEC too, and I completely agree.

**Comment by jrmarino** [comment]
I think the logic is okay. :)
I'll ask sunpoet to update to v0.7.3 so we can see how that works.

**Comment by jrmarino** [comment]
This particular issue was fixed.
