### ISSUE TITLE
example/client.c was often failed

### ISSUE THREAD

**Issue by matsumoto-r** [tatsuhiro-t/nghttp2#152]
Thank you for your great HTTP/2 library. I always use this software as a reference to develop trusterd.

I run the `examples/libevent-server` with below command. 

```
./examples/libevent-server 8080 server.key server.crt
```

and send request to the server using `example/client`.

```
$ for i in `seq 1 100`; do ./client https://127.0.0.1:8080/index.html | grep FATAL; done
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
```

`example/client` was often failed.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  It seems FATAL message for just EOF is a bit exaggerating, but client is just a toy program for now, and it really has nothing to do on EOF.

**Comment by matsumoto-r** [comment]
Thank you for your advice. More information. I run nghttpd and send request by `example/client` using the same command. But, FATAL message didn't occurred. So, it seems not `example/client` but `example/libevent-server` have this problem. What do you think?

**Comment by tatsuhiro-t** [comment]
I have not got EOF with both libevent-server and nghttpd.
But I noticed that libevent-server sometimes sends GOAWAY without response.
Something is wrong here. I'll look into it.

**Comment by tatsuhiro-t** [comment]
I found the cause.  client does not send SETTINGS. The reason why sometimes it works and sometimes doesn't is that nghttp2 function does not check SETTINGS ACK flag for the first frame.
If client sends HEADERS before server's SETTINGS, then nghttp2 lib automatically sends SETTINGS with ACK, and nghttp2 lib wrongly see it as connection preface and go on.  This is working case.
Otherwse, HEADERS arrives before SETTINGS with ACK on server and server sends GOAWAY and drops connection. I'll fix this issue. Thank you very much.

**Comment by tatsuhiro-t** [comment]
Fix committed via  2dd6353e24dd8e9d1040d1042571a75eb9e141f6 and   f93a2b71a17d7032a312022486f45a336c926d95.
Could you verify that it works?

**Comment by matsumoto-r** [comment]
Thank you for quick response and fixing. I have checked this and everything was solved by these commits! Thanks again!

**Comment by crinaZhao** [comment]
I have this issue,too. Even though the lib includes this change.
My libnghttp2 version 1.20
Print:
FATAL: nghttp2_session_recv: error_code=-507, msg=EOF
