### ISSUE TITLE
shrpx_client_handler.cc:527:28: error: use of undeclared identifier 'ssl_'

### ISSUE THREAD

**Issue by kjunichi** [tatsuhiro-t/nghttp2#153]
I got above error message.

openssl version is 1.0.2.
os is osx yosemite.

I change shrpx_client_handler.cc

```
SSL_get0_alpn_selected(ssl_, &next_proto, &next_proto_len);
```

to 

```
SSL_get0_alpn_selected(conn_.tls.ssl, &next_proto, &next_proto_len);
```

Compile error has gone.

Thank you.

**Comment by tatsuhiro-t** [comment]
Thank you for noticing this.  Fix committed via 90746cd
