### ISSUE TITLE
shrpx.cc:205:5: error: use of undeclared identifier 'make_socket_nonblocking';

### ISSUE THREAD

**Issue by kjunichi** [tatsuhiro-t/nghttp2#154]
Hi.
I got above error message.

os is osx yosemite.
clang version is Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)

actualy,i got that.

```shell-session
shrpx.cc:205:5: error: use of undeclared identifier 'make_socket_nonblocking'; did you mean
      'nghttp2::util::make_socket_nonblocking'?
    make_socket_nonblocking(fd);
    ^~~~~~~~~~~~~~~~~~~~~~~
    nghttp2::util::make_socket_nonblocking
./util.h:485:5: note: 'nghttp2::util::make_socket_nonblocking' declared here
int make_socket_nonblocking(int fd);
    ^
```

So, I change the code 

```c
make_socket_nonblocking(fd);
```

to 

```c
nghttp2::util::make_socket_nonblocking(fd)
```

.When I changed the code,i have no build error.

Sorry.so many times to create issues.

Thank you.

**Comment by tatsuhiro-t** [comment]
Bug report is always welcome.  It makes our project better.
Fix committed via 4dea318.  Thank you!
