### ISSUE TITLE
Make client HTTP/1.1 requests abortable

### ISSUE THREAD

**Issue by devlearner** [tatsuhiro-t/nghttp2#156]
Thanks for the great piece of software. Saw that nghttp2 just got HTTP/2 push, it's just getting better!

Just one thing I happened to notice, when the incoming request is in HTTP/1.1, when the client aborts the request (say, half-way through the connection before the server returns the reply), the request upstream isn't aborted as well, and thus the upstream server continues to send the reply even when the client that initiated the request has already disconnected from the nghttpx proxy.

I was using nghttpx as a proxy to proxy client HTTP/1.1 requests to HTTP/2 upstream.

The problem seems to be specific to the HTTP/1.1 client connection handler.

Could we make nghttpx terminate an (HTTP/2) upstream request when the client request has been aborted (from an HTTP/1.1 incoming connection)?

As always, many thanks!

**Comment by tatsuhiro-t** [comment]
I did test with following configuration, but I saw that nghttpx sends RST_STREAM to backend HTTP/2 server immediately when it sees client drop connection:

```
# backend
$ nghttpd 3001 --no-tls -v
# frontend
$ nghttpx -b127.0.0.1,3001 -LINFO --backend-no-tls --client
# client; get 1GiB file
$ curl http://localhost:3000/1g
# and I hit ctrl-c to stop curl
```

**Comment by devlearner** [comment]
Thanks for the prompt response. 
I'm actually quite new to HTTP/2 (and programming in general), but that's how I tested it:

```
# Sorry that this setup seems a bit convoluted, apparantly I'm a novice
# backend (I used socat to redirect to stdout  - didn't know of a way to halt server response)
$ socat TCP4-LISTEN:333,bind=127.0.0.1 -
# nghttpx server (reverse proxy to backend - HTTP/2 -> HTTP/1.1)
$ nghttpx -f 127.0.0.1,111 -b 127.0.0.1,333 --backend-no-tls --frontend-no-tls -L INFO

# nghttpx client proxy (which proxies HTTP/1.1 to HTTP/2)
$ nghttpx -f 127.0.0.1,222 -b 127.0.0.1,111 -L INFO --backend-no-tls --frontend-no-tls --client
# the client (simulated by socat taking stdin input)
$ socat - TCP4:127.0.0.1:222
```

I then simulated a client request by typing in the following lines at the client socat console:
```
$ GET /1g HTTP/1.1 (press Enter)
$ Host: localhost (press Enter)
$ (press Enter)
$
```
On the other side at the server, I saw that the request was received at the backend socat:
```
$ GET /1g HTTP/1.1 
$ Host: localhost
$ X-Forwarded-Proto: http
$ Via: 1.1 nghttpx, 2.0 nghttpx
$
$
```
It now halts for user input (simulating a server suspending response).
If I now hit Ctrl-C at the client socat (simulating a client drop connection), I expected the backend socat will quit as well (that the request to the upstream server is being closed when client dies), instead the backend socat stays open waiting for input.

This setup is pretty bad since it also uses nghttpx as a reverse proxy on the backend (basically because I didn't know of a way to suspend server response). But if I try it with nghttp at the frontend (simulating an HTTP/2 client):

```
# we keep the server setup
$ socat TCP4-LISTEN:333,bind=127.0.0.1 -
$ nghttpx -f 127.0.0.1,111 -b 127.0.0.1,333 --backend-no-tls --frontend-no-tls -L INFO

# instead of an HTTP/1.1 client (proxied through nghttpx client proxy to HTTP/2)
# we test a direct HTTP/2 client connection using nghttp
$ nghttp -v -n http://127.0.0.1:333/1g

# the backend socat receives a request similar to the above
# when I hit Ctrl-C to stop nghttp, the backend socat quits as expected (meaning the pending request is also cancelled upstream)
```

(Without the fork option, socat behaves like a one-shot relay and thus it quits at the end of the single connection it listens to.)

So it seems (to me) that nghttpx is not terminating the pending request upstream when the (HTTP/1) client drops connection. Is it the case? Do I miss something?

Sorry that this seems an overly-complicated setup. Can a similar behaviour been observed?
Thanks very much indeed.

**Comment by devlearner** [comment]
Oh, just ignore my previous lengthy post, Tatsuhiro   : )
For clarity's sake: I think the major difference between the two test setups is that,
* (in your setup) the client aborts the connection during an active read/write session (while the server is sending a response) [which I think nghttpx is handling fine ]; and

* the client aborts the connection after a full request is sent (to the nghttpx proxy) but before the server returns its first byte to the client 
(the period when the client is waiting for a server reply within the timeout period)
  - that happens - say, when an impatient user hits refresh while loading a page and the (HTTP/1) browser aborts the request and re-sends another one

In the latter case, it seems that nghttpx (in client / client proxy mode) does not notice that the client has dropped connection to itself  (while the client is waiting for a reply after a full request is sent); and thus nghttpx won't close the pending request to the upstream accordingly.  
Does this behaviour exhibits? Any clues about this behaviour?

**Comment by tatsuhiro-t** [comment]
Your observation is correct.  nghttpx HTTPS frontend stops reading while waiting for response from backend server.  We do this to avoid reading next pipelined requests which client may send speculatively.  I have an idea to improve this situation.

**Comment by devlearner** [comment]
Thanks Tatsuhiro for the quick fix! I checked out the latest master and the issue seems to be gone. 
The latest commits are just beautiful!
Thanks for your help and the great work! Do have a nice day and weekend : )

**Comment by tatsuhiro-t** [comment]
Thanks.  Let's close this issue.

**Comment by devlearner** [comment]
Hi tatsuhiro

Sorry to comment on an old thread
it's embarrassing to ask, but i'm stuck with a spdy server in one use-case
i thought i'll just upgrade from shrpx to nghttpx, since it supports h2, h1 and spdy
but just discovered that proxying http/1.1 requests to a spdy backend isn't currently supported
[which is understandable --- given that http/2 is going to obsolete spdy soon ;-)  ]
but for now i'll still have to live with that spdy backend ;-)

i was thinking, meanwhile before that great migration takes place,
would it be possible to sort-of 'back-port' this change back to shrpx ;-)
[it'll probably be sort-of a big personal favour to ask (so i didn't open a new ticket in spdylay)
but it'll be nice if shrpx could also receive a similar patch at least for the time being ;-)
(the two related commits in nghttpx would probably be  [011e3b3] (https://github.com/tatsuhiro-t/nghttp2/commit/011e3b325da8c1fa4e02e4d802bd57acdfe32f55)   [442572c] (https://github.com/tatsuhiro-t/nghttp2/commit/442572c1f45104da5650f842bffb1bd597007e9b)    )

Anyway, thank you for developing both projects `nghttp2` and `spdylay`
which helps in making our web browsing today simply a nicer experience !

**Comment by tatsuhiro-t** [comment]
shrpx and nghttpx differs in various way for now and I'm not sure just applying patch fixes shrpx.
As you said, HTTP/2 is going to take over spdy and I plan to support spdylay for the time being, but applications like shrpx are in low priority now.

**Comment by devlearner** [comment]
i see ;-) 
that's okay, thanks for your reply!
