### ISSUE TITLE
nghttpd does not honor return value of HttpServer.run

### ISSUE THREAD

**Issue by m6w6** [tatsuhiro-t/nghttp2#157]
https://github.com/tatsuhiro-t/nghttp2/blob/master/src/nghttpd.cc#L301

Though HttpServer.run() may fail (e.g. could not listen), nghttpd exits with 0 instead of f.e. -1.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting bug.  This issue was fixed in 6f4f252907094edc7aac32a4e3a5259a36441999
