### ISSUE TITLE
libnghttp2 Client API for Android

### ISSUE THREAD

**Issue by Adouni** [tatsuhiro-t/nghttp2#159]
I am looking to use nghttp2 client to receive push from server that implements stream push with nghttp2. I take note that you are thinking to do a libnghttp2_asio Client API.
 Is there to this date a nghttp2 client API version for Android or mobile device? I have already taken a look to OKHTTP library but there is no implementations on client side to get push stream from server.

**Comment by tatsuhiro-t** [comment]
The client API is planned, but we don't have exact schedule yet.

**Comment by tatsuhiro-t** [comment]
We've implemented client API in libnghttp2_asio: https://nghttp2.org/documentation/libnghttp2_asio.html#client-api
But still I have no experience with boost on Android.

**Comment by tatsuhiro-t** [comment]
We have no plan to directly support android at the moment.  Closing.
