### ISSUE TITLE
Connection check issue

### ISSUE THREAD

**Issue by devlearner** [tatsuhiro-t/nghttp2#160]
Hi Tatsuhiro, 

First of all, thanks for the 0.7.4 release.

Sorry that I open another issue again shortly following my previous one; 
but I shall really say it's not really an issue, rather an observation maybe (though it's not related to my previous issue).

I actually put my test setup at some length -- sorry for the wordiness.
[Github does not allow me to upload other than image files (gosh), so I'll be forced to host it on Google Drive --- it's a standalone html file exported from my word-processing software 
(which apparantly doesn't do excellent HTML markup; but anyway)]
https://www.googledrive.com/host/0BxAqXY_rV9MMcl9zTGxvRGhmdlE

I'll try to summarize my observation here for bevity:
- Consider that a h1 client connects to a h2 backend thru an nghttpx proxy (client mode / HTTPS frontend)
- The client issues a request, and waits for the backend to reply
- An internal 5-sec timeout triggered a connection check in the nghttpx proxy
(log prompts `connection check required`)
- For some reason nghttpx seems to reissue the pending request (to the upstream queue) -- which the request apparantly is already in flight
- The backend sends back a reply to the nghttpx proxy; somehow nghttpx seems to think that this is an invalid reply to an already-closed stream; the reply gets nowhere but discarded.
- The nghttpx proxy moves on to process the next pending request in the upstream queue -- which would be the 're-issue' spawned during the 'connection check'
- Effectively, the backend receives another instance of the same request which it has just answered
- (Thankfully the backend deploys some cache, not a computation-heavy request, low enough rtt)
the backend manages to make a reply (before another 'connection check' is triggered at nghttpx)
- This time nghttpx successfully recognizes this as the reply it wants, and relays it back to the client
- Finally the client got something back (for a request which the backend has in fact answered twice)

Well, in fact -- despite my wordiness -- this doesn't really appear to be a huge issue I think --- considering that no one posted about this before me --- anyway, I'll just post it here as food for thought.

N.B. I digged thru the commits, and seem to find this very relevant commit back in Dec 9, 2014: dce20c3e6a470471fa0dde272dcc83e102a9a694 when the connection check feature was (first) introduced and made its debut in 0.7.0 release. Thanks to the commit comments, I seem to understand more how the connection check mechanism works; but just wondering why it doesn't seem to be working as expected in my test case.

(Thanks for reading; and) Any inputs appreciated!

**Comment by tatsuhiro-t** [comment]
Thank you for awesome debugging information.  I can see clearly that there are problems in nghttpx code.  I'll fix this problem.

**Comment by tatsuhiro-t** [comment]
d45f5a51e4e6d57e255e63e86ab44a7e6fa231b0 will fix this issue.  It looks like many things was broken regarding resubmitting request after HTTP/2 backend connection was lost abruptly.  Now it should work fine.

**Comment by tatsuhiro-t** [comment]
Oops, the d45f5a5 fixes this particular problem, but introduces another.  It was reverted now.  Will commit proper fix soon.

**Comment by tatsuhiro-t** [comment]
Fix committed via d1a1e882bf89f302652c37341365504ebc5559f7
This should fix this issue.

**Comment by devlearner** [comment]
Thanks for the quick commit! Tatsuhiro
Really impressed and thankful for the quick responses here on the issues tab.
But just as a favour, as a beginner in HTTP/2 and a novice in programming,
could you explain a little bit more how this was fixed; or in general, how the connection check mechanism is supposed to work (so that I could learn more from the impressive commits you've made)
[For now, (as a novice), I still feel like more approachable to read comments than codes :)
It's okay if it's just a line or two as a short note, just wanna learn more so that I could improve myself]
Thanks a lot!

**Comment by tatsuhiro-t** [comment]
Connection check was introduced because on some situation (mostly on mobile, where network is unstable), nghttpx HTTP/2 backend connection is lost but there is no notification to nghttpx process and we don't know it is alive or not without actually read or write something to the connection.
We have no good way to recover once we send request to the wire, so instead of actually sending request, we stop sending request temporarily (Downstream::request_pending_ = true), and write PING frame to the connection.  If we can successfully send PING frame, we assume connection is OK and submits pending requests.  The bug was that when we see the connection is OK, we wrongly re-send request because the condition to select which request should be re-send is insufficient.  The fix we made is introduce new variable Downstream::request_pending_ to explicitly mark the request as pending.

**Comment by devlearner** [comment]
Oh I see, thanks very much for the detailed explanation!
Confirmed that issue's gone with the fix. Closing this issue for now.
Thanks very much indeed, Tatsuhiro!
