### ISSUE TITLE
Can't connect to server in the examples.

### ISSUE THREAD

**Issue by informer2000** [tatsuhiro-t/nghttp2#162]
I have launched a server process using the `asio-sv.cc` example. I can see that the server is listening to the port I specified (8080) using netstat, on both IPv4 and IPv6 addresses. But whenever I attempt to connect to it using the Web browser (using http://127.0.0.1:8080), I don't get any reply. It just keeps saying waiting for reply and eventually gives me a no data received error page.

Is there something I'm missing?

**Comment by tatsuhiro-t** [comment]
Which web browser did you use?  As far as I know, both Firefox and Chrome only implement HTTP/2 over TLS.  You need to launch asio-sv with private key and certificate and access it to using https URI.
```
$ examples/asio-sv 8080 1 tests/testdata/privkey.pem tests/testdata/cacert.pem
```

FYI, CLI tools like nghttp client or curl support HTTP/2 in cleartext (without TLS).

**Comment by informer2000** [comment]
Thanks! That was it. I was using Chromium and FireFox. 

Most likely the Chromium version I was using does not support HTTP/2. But using (https://127.0.0.1:8080) with FireFox worked! I will check curl and the nghttp client.

**Comment by tatsuhiro-t** [comment]
For chrome, you need to open chrome://flags and enable spdy/4

**Comment by informer2000** [comment]
Perfect! It works now. Thanks @tatsuhiro-t ..
