### ISSUE TITLE
0.7.5 breaks h2c upgrade

### ISSUE THREAD

**Issue by icing** [tatsuhiro-t/nghttp2#168]
Hi,

while tightening checks in initial SETTINGS exchange, the additional check in nghttp2_session.c, line 4836, breaks the h2c upgrade. I think the problem is that the intial SETTINGS was already in the header of the HTTP/1 request triggering the upgrade. So the first SETTINGS frame that nghttp2_session really sees is an ACK to its own.

Either this check is too much, or one needs a check that the session is not on the server side of a nghttp2 upgrade, I think.

Thanks for the great work!

**Comment by tatsuhiro-t** [comment]
nghttp2 is correct.  HTTP/2 spec requires SETTINGS frame without ACK must be sent even if it is already sent in HTTP2-Settings header field.

**Comment by icing** [comment]
I agree. I will find out tomorrow what breaks my code from 0.7.4 to 0.7.5 and let you know.

**Comment by icing** [comment]
Ok, clarified the issue. My server code broke as nghttp now sends the CONNECTION_PREFACE - which it should according to spec - but did not do in 0.7.4 and before, it seems. With explicitly calling
```  nghttp2_option_set_recv_client_preface(options, 1);```
my server works with nghttp.

Since receiving connection preface is now required by h2 and h2c, it would be less confusing if that is the default behaviour of nghttp2 server session. Just an idea.

**Comment by tatsuhiro-t** [comment]
As far as I know, nghttp client sends CONNECTION_PREFACE in 0.7.4 and earlier version.
Anyway, grad to hear the problem was solved.

As for nghttp2_option_set_recv_client_preface(), I agree with you, the behaviour should be default.
We plans API breaking change upon 1.0.0 release and I'd like to do this change.
