### ISSUE TITLE
nghttp2_option_set_recv_client_preface() should be default

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#171]
Since HTTP/2 spec requires for client to send connection preface, it is reasonable to make this option enabled by default.
It is still a use case to disable this, so replace this option with `nghttp2_option_set_no_recv_client_preface() `.

**Comment by matsumoto-r** [comment]
:+1:

**Comment by tatsuhiro-t** [comment]
I decided to rename `nghttp2_option_set_no_recv_client_preface()` as `nghttp2_option_set_no_recv_client_magic()`, since what we are processing is not entire client connection preface, just part of it (MAGIC).
