### ISSUE TITLE
nghttp2 build fail on ARM

### ISSUE THREAD

**Issue by alagoutte** [tatsuhiro-t/nghttp2#172]
I have a ARM build ( http://labs.online.net/ ) and nghttp2 no longer build :-(

I have the following error message :

nghttp2_session.c: In function 'nghttp2_session_get_stream':
nghttp2_session.c:209:12: error: cast increases required alignment of target type [-Werror=cast-align]
   stream = (nghttp2_stream *)nghttp2_map_find(&session->streams, stream_id);
            ^
nghttp2_session.c: In function 'nghttp2_session_get_stream_raw':
nghttp2_session.c:221:10: error: cast increases required alignment of target type [-Werror=cast-align]
   return (nghttp2_stream *)nghttp2_map_find(&session->streams, stream_id);
          ^
nghttp2_session.c: In function 'free_streams':
nghttp2_session.c:544:12: error: cast increases required alignment of target type [-Werror=cast-align]
   stream = (nghttp2_stream *)entry;
            ^
nghttp2_session.c: In function 'find_stream_on_goaway_func':
nghttp2_session.c:2182:12: error: cast increases required alignment of target type [-Werror=cast-align]
   stream = (nghttp2_stream *)entry;
            ^
nghttp2_session.c: In function 'update_remote_initial_window_size_func':
nghttp2_session.c:3731:12: error: cast increases required alignment of target type [-Werror=cast-align]
   stream = (nghttp2_stream *)entry;
            ^
nghttp2_session.c: In function 'update_local_initial_window_size_func':
nghttp2_session.c:3784:12: error: cast increases required alignment of target type [-Werror=cast-align]
   stream = (nghttp2_stream *)entry;

After a quick bisect, i have found the commit with the problem :

commit b157d4ebb23a9c056b83fdb81393495bb13a54d4
Author: Tatsuhiro Tsujikawa <tatsuhiro.t@gmail.com>
Date:   Fri Feb 20 00:01:15 2015 +0900

    Validate HTTP semantics by default

    Previously we did not check HTTP semantics and it is left out for
    application.  Although checking is relatively easy, but they are
    scattered and error prone.  We have implemented these checks in our
    applications and also feel they are tedious.  To make application
    development a bit easier, this commit adds basic HTTP semantics
    validation to library code.
[...]

**Comment by tatsuhiro-t** [comment]
OK, I found the cause.  The commit introduced 64bit integer field to nghttp2_stream.  On the other hand, on 32 bit OS, nghttp2_map_entry only contain at most 4 byte field (pointer type), so there is alignment mismatch.

**Comment by alagoutte** [comment]
Thanks, work for me too :)
