### ISSUE TITLE
Feature Request: OCSP stapling

### ISSUE THREAD

**Issue by vadave** [tatsuhiro-t/nghttp2#180]
I'd love to see (optional) support for OCSP stapling added to nghttpx and nghttpd. OCSP stapling is described by RFC 4366 (http://tools.ietf.org/html/rfc4366) and provides an architecturally elegant method of verifying that a server certificate has not been revoked. 

While it's the case that most current browsers don't (by default) check revocation for server certificates, there are some indications that website security configurations may become a factor in reputation scores generated by search engines, and therefore become increasingly important to website administrators.

**Comment by tatsuhiro-t** [comment]
Probably we can borrow @kazuho 's fetch script https://github.com/h2o/h2o/blob/master/share/h2o/fetch-ocsp-response for h2o and just sends the result to the client.
OpenSSL seems to have set of API to query OCSP to server but they are not documented.

**Comment by kazuho** [comment]
@tatsuhiro-t Yeah!  I do not see any reason to have different implementation in each httpd.  Please let me know if you want me to move the script into a separate repository so that you can submodule / subtree it.

**Comment by tatsuhiro-t** [comment]
Thank you.  Currently, the perl script is only one file, so we can just copy and add to our repo.
BTW, we should rename script for our own prefix, since they may conflict each other if someone installs both h2o and nghttp2.

**Comment by kazuho** [comment]
@tatsuhiro-t Thank you for the response.

> Thank you. Currently, the perl script is only one file, so we can just copy and add to our repo.

Got it.  I thought it might be better to keep the code at one place and share the improvements, since the script needs to take care of various CAs (the response seem to differ from one another) and the environment on which the script is being executed, and I expect that such changes would be necessary in the future as well.  But I do not think starting it the easy way (by just copying the code) is a bad idea as we can always merge the implementation afterwards.

> BTW, we should rename script for our own prefix, since they may conflict each other if someone installs both h2o and nghttp2.

In case of H2O the script is considered internal, and is installed under `$PREFIX/share/h2o` so there is no such issue.

**Comment by tatsuhiro-t** [comment]
> In case of H2O the script is considered internal, and is installed under $PREFIX/share/h2o so there is no such issue.

Very good.  We'll follow that convention.

**Comment by tatsuhiro-t** [comment]
As of commit 4bc9afe20a8565d03c83cb3272a002192fd384d3, nghttpx supports OCSP stapling using h2o's fetch-ocsp-response script.
https://nghttp2.org/ now enables OCSP stapling.

**Comment by tatsuhiro-t** [comment]
nghttpx supports SNI and multiple certificates.  Our implementation checks all certificates.  Currently, it invokes script per 1 certificate.  I don't know how many those certificates are used in practice.  If they are plenty, then it causes a bit more server load.  But the updates are done once per 4hrs by default, so not much a pain.

**Comment by tatsuhiro-t** [comment]
For now, we have no plan to add OCSP stapling to nghttpd.  We'd like to keep nghttpd simple.
