### ISSUE TITLE
Timigs and latency http/2 vs tls

### ISSUE THREAD

**Issue by brk0v** [tatsuhiro-t/nghttp2#182]
Hi, 

I'm a little confused about multiplexing over tcp in http/2 and timings. 

I have a simple html page with 2 images:

```html
<html>
  <head><title>http2 test</title></head>
  <body>
   <img src="1.jpg" />
   <img src="2.jpg" />
  </body>
</html>
```

While I'm serving it using nginx – I get following timings (with disabled browser cache and after TLS handshake):

![](http://habrastorage.org/files/5ba/9ae/8b0/5ba9ae8b069749208c1a98e392ea71b4.png)

In total: **240ms**.

In ```netstat``` we can see that FireFox opened 2 connections:
```
root@vagrant-ubuntu-trusty-64:~# netstat -ntp | grep 8443
tcp        0      0 192.168.32.10:8443      192.168.32.1:55232      ESTABLISHED 9206/nginx: worker
tcp        0      0 192.168.32.10:8443      192.168.32.1:55233      ESTABLISHED 9206/nginx: worker
```

And while serving nghttp2d:

![](http://habrastorage.org/files/2ff/786/1d1/2ff7861d1220475ea391a22cb9265d98.png)

In total: **310ms**.

nghttp2d start line:
```
sudo ./nghttpd  -d /var/www/  443  ./server.key ./server.crt
```

And one socket:
```
vagrant@vagrant-ubuntu-trusty-64:~/nghttp2/src$ sudo netstat -ntp | grep 443
tcp        0      0 192.168.32.100:443      192.168.32.1:55325      ESTABLISHED 12574/lt-nghttpd
```

Nginx's TLS config:
```
    ssl_protocols TLSv1.2;
    ssl_ciphers kEECDH+AES128:kEECDH:kEDH:-3DES:kEDH+3DES:kRSA+AES128:DES-CBC3-SHA:!RC4:!aNULL:!eNULL:!MD5:!EXPORT:!LOW:!SEED:!CAMELLIA:!IDEA:!PSK:!SRP:!SSLv2;
    ssl_session_cache    shared:SSL:64m;
    ssl_session_timeout  12h;
```

**So the question is why we loose so much time? I think that multiplexing should fix it.**

P.S. I've emulated latency using ```iproute2``` and ```tc```:
```
sudo tc qdisc add dev eth1 root netem delay 100ms
```

**Comment by methane** [comment]
I suppose default TCP investigation windows size is 10KB~15KB.
Since one image file fits in initial window size, server can send whole image in one round trip.
But when multiplexing, server should wait receiving ACK while sending second image.

**Comment by brk0v** [comment]
Images sizes:
```
$ ls -lh *.jpg
-rw-r--r-- 1 vagrant vagrant 9.2K Mar 13 21:10 1.jpg
-rw-r--r-- 1 vagrant vagrant 9.2K Mar 13 21:10 2.jpg
```

Defautl network setting:
```
MTU: 1500
initcwnd: 10
```

So you're right, tcp congestion control should wait for ACK after 15KB data. If I increase initcwnd:
```
ip route change 192.168.32.0/24 dev eth1 proto static initcwnd 25
```

I've got expected timings:

![](http://habrastorage.org/files/b7f/785/7a9/b7f7857a96004190add21762188d44a7.png)

It's interesting and became more tcp congection control depended with http/2. Maybe we should change default congection control algorithm for better performance and fast window grow?

**Comment by tatsuhiro-t** [comment]
Nice catch, @methane for initcwnd.
I think typical web pages contains more resources/images, and then it makes a difference.
Try something more real example, say, http://http2rulez.com/, its source can be cloned from https://github.com/ipeychev/http2rulez.com

**Comment by brk0v** [comment]
Thank you for answers. 

But I've got the same results with page: ```https://http2rulez.com/web-components.html``` vs ```https://http2rulez.com:8081/web-components.html```. HTTPS version is faster than HTTP/2 (2.4s vs 3.2s) I think it is because of opening multiple (6) tcp connections on the page.

Changing tcp recieve window from my client FF on mac os x looks following.

For **http/2**

![](http://habrastorage.org/files/6c9/5d2/ead/6c95d2ead6f64315973b1c7fa21c4672.png)

For **https** for one of 6 connections (they're the same):

![](http://habrastorage.org/files/bbc/72d/f9b/bbc72df9b5ff4b87ba5065c8e5d4a968.png)

What am I doing wrong?

**Comment by brk0v** [comment]
I guess I've found the answer. It is slow start after idle. You really should turn it of on the server side with http/2.

```
sysctl -w net.ipv4.tcp_slow_start_after_idle=0
```

And  now look at ```cwnd``` using this command:

```
ss -n  --processes --options --info | grep  -A 1 lt-nghttpd
```

We can see our ```cwnd``` and  ```ssthresh```:

In my case:

```
# ss -n  --processes --options --info | grep  -A 1 lt-nghttpd
tcp    ESTAB      0      0         192.168.32.100:443        192.168.32.1:52096  users:(("lt-nghttpd",16117,7))
         ts sack cubic wscale:5,6 rto:312 rtt:107/3 ato:40 mss:1448 cwnd:262 ssthresh:219 send 28.4Mbps rcv_rtt:319776 rcv_space:29102
```
