### ISSUE TITLE
nghttpx proxy forwarding requests via 1 IP address only

### ISSUE THREAD

**Issue by nergoza** [tatsuhiro-t/nghttp2#190]
Hi,

I have a server with 5 sub IP's the primary interface.
This is the command I use for nghttpx:
nghttpx -LWARN -LERROR  --npn-list=spdy/3 --http2-bridge -k -f*,8080 -bperf-test.http-nostore1.spdy.SSL.gxi.com,443 -bperf-test.http-nostore2.spdy.SSL.gxi.com,443 -b perf-test.http-nostore3.spdy.SSL.gxi.com,443 -b perf-test.http-nostore4.spdy.SSL.gxi.com,443 -b perf-test.http-nostore5.spdy.SSL.gxi.com,443 localhost.key localhost.crt

The clients are sending the requests to all 5 IP's and I can see them via tcpdump.
But on the backend server I can see that all the requests are coming from the primary IP of the nghttpx server.

Is there a way to tell the nghttpx to send the requests from the same IP he received the requests?

Thans

**Comment by tatsuhiro-t** [comment]
There is no option to choose interface.

FYI, nghttpx by default uses 1 HTTP/2 backend connection per worker.
To use multiple connections per worker, use --backend-http2-connections-per-worker

**Comment by nergoza** [comment]
I see.
Another question mate,
I want to use from my clients a better cipher for performance, like AES-256.

Can I use it with the proxy?
I mean my clients will be SPDY enabled but with AES-256, the proxy will accept it?
Also, it will forward to the backend server using same ciphers ?

Thanks

**Comment by tatsuhiro-t** [comment]
The default cipher list nghttpx supports:
https://github.com/tatsuhiro-t/nghttp2/blob/faa2c4467a1553912d77fc58dc62dee2c7d144d8/src/ssl.cc#L42-L50

You can change specific ciphers using --ciphers option.

Cipher negotiation is done hop by hop, so there is no relationship between frontend and backend connections.

**Comment by nergoza** [comment]
Oh I see.
Mate, I'm changing the number of workers in the proxy and on high numbers (from 50 and above) my clients reporsts on packet drops..

I don't know why since the proxy is not overloaded..
What could be the cause of it?

**Comment by tatsuhiro-t** [comment]
The number of workers should be equal to the number of CPU cores. Too many workers just degrades performance.
I have no idea about packet drops.  Probably system is not tuned for performance testing or client is misbehaving?

**Comment by tatsuhiro-t** [comment]
This is old thread, I'm not sure how to proceed from here.
Please reopen this issue if you still have this issue.
