### ISSUE TITLE
Build uses headers from older version of nghttp2, if installed

### ISSUE THREAD

**Issue by UnitedMarsupials** [tatsuhiro-t/nghttp2#192]
Trying to build 0.7.7 on FreeBSD, where 0.7.5 is currently installed. Configure's summary says:

     Version:        0.7.7 shared 12:0:7
     Host type:      i386-portbld-freebsd10.1
     Install prefix: /opt
     C compiler:     cc
     CFLAGS:         -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing
     WARNCFLAGS:     
     LDFLAGS:         -Wl,-rpath,/usr/lib:/opt/lib -fstack-protector
     LIBS:           -L/opt/lib -lev
     CPPFLAGS:       -I/opt/include
     C preprocessor: cpp
     C++ compiler:   c++
     CXXFLAGS:       -O2 -pipe -march=core2  -fstack-protector -fno-strict-aliasing  -std=c++11
     CXXCPP:         c++ -E
     Library types:  Shared=yes, Static=yes

The build fails with:

    asio-sv.cc:118:39: error: use of undeclared identifier 'NGHTTP2_DATA_FLAG_NO_END_STREAM'; did you mean 'NGHTTP2_FLAG_END_STREAM'?
              NGHTTP2_DATA_FLAG_EOF | NGHTTP2_DATA_FLAG_NO_END_STREAM;
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                      NGHTTP2_FLAG_END_STREAM
    /opt/include/nghttp2/nghttp2.h:505:3: note: 'NGHTTP2_FLAG_END_STREAM' declared here
      NGHTTP2_FLAG_END_STREAM = 0x01,
      ^

Although `-I/opt/include` is needed for the package to be able to find other packages' headers, the build should always place the directory with nghttp2's current headers _first_.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.  I believe c2510a0 fixes this issue.
