### ISSUE TITLE
Expose dependency priority information to application

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#193]
Currently, nghttp2 does not expose dependency priority information to application.
Event-based application probably does not require them, but thread based application may need priority information to allocate high priority request to thread which could be far less than the number of concurrent requests.

**Comment by tatsuhiro-t** [comment]
Some ideas:

idea 1:  Make dependency tree available to public API, application can get stream object by stream ID.  It can then traverse dependency tree.

This gives a lot of freedom to application, because now it can freely check the dependency status.

idea 2: Assuming application wants to pick next stream to process among the streams waiting in queue, if those streams are passed to nghttp2 library, it looks up the dependency tree, and returns the weight of each streams.  If a stream is descendant of the another stream in the parameter list, then it is considered as blocked, and special value (0 or -1) weight is returned to indicate this.
The application can implement this using idea 1.  Idea 2 is just straight forward way to use this feature.

@icing what do you think about them?  Can  these idea be applied to mod_h2?

**Comment by icing** [comment]
Tatsuhiro,

thanks for the proposals! This is indeed on my list of things. I think making it public would work nicely, so 1. I am not sure when mod_h2 would evaluate it, either at stream open or when dispatching the next task. So I'd like the flexibity of accessing it directly. 

I am on vacation next two weeks (I know - crazy germans!) so I might be slow on response. 

cheers,
  Stefan

**Comment by tatsuhiro-t** [comment]
Thank you for quick feedback!  Our proxy server has the same situation when backend connection is limited to very low, so I'll do some experiments with the idea 1, to make sure it works.
Probably, cut new branch for experiments.

**Comment by tatsuhiro-t** [comment]
I just added API to get complete dependency tree.  See 059280d
