### ISSUE TITLE
Malformed headers in PUSH_PROMISE

### ISSUE THREAD

**Issue by devlearner** [tatsuhiro-t/nghttp2#194]
Hi Tatsuhiro,

Recently played with http/2 server push in nghttpx, and seems to come across some malformed headers in PUSH_PROMISE, specifically :scheme and :authority.

I used nghttp to issue a http/2 request, and used nghttpx as reverse proxy in default mode.
Interestingly, I also tried nghttp with nghttp2.org which also seems to be running nghttpx and it returned the pushed css fine.

I've attached the logs here:
https://www.googledrive.com/host/0BxAqXY_rV9MMVS1ncFVSaUdDeWM/PUSH_PROMISE-messed-up-headers.htm

Any clues of something that I missed?

**Comment by tatsuhiro-t** [comment]
I think the above commit fixes the problem.
The reason why nghttp2.org is ok is just a luck.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug!

**Comment by devlearner** [comment]
Thanks, Tatsuhiro!

**Comment by devlearner** [comment]
Ah, sorry that I forgot to mention this in my previous post:

During my testing and playing around a bit with server push, I happened to notice that ---

consider the following response:
```
HTTP/1.1 200 OK <CRLF>
Transfer-encoding: chunked <CRLF>
Trailer: Link <CRLF>
<CRLF>
3<CRLF>
abc<CRLF>
0<CRLF>
Link: </css/theme.css>; rel=preload<CRLF>
<CRLF>
```

if the `Link:` header appears in the trailers, the header is passed as is to the client without any server push. shall we also intercept this in the trailers for server push?
[i think most implementatons won't do this in this in the trailers; but just raising this as a possibility :) ]

ah... and thanks for the 0.7.9 release!

**Comment by tatsuhiro-t** [comment]
It is is interesting.  My observation is that PUSH_PROMISE is usually done before response body or even response headers so that it can reach to client before client sees link to pushed content.
In that context, link header fields in trailer fields are a bit too late.

**Comment by devlearner** [comment]
Ya, you're right... at second thought my question was a bit silly :)
Thanks for your answer!
