### ISSUE TITLE
License is not an officially recognized OSI license

### ISSUE THREAD

**Issue by jimjag** [tatsuhiro-t/nghttp2#200]
The original license was the simple, and OSI approved, MIT License. However, the addition of the libcurl sections resulted in a new License, the complete of which is NOT an approved or recognized OSI or FSF license. This *significantly* impacts usage by other Open Source projects which would like to leverage nghttp2, such as Apache and Eclipse.

I would strongly encourage reverting back to the original MIT license or the BSD or even Apache License v2. These are officially approved OSI licenses.

**Comment by bagder** [comment]
Only if you consider the second half part of the text as still a part of the license, which to me seems strange as that part talks about how to contribute to the project.

Of course, that issue can be avoided by splitting out the contributing text to another file.

**Comment by jimjag** [comment]
One thing that scares people using open source is questions around licensing :)

Any time you modify a license from the canonically accepted and approved OSI version, there will be concerns and those concerns significantly restrict adoption.

**Comment by tatsuhiro-t** [comment]
Our license is still MIT and we have never intended to invent new one. I'll split COPYING file to resolve this issue.

**Comment by tatsuhiro-t** [comment]
See 0c8ec7b.
@jimjag Does that look good?

**Comment by jimjag** [comment]
Perfect! THX!!! :)

Expect some pull requests over the next few weeks ;)

**Comment by tatsuhiro-t** [comment]
Thank you!
