### ISSUE TITLE
Does nghttpx support preserve host in default mode?

### ISSUE THREAD

**Issue by oyvindhorneland** [tatsuhiro-t/nghttp2#208]
Hi,

I'm testing nghttpx in default mode in front of an Apache HTTP server. Does nghttpx support preserving the original host line like apache with ProxyPreserveHost On or is it only passed as X-Forwarded request headers?

http://httpd.apache.org/docs/2.4/mod/mod_proxy.html#proxypreservehost

So far It's only sending the backend name:port as host.

Regards,
Øyvind

**Comment by oyvindhorneland** [comment]
Ah, never mind. no-host-rewrite did the trick. Apparently I missed that configuration option.. :)

**Comment by tatsuhiro-t** [comment]
nghttpx initially preserved hostname but we changed the code so that hostname is rewritten using backend host since major web servers do this by default.  I saw someone also asked this before, and I am wondering which should be a default behavior.

**Comment by oyvindhorneland** [comment]
I haven't seen any explanation as to why Apache has ProxyPreserveHost set to Off by default. When used as a reverse proxy a backend application will probably most of the times want to see which site the end client tried to access and not it's own backend name/ip. So I fail to see why this is not enabled by default as long as there is no performance penalty associated with it.

If, however, there is a slight performance penalty involved, then it should probably be Off by default as many web applications will not care one way or the other which hostname was originally used (and therefore does not care about this setting - only performance).

**Comment by tatsuhiro-t** [comment]
Thanks for the reply.
As for performance, our nghttpx implementation has absolutely no difference between with or without rewriting hostname.
It seems nginx also follows apache's behaviour.
I heard that some server may strictly check the host header field with its hostname or configuration and fail the request if it does not match, so rewriting the hostname would be safe default.
