### ISSUE TITLE
Problems with libnghttp2_asio: error while loading shared libraries libnghttp2_asio.so.1

### ISSUE THREAD

**Issue by liuli9203** [tatsuhiro-t/nghttp2#209]
Hello, everyone！
    I tried to write a push demo based on the libnghttp2_asio: High level HTTP/2 C++ library. However, when I try to run the successfully compiled server, it just failed to load the shared libraries libnghttp2_asio.so.1. Can anybody give me a hand ? Thank you so much.

   This is my a_server.cpp:
--------------------------------
#include <nghttp2/asio_http2_server.h>
#include <iostream>

using namespace nghttp2::asio_http2;
using namespace nghttp2::asio_http2::server;

int main(int argc, char * argv[])
{
  boost::system::error_code ec;
  http2 server;
  
  server.handle("/",[](const request &req, const response &res)
    {
      res.write_head(200);
      res.end("hello, world\n");
    }
  );
  
  if(server.listen_and_serve(ec, "localhost", "3000"))
  {
    std::cerr<< "error:"<<ec.message() <<std::endl;
  }
}

I set the environment variable $CPLUS_INCLUDE_PATH=/home/liuli/Public/nghttp2/src/includes:/home/liuli/Public/nghttp2/lib/includes  and $LIBRARY_PATH=/home/liuli/Public/nghttp2/src/.libs/

and then, I compile the a_server.cpp with c++11:
$ g++ -std=c++11 -c a_server.cpp 

and then, I link the object with c++11:
$ g++ -std=c++11 a_server.o -o a_server -lnghttp2_asio -lboost_system  -lssl -lcrypto -lpthread

Finally, I get the executable file a_server. I run it with ./a_server, however error happens:
liuli@liuli-VM:~/Public/nghttp2/src$ ./a_server 
./a_server: error while loading shared libraries: libnghttp2_asio.so.1: cannot open shared object file: No such file or directory

I check the /home/liuli/Public/nghttp2/src/.libs/, and the link file libnghttp2_asio.so.1 exsits:
lrwxrwxrwx 1 liuli liuli       24  April 10 07:42 libnghttp2_asio.so -> libnghttp2_asio.so.1.0.0*
lrwxrwxrwx 1 liuli liuli       24  April 10 01:02 libnghttp2_asio.so.1 -> libnghttp2_asio.so.1.0.0*
-rwxrwxr-x 1 liuli liuli 12198542  April 10 01:02 libnghttp2_asio.so.1.0.0*
-rwxrwxr-x 1 liuli liuli  1959445  April 10 01:03 lt-nghttp*

I try to delete libnghttp2_asio.so and create symbolic link libnghttp2_asio.so to libnghttp2_asio.so.1, however, it does not work.

**Comment by tatsuhiro-t** [comment]
try:
```
$ LD_LIBRARY_PATH=/home/liuli/Public/nghttp2/src/.libs/:/home/liuli/Public/nghttp2/lib/.libs/ ./a_server 
```

**Comment by liuli9203** [comment]
Thank U very much! However, the environment variable $LD_LIBRARY_PATH seems to be ignored by the G++. Anyway, it works when I set  the environment variable $LIBRARY_PATH=/home/liuli/Public/nghttp2/src/.libs/:/home/liuli/Public/nghttp2/lib/.libs/.

**Comment by tatsuhiro-t** [comment]
Good.  Alternatively, you can utilize rpath directory:
```
$ ./configure LDFLAGS="-Wl,-rpath,/PATH/TO/LIB/"
```
