### ISSUE TITLE
Question: performance improvement

### ISSUE THREAD

**Issue by molinch** [tatsuhiro-t/nghttp2#212]
Do you have hints on how to improve performance when using nghttpx?
My backend server remains faster even with a high latency line.

Basically we have:
- an application server in our corporate network
- nghttpx acting as a HTTP2 reverse proxy, and only allowing NPNs h2,h2-16,h2-14
- nightly chrome with SPDY/4 enabled, nightly firefox

Currently with chrome or firefox we still have better performance using the application server directly.
Could you help us?

**Comment by tatsuhiro-t** [comment]
We should share the meaning of "performance"  here.  We have many metrics for web performance.  Do you have any numbers or some screenshot of low performance (e.g., browser's dev-tool network view or http://www.webpagetest.org/)?

If you enable INFO level logging, it could affect performance since it produces a lot of logging.

**Comment by molinch** [comment]
I was using the default logging level, ie: NOTICE. Changing it to ERROR level improves performance.
But still there is a big performance penalty when reverse proxy is used.

Attached I have 2 screens one with direct access to server (it takes 15.43 seconds for one file) and one using reverse proxy (it takes seconds for the same file)
![image](https://cloud.githubusercontent.com/assets/5130190/7252793/4d58d5f0-e838-11e4-9408-7fab35974096.png)
![image](https://cloud.githubusercontent.com/assets/5130190/7252823/721044b4-e838-11e4-9d30-8ff956da53f7.png)

I am using clumsy to simulate bad network
![image](https://cloud.githubusercontent.com/assets/5130190/7252843/8602faa2-e838-11e4-977a-12d1f349644e.png)

**Comment by tatsuhiro-t** [comment]
Thanks.
I noticed that jquery_bootstrap's file size is different between 2 screenshots: 162KB vs 423KB.
Probably, compression is disabled in the latter case?
Since we have simulated higher packet loss ratio, large transfer gets more penalty than smaller one.

BTW, `--backend-http1-connections-per-host` is ignored if default mode is used.

**Comment by molinch** [comment]
Thanks for the feedback
From what I see nghttpx uncompress data from backend server and sends it to browser uncompressed.
Is it the expected behaviour?

**Comment by tatsuhiro-t** [comment]
nghttpx never uncompress anything.  It also does not strip "accept-encoding" header field from browser.
We enabled gzip compression on https://nghttp2.org/ and it works perfectly with Firefox.
Could you check that browser sends "accept-encoding" header field and also the application server gets this header and do compress files?

**Comment by molinch** [comment]
Reverse proxy
![image](https://cloud.githubusercontent.com/assets/5130190/7253520/971a3d0a-e83d-11e4-9945-6dde571c07c9.png)


Direct access
![image](https://cloud.githubusercontent.com/assets/5130190/7253532/bcf4b21c-e83d-11e4-9718-74b53303cb22.png)

**Comment by tatsuhiro-t** [comment]
Thanks.  Indeed client sends accept-encoding header field correctly.
Then I guess that some header fields sent by nghttpx to backend server may cause it not to compress files.  I found this page: http://www.iis.net/learn/troubleshoot/performance-issues/troubleshooting-iis-compression-issues-in-iis6-iis7x
It says:
> If the request contains a Via: header: The Via headers indicates that the request is coming to IIS via a Proxy. Many proxies don't handle the compression header correctly and give compressed data to clients when they aren't supposed to, so by default we don't allow compressed responses when the request has a Via header. You can override this by setting the HcNoCompressionForProxies metabase key to True.

So "via" header field is probably a cause of this issue.
We can turn it off using `--no-via` option in nghttpx or follow the instruction the above page.
Side note: via header field is mandated by HTTP specification, so I recommend not to strip it..

**Comment by molinch** [comment]
Wow the impact is HUGE. May thanks @tatsuhiro-t now it gets the file in 13seconds!

**Comment by tatsuhiro-t** [comment]
Good.  For performance/latency, you may be also interested in #182

**Comment by molinch** [comment]
Thanks I also implemented what was written there.
Now I have same level of performance for direct access or reverse proxy.
