### ISSUE TITLE
Reverse proxy with SSL Backend

### ISSUE THREAD

**Issue by molinch** [tatsuhiro-t/nghttp2#214]
Is it possible to reverse proxy to backend with SSL and HTTP1.1?

My configuration is:
<pre>/usr/local/bin/nghttpx --no-via  --backend=crmtest,443 --frontend=*,8081 --log-level=INFO --npn-list=h2,h2-16,h2-14 --dh-param-file=/etc/pki/CA/private/dhparam.pem --daemon --accesslog-file=access.log --errorlog-file=error.log --no-ocsp /etc/pki/CA/private/key.pem /etc/pki/CA/private/cert.pem</pre>
My backend is https://crmtest and I try to reverse proxy it to https://blkshttp2t01:8081

Unfortunately that does not seem to work: browser is loading for a long time and finally outputs:
<pre>502 Bad Gateway
nghttpx nghttp2/0.7.13-DEV at port 8081</pre>

**Comment by tatsuhiro-t** [comment]
Currently, not possible.
We support TLS in HTTP/2 backend only at the moment.

**Comment by molinch** [comment]
Ok thanks for the feedback @tatsuhiro-t
