### ISSUE TITLE
elaborate on nghttpd "worker threads" ?

### ISSUE THREAD

**Issue by bagder** [tatsuhiro-t/nghttp2#216]
-n, --workers sets the number of worker threads the docs says.

Is there any further docs that explains what the worker threads do or another resource that can help me decide on what a suitable number of threads would be?

I'd love to extend that man page a little once I've figured this out myself!

**Comment by tatsuhiro-t** [comment]
Thanks.  nghttpd's acceptor thread accepts the connection from client and hands it over to worker thread.
The worker thread handles the multiple connections from clients, including costly SSL/TLS handshakes.
So the ideal configuration is specify the number of cores to -n option.
-n1, which is default, makes nghttpd totally single threaded, that is acceptor and worker run in the same thread.
