### ISSUE TITLE
QUIC

### ISSUE THREAD

**Issue by huyuguang** [tatsuhiro-t/nghttp2#220]
I really like your http2_asio lib.
Do you have any plan to provide a quic client/server lib with asio?
Now the quic code in chrome is really hard to use.

**Comment by etcimon** [comment]
Isn't that a proprietary protocol? I doubt you can use it in anything without explicit permission

**Comment by huyuguang** [comment]
What I mean is, the implement of the QUIC in chromium has too many depends and hard to use.

**Comment by etcimon** [comment]
I did some more research and it seems like the Chromium code is BSD-licensed and the protocol may become standard soon. It will be interesting to see it being implemented in a library as you say. The advantages would come mostly from reducing the delay from the initial handshake of HTTP/2 + TLS roundtrips

**Comment by huyuguang** [comment]
Very thanks for your attention.
There are some useful features of the QUIC.
First is it can avoid the head-of-line blocking (which make spdy/http2 slow in mobile network connetction) and the second is it support multi-path which can let cellphones do not need to reconnect to server when the network connection changes (2g/3g/4g/wifi).

I tried to port the QUIC code from chromium to a clean, standalone, cross-platform library (just like your http2_asio) for some days and gave up. The chromium code it too large to handle for me.

**Comment by tatsuhiro-t** [comment]
I think we need to wait for standardization of QUIC, and complete specification of it.
I've not researched QUIC yet, so don't know how it is integrated into HTTP/2 or completely separate layer from it.  Probably, QUIC library itself could be a completely separate project for its own.

**Comment by bagder** [comment]
I agree with @tatsuhiro-t here. QUIC is underspecified as it is right now, and still too tied to SPDY instead of HTTP/2. Using the chrome code is really annoying (as can be seen in the libquic project). We really need it to settle down and move towards standardization, once that happens I'll gladly participate in making a quic library in nghttp2 style a reality.

**Comment by est** [comment]
I lurk QUIC discussion group, they are moving versions really fast, any thirdparty implementation may fall behind.

**Comment by alagoutte** [comment]
Like it is say on http://blog.chromium.org/2015/04/a-quic-update-on-googles-experimental.html

It is plan to switch to HTTP2 over "QUIC" (Actually SPDY over "QUIC") and also to propose QUIC @IETF (HTTP3 ? ;-) )

There is also like @bagder say, a experimental libquic (based on Chromium source code)
https://github.com/devsisters/libquic

**Comment by tatsuhiro-t** [comment]
I think if I were implement QUIC, it would become a separate another project.
