### ISSUE TITLE
(Re)construct $http_host in access log?

### ISSUE THREAD

**Issue by wzyboy** [tatsuhiro-t/nghttp2#222]
Hi,

I am using `nghttpx` as a frontend and Squid as a backend. My Google Chrome is configured to use nghttpx frontend as a HTTPS proxy. I want to analyse my web requests.

When using `--accesslog-format "$http_host $request"` and visiting a few web pages, my nghttpx access log file looks like this:

    "- GET /foo.html HTTP/1.1"
    "- GET /bar.html HTTP/1.1"
    "mtalk.google.com:5228 CONNECT mtalk.google.com:5228 HTTP/1.1"
    "- GET /wow.html HTTP/1.1"
    "- GET /doge.html HTTP/1.1"
    "- CONNECT github.com:443 HTTP/1.1"
    "- CONNECT github.com:443 HTTP/1.1"
    
As you can see, `$http_host` is not logged for most requests so I cannot know which sites am I visiting. I tried other variables like `$http_referer` `$http_accept`, they all get logged. I read this [old issue](https://github.com/tatsuhiro-t/spdylay/issues/31) and learned this is because Chrome really sends out `GET /foo.html HTTP/1.1` to proxy and shrpx/nghttpx reconstructs this to `GET http://example.org/foo.html HTTP/1.1` and sends it to Squid. (Am I right?)

So, could nghttpx log reconstructed requests in access log? Currently I need to check Squid's access log to see "normal" request lines (`GET http://example.org/foo.html HTTP/1.1`). But all requests in Squid's access log are from 127.0.0.1 so I think it would be better if nghttpx itself could have an option to log "normal" request lines.

**Comment by tatsuhiro-t** [comment]
It is true that nghttpx only logs request path part of requset as if it works like web server, even if it is configured as http/2 or spdy proxy.  I think it would be better to log absolute URI instead of request path in this case.

**Comment by tatsuhiro-t** [comment]
Fix committed via 4be4d87
@wzyboy Could you verify that this commit fixes this issue?

**Comment by wzyboy** [comment]
Wow thanks for your swift fix!

I have confirmed this commit fixes this issue!
