### ISSUE TITLE
Client proxy mode not using certificate authentication

### ISSUE THREAD

**Issue by wzyboy** [tatsuhiro-t/nghttp2#223]
I am using nghttpx HTTP/2 proxy mode on my server (Squid as a backend), and want to use nghttpx client proxy mode on my laptop.

```
+----Laptop------------------------+            +----Server-----------+
| [cURL] <-- HTTP --> [nghttpx] <--=-- HTTP/2 --=-->[nghttpx,squid]<--=-----> Internet
+----------------------------------+            +---------------------+
```

The nghttpx on my server is configured to verify clients with a CA certificate. So I need to specify certificate and private key on my laptop:

    frontend=127.0.0.1,8080
    backend=proxy.example.org,443
    private-key-file=/path/to/key
    certificate-file=/path/to/cert
    client-proxy=yes

Then I tried `curl -vx http://127.0.0.1:8080 http://google.com` and I got 503 error. If I use `-L INFO` I can see nghttpx just tries to connect downstream and quickly closes the connection.

By mere chance I find out that nghttpx now ignores `--private-key-file` and `--certificate-file` completely. Even if I use `--private-key-file=/file-not-found` it will not throw an error.

So my guess is that nghttpx does not use certificates at all thus fails at TLS verification.

Hint: I remember that I made [this old document](http://spdylay.sourceforge.net/android-spdy-proxy.html) work on my old Android phone. So old version of shrpx is capable of using certificate authentication but current version of nghttpx is not.

**Comment by tatsuhiro-t** [comment]
Use --client-private-key-file and --client-cert-file to specify client private key and certificate file.
If nghttpx on server has self-signed TLS certificate, you will need to specify its certificate to --cacert, or use -k as a last resort.

**Comment by wzyboy** [comment]
Oh I am so sorry. I corrected the option names and it works!
