### ISSUE TITLE
How to compile the 'Hello World' example using libnghttp2_asio?

### ISSUE THREAD

**Issue by semitrivial** [tatsuhiro-t/nghttp2#229]
With a little gymnastics, I was able to compile libnghttp2_asio for the mac (see below for summary of ./configure).  After the ./configure, the make and make install appear to have worked fine, and the examples compiled into working executables.  But the library -lnghttp2_asio does not appear to exist:

    g++ -lnghttp2_asio
    ld: library not found for -lnghttp2_asio

Can you give an example of the exact g++ command one would use to compile the Hello World example?

    g++ hello.cpp -o hello -lnghttp2_asio -lboost_system
    hello.cpp:1:10: fatal error: 'nghttp2/asio_http2_server.h' file not found
    #include <nghttp2/asio_http2_server.h>
             ^

Here is the summary from configure:

```
Version:        0.7.15-DEV shared 13:3:8

    Host type:      x86_64-apple-darwin13.3.0

    Install prefix: /usr/local/http2-15

    C compiler:     gcc

    CFLAGS:         -g -O2

    WARNCFLAGS:     

    LDFLAGS:        

    LIBS:           

    CPPFLAGS:       

    C preprocessor: gcc -E

    C++ compiler:   g++

    CXXFLAGS:       -g -O2 -std=c++11

    CXXCPP:         g++ -E

    Library types:  Shared=yes, Static=yes

    Python:

      Python:         /usr/bin/python

      PYTHON_VERSION: 2.7

      pyexecdir:      ${exec_prefix}/lib/python2.7/site-packages

      Python-dev:     yes

      PYTHON_CPPFLAGS:-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7

      PYTHON_LDFLAGS: -L/System/Library/Frameworks/Python.framework/Versions/2.7/lib -lpython2.7

      Cython:         

    Test:

      CUnit:          no

      Failmalloc:     yes

    Libs:

      OpenSSL:        yes

      Libxml2:        yes

      Libev:          no

      Libevent(SSL):  yes

      Spdylay:        no

      Jansson:        no

      Jemalloc:       no

      Boost CPPFLAGS: -pthread -I/usr/local/include

      Boost LDFLAGS:  -L/usr/local/lib

      Boost::ASIO:    -lboost_system-mt

      Boost::System:  -lboost_system

      Boost::Thread:  -lboost_thread-mt

    Features:

      Applications:   no

      HPACK tools:    no

      Libnghttp2_asio:yes

      Examples:       yes

      Python bindings:no

      Threading:      no
```

**Comment by tatsuhiro-t** [comment]
Assuming you ran `make install`, libraries are installed under /usr/local/http2-15/lib, and header files are installed under /usr/local/http2-15/include.
So probably you need `-I/usr/local/http2-15/include -L/usr/local/http2-15/lib` flags for compiler to find the headers and libraries.

**Comment by semitrivial** [comment]
Thanks, compiling now works.

Is nghttp2 not supposed to support http/1.1 as a fallback?  Running, e.g., ./asio-sv from the examples folder, an attempt to connect with curl gives "Empty reply from server".

```
$ ./asio-sv localhost 3000 1 ~/testkeys/privkey.pem ~/testkeys/cacert.pem
$ curl -v "http://localhost:3000/"
* Adding handle: conn: 0x7ff62c003a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7ff62c003a00) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 3000 (#0)
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:3000
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
```

**Comment by tatsuhiro-t** [comment]
libnghttp2_asio server supports HTTP/2 only.

**Comment by tatsuhiro-t** [comment]
Currently, we have no plan to add HTTP/1.1 support to asio lib.
