### ISSUE TITLE
h2load help

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#231]
Hello,
I would like tu run h2load with -a and -u nghttp client option for getting all assets in the page and doing http2 upgrade connection. I want do it with h2load because I want to download several pages in the same connection. Is there any way to do it?
Best regards

**Comment by tatsuhiro-t** [comment]
h2load does not support HTTP upgrade.  But it can perform HTTP/2 transfer in cleartext, so called direct HTTP/2 connection with prior knowledge.
h2load also lacks feature equivalent to nghttp -a.  But h2load can accept multiple URIs to use, so you can somewhat simulate nghttp -a if you pass the list of of URIs.

**Comment by tatsuhiro-t** [comment]
h2load also now has --timing-script option.  They provide a way to achieve the goal. Closing.
