### ISSUE TITLE
Configure fails to find jemalloc on Darwin

### ISSUE THREAD

**Issue by spwhitt** [tatsuhiro-t/nghttp2#233]
The error:

```
checking for library containing malloc_stats_print... no
configure: error: jemalloc was requested (--with-jemalloc) but not found
```

This happens because the `malloc_stats_print` symbol  does not exist in jemalloc on Darwin:

```
$ nm result/lib/libjemalloc.dylib | grep malloc_stats
0000000000012650 T _je_malloc_stats_print
```

Consequently, the configure script fails to find jemalloc. It builds successfully for me when in change `malloc_stats_print` to `je_malloc_stats_print`.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.  The fix was committed via the above commit.
