### ISSUE TITLE
segfault with nghttpx

### ISSUE THREAD

**Issue by cnrat** [tatsuhiro-t/nghttp2#234]
Hi,

I got a segfault here, plz check it out.
Thank you. @tatsuhiro-t 

nghttpx.conf:
frontend=0.0.0.0,443
backend=127.0.0.1,3200
private-key-file=xxx.key
certificate-file=xxx.crt
http2-proxy=yes
add-x-forwarded-for=yes
strip-incoming-x-forwarded-for=yes
no-via=yes
npn-list=spdy/3.1
no-ocsp=yes
log-level=ERROR
daemon=yes
pid-file=/var/run/nghttpx.pid
workers=5

syslog:
May 15 15:48:00 xxxx kernel: nghttpx[9448]: segfault at 7f8e28400000 ip 00007f8e2ceb97cb sp 00007f8e29ffc8f8 error 4 in libc-2.12.so[7f8e2ce30000+18a000]

backtrace:
#0  0x00007f8e2ceb97cb in memcpy () from /lib64/libc.so.6
#1  0x00007f8e2e5c4a77 in ?? () from /usr/lib64/libssl.so.10
#2  0x00007f8e2e5c4d95 in ssl3_write_bytes () from /usr/lib64/libssl.so.10
#3  0x000000000044c3fc in shrpx::Connection::write_tls(void const*, unsigned long) ()
#4  0x0000000000451c18 in shrpx::ClientHandler::write_tls() ()
    at shrpx_client_handler.cc:230
#5  0x0000000000451a1b in shrpx::(anonymous namespace)::writecb ()
    at shrpx_client_handler.cc:567
#6  0x00007f8e2e8092bd in ev_invoke_pending (loop=0x7f8e2b0af000) at ev.c:3088
#7  0x00007f8e2e80dae2 in ev_run (loop=0x7f8e2b0af000,
    flags=<value optimized out>) at ev.c:3488
#8  0x000000000044a37a in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()(), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, void> >::_M_invoke(std::_Any_data const&)
    () at /usr/local/include/c++/4.9.2/functional:2439
#9  0x000000000044a602 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()()>&, bool&) ()
    at /usr/local/include/c++/4.9.2/functional:2439
#10 0x00007f8e2d1d0d33 in pthread_once () from /lib64/libpthread.so.0
#11 0x000000000044a069 in _ZNSt6thread5_ImplISt12_Bind_simpleIFZNSt13__future_ba---Type <return> to continue, or q <return> to quit---
se17_Async_state_implIS1_IFZN5shrpx6Worker9run_asyncEvEUlvE_vEEvEC4EOS8_EUlvE_vEEE6_M_runEv ()
    at /usr/local/include/c++/4.9.2/x86_64-unknown-linux-gnu/bits/gthr-default.h:699
#12 0x00007f8e2d936690 in execute_native_thread_routine ()
    at ../../../.././libstdc++-v3/src/c++11/thread.cc:84
#13 0x00007f8e2d1cb9d1 in start_thread () from /lib64/libpthread.so.0
#14 0x00007f8e2cf188fd in clone () from /lib64/libc.so.6

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.  Is this related to  #226?

Please tell us the version number of nghttp2, or the commit number you are using.
From the stack trace, the crash occurred inside OpenSSL.
Could you tell us which version of OpenSSL you are using?
We see several vulnerabilities in OpenSSL regarding SSL3_write_byte in the past year.
So please make sure that it is up to date.

**Comment by cnrat** [comment]
Sorry, I'm not sure if it is the same bug. I updated to the latest master version after issue #226 and it worked good until last crash.

OpenSSL version:
OpenSSL 1.0.2a 19 Mar 2015

nghttpx version:
nghttpx nghttp2/0.7.15-DEV

**Comment by tatsuhiro-t** [comment]
Thank you.  OpenSSL version 1.0.2a should be fine.
I'll look into this issue.

**Comment by cnrat** [comment]
Thank you. Just let me know if there is any thing I can help. And I will update this issue if I get another coredump.

**Comment by tatsuhiro-t** [comment]
I just got reproduced this crash.  It seems it only occurs when TLS is enabled.

**Comment by tatsuhiro-t** [comment]
v0.7.9 works fine.  I'm `git bisect`ing now...

**Comment by tatsuhiro-t** [comment]
v0.7.9 does not work.
`git bisect` again, and found the cause of the issue: 585af938287d329333d9c755698fb25aa6471dab

I thought that this commit is harmful because of proper use of SSL_MODE_ACCEPT_MOVING_WRITE_BUFFER, but it seems I was wrong.

**Comment by tatsuhiro-t** [comment]
reverted offending commit 0479f83.  It should work now.

**Comment by cnrat** [comment]
@tatsuhiro-t Thank you! I am now updating to 'nghttpx nghttp2/0.7.15'.

**Comment by cnrat** [comment]
@tatsuhiro-t It had been over 72 hours since last crash. I think this issue should be closed now. Thank you.
