### ISSUE TITLE
malformed input can crash inflatehd

### ISSUE THREAD

**Issue by hannob** [tatsuhiro-t/nghttp2#235]
Passing this file to the hpack unpacking tool inflatehd will crash it:
https://crashes.fuzzing-project.org/nghttp2-inflatehd-nullptr

It looks like a null pointer access, here is the valgrind output:
==18764== Invalid read of size 1
==18764==    at 0x40180E: inflate_hd (inflatehd.cc:121)
==18764==    by 0x40180E: perform() (inflatehd.cc:194)
==18764==    by 0x4014F1: main (inflatehd.cc:268)
==18764==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==18764== 
==18764== 
==18764== Process terminating with default action of signal 11 (SIGSEGV): dumping core
==18764==  Access not within mapped region at address 0x0
==18764==    at 0x40180E: inflate_hd (inflatehd.cc:121)
==18764==    by 0x40180E: perform() (inflatehd.cc:194)
==18764==    by 0x4014F1: main (inflatehd.cc:268)

This was found with the tool american fuzzy lop.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.  Looks like we don't check the type of "wire" properly here.
Will fix this soon.

**Comment by tatsuhiro-t** [comment]
Fixed now. Thank you!
