### ISSUE TITLE
golang spdy is no more

### ISSUE THREAD

**Issue by baranov1ch** [tatsuhiro-t/nghttp2#239]
https://github.com/golang/net/commit/ff8eb9a34a5cbb9941ffc6f84a19a8014c2646ad

spdy package was deleted at all, and simple `go get ...` doesn't work (and thus `make itprep`). For myself, I've made a copy of the older x/net, but probably it's not the best option:)

**Comment by tatsuhiro-t** [comment]
Thank you for letting us know.
We will also remove SPDY feature probably when chrome drops SPDY (next year?).
Until then, we need to keep this spdy package.
We can either rely on your copy, or we can upload our copy under github.com/tatsuhiro-t.

**Comment by tatsuhiro-t** [comment]
We made a copy of spdy package at https://github.com/tatsuhiro-t/spdy
Now integration test works again.
