### ISSUE TITLE
Two server modes doesn't support connections by TOR

### ISSUE THREAD

**Issue by Buddle** [tatsuhiro-t/nghttp2#240]
A Tor client and a shrpx of client-proxy mode as forward proxy for Tor are setup on my local server.On the remote server,shrpx is running as SPDY proxy `--spdy-proxy` with a polipo as the backend proxy server.

1.`Tor OK` Tor<-->Shrpx Forward Proxy<-->nodejs-spdyproxy<-->Tor network
2.`Tor OK` Tor<-->Internet<-->Polipo<-->Tor network
3.`Tor fails` Tor<-->Shrpx Forward Proxy<-->Shrpx SPDY proxy<-->Polipo<-->Tor network
4.`Tor fails` Tor<-->Shrpx Forward Proxy<-->Shrpx SPDY bridge<-->nodejs-spdyproxy<-->Tor network
Meanwhile `Chrome` is able to work with all the for modes.Nodejs-spdyproxy shows all the connections created by Chrome from the shrpx bridge but shows no Tor stream is recieved.

Logs from the server

>[UPSTREAM:0x8b0fdb0] Received upstream SYN_STREAM stream_id=1 (shrpx_spdy_upstream.cc:147)
>[UPSTREAM:0x8b0fdb0] RST_STREAM stream_id=1 (shrpx_spdy_upstream.cc:696)
>[UPSTREAM:0x8b0fdb0] Stream stream_id=1 is being closed (shrpx_spdy_upstream.cc:99)
>[DOWNSTREAM:0x8b55dc0] Deleting (shrpx_downstream.cc:67)
>[DOWNSTREAM:0x8b55dc0] Deleted (shrpx_downstream.cc:77)

Tor hangs up
>Bootstrapped 10%: Finishing handshake with director

**Comment by Buddle** [comment]
Both tested on shrpx and nghttpx 1.0 and got the same result

**Comment by tatsuhiro-t** [comment]
I'm not sure how to debug this.  What does tor perform in this usecase?  Does it correctly forward HTTP request or response to proxy?
If they work without Tor, then Tor is a cause of the problem?

Please note that shrpx and nghttpx are now different from each other.
shrpx supports SPDY for both frontend and backend.
OTOH, nghttpx supports SPDY for frontend if you compiled it with libspdylay.
It does not support SPDY for backend.  It supports HTTP/2 for both frontend and backend BTW.

**Comment by Buddle** [comment]
Tor is set to work as transparent proxy and TCP streams from some of devices are redirected into Tor network.
For the test,I opened both socks5 port and transparent port to listen in Tor.
`On my local server`
* `port 9050----Tor socks5 port`
* `port 9040----Tor transparent proxy`
* `port 8088----frontend port of shrpx forward proxy`
and it is set as forward proxy in Tor.Tor should make all its connections through it.

Tor works fine with Case 1 and Case 2 listed above,which has been checked by socks5 proxy in Chrome and redirected devices.When Tor fails,Chrome can't get access to any website via Tor's socks5 proxy.But Chrome can do through http proxy of shrpx.In shrpx client logs,it seems to get empty responses to Tor connections from the sever.

Case 4 is built to see if node-spdyproxy gets request and the result is that shrpx server didn't work with Tor streams.

If Tor is the cause,I couldn't understand why it is able to work when server is running nodejs-spdyproxy or even polipo without shrpx.
Shoud it be moved to spdylay issue list?

**Comment by tatsuhiro-t** [comment]
Thanks.  spdylay's shrpx refuses stream if its HTTP header lacks mandatory header fields (:path, :host, :method, and :scheme if :method is not CONNECT).  Also it fails if content-length is not set if SYN_STREAM does not FIN bit set.  The latter is being problematic, and it was fixed in nghttp2's nghttpx.  So I think the following setup (replacing shrpx with nghttpx based on 3.) should work:

3'.Tor fails Tor<-->nghttpx Forward Proxy (-p) <-->nghttpx HTTP/2 proxy (-s) <-->Polipo<-->Tor network

> Shoud it be moved to spdylay issue list?

yes, if nghttp2 does not involved.  But please note that since we have HTTP/2 now, spdylay's shrpx is not going to be well maintained. We already fixed many bugs in nghttpx, and not shrpx.

**Comment by Buddle** [comment]
Thank you.
But now,I found that my local server,a Rpi 2 running Raspbian Wheezy has a lot of required packages updating,such as jansson,etc.Even gcc compiler needs upgrading.It seems it is hard to continue test now.What a pity.

**Comment by tatsuhiro-t** [comment]
If you want just nghttpx, the external library dependencies are OpenSSL, libev and zlib only.
It seems there is cross compiler toolchain for raspberrypi.  If it contains recent gcc or clang, then you can compile dependencies and nghttp2, and link them statically.  We make android build using Android NDK toolchain in the same way.

**Comment by Buddle** [comment]
I am encountering an error when compiling nghttp2.
> AR       libnghttpx.a
>   CXXLD    nghttp
> .../arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib: file not recognized: Is a directory
> collect2: error: ld returned 1 exit status
> make[3]: *** [nghttp] Error 1

The gcc in the toolchain is 4.8.3 which I think meets the minimum requirement.

These were exported into environment variables.
`CC=arm-linux-gnueabihf-gcc`
`CXX=arm-linux-gnueabihf-g++`
`LDFLAGS=-L/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib`
`CPPFLAGS=-I/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include`
`PKG_CONFIG_LIBDIR=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/pkgconfig`
`OPENSSL_LIBS=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib`
`OPENSSL_CFLAGS=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include`
`ZLIB_CFLAGS=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include`
`ZLIB_LIBS=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib`
`LIBSPDYLAY_CFLAGS=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include`
`LIBSPDYLAY_LIBS=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib`

Is there anything incorrect?
```
```
Another issue was that `configure` said lack of dependencies,openssl,zlib and libev that I cross-compiled if I only gave `LDFLAGS`,`CPPFLAGS` and `PKG_CONFIG_LIBDIR`.I checked the .pc files in pkgconfig folder.For example,**zlib.pc**
```
prefix=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
sharedlibdir=${libdir}
includedir=${prefix}/include

Name: zlib
Description: zlib compression library
Version: 1.2.8

Requires:
Libs: -L${libdir} -L${sharedlibdir} -lz
Cflags: -I${includedir}
```

I am sorry I am not experienced at it.`PKG_CONFIG_LIBDIR` needs to be overridden when spdylay and nghttp2 are compiled. I don't know what was wrong.

**Comment by Buddle** [comment]
Compiling was always failing
```
./configure --host=arm-linux-gnueabihf
 --prefix=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian 
--disable-shared 
--disable-examples
 --disable-python-bindings
 --with-libxml2
 --with-xml-prefix=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian
 --with-xml-exec-prefix=/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian
 --with-spdylay
 CC=arm-linux-gnueabihf-gcc 
CXX=arm-linux-gnueabihf-g++ 
CPPFLAGS="-I/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include" LDFLAGS="-L/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib" PKG_CONFIG_LIBDIR="/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib/pkgconfig"
ZLIB_CFLAGS="-I/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include" ZLIB_LIBS="-L/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib" OPENSSL_CFLAGS="-I/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include" 
OPENSSL_LIBS="-L/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib" LIBSPDYLAY_CFLAGS="-I/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include" 
LIBSPDYLAY_LIBS="-L/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib"
```

```
configure: summary of build options:

    Version:        1.0.1 shared 14:1:0
    Host type:      arm-unknown-linux-gnueabihf
    Install prefix: /home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian
    C compiler:     arm-linux-gnueabihf-gcc
    CFLAGS:         -g -O2
    WARNCFLAGS:
    LDFLAGS:        -L/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/lib
    LIBS:
    CPPFLAGS:       -I/home/vps/rpi/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/include
    C preprocessor: arm-linux-gnueabihf-gcc -E
    C++ compiler:   arm-linux-gnueabihf-g++
    CXXFLAGS:       -g -O2 -std=c++11
    CXXCPP:         arm-linux-gnueabihf-g++ -E
    Library types:  Shared=no, Static=yes
    Python:
      Python:
      PYTHON_VERSION:
      pyexecdir:
      Python-dev:
      PYTHON_CPPFLAGS:
      PYTHON_LDFLAGS:
      Cython:         cython
    Test:
      CUnit:          no
      Failmalloc:     yes
    Libs:
      OpenSSL:        yes
      Libxml2:        yes
      Libev:          yes
      Libevent(SSL):  no
      Spdylay:        yes
      Jansson:        no
      Jemalloc:       no
      Zlib:           yes
      Boost CPPFLAGS:
      Boost LDFLAGS:
      Boost::ASIO:
      Boost::System:
      Boost::Thread:
    Features:
      Applications:   yes
      HPACK tools:    no
      Libnghttp2_asio:no
      Examples:       no
      Python bindings:no
      Threading:      yes
```


***But `make` failed***
```
  CXXLD    nghttp
nghttp.o: In function `nghttp2::HttpClient::initiate_connection()':
.../nghttp2-1.0.1/src/nghttp.cc:508: undefined reference to `SSL_new'
.../nghttp2-1.0.1/src/nghttp.cc:515: undefined reference to `SSL_set_fd'
.../nghttp2-1.0.1/src/nghttp.cc:516: undefined reference to `SSL_set_connect_state'
.../nghttp2-1.0.1/src/nghttp.cc:540: undefined reference to `SSL_free'
.../nghttp2-1.0.1/src/nghttp.cc:532: undefined reference to `SSL_ctrl'
.../nghttp2-1.0.1/src/nghttp.cc:511: undefined reference to `ERR_get_error'
.../nghttp2-1.0.1/src/nghttp.cc:511: undefined reference to `ERR_error_string'
nghttp.o: In function `nghttp2::HttpClient::disconnect()':
.../nghttp2-1.0.1/src/nghttp.cc:589: undefined reference to `SSL_set_shutdown'
.../nghttp2-1.0.1/src/nghttp.cc:590: undefined reference to `ERR_clear_error'
.../nghttp2-1.0.1/src/nghttp.cc:591: undefined reference to `SSL_shutdown'
.../nghttp2-1.0.1/src/nghttp.cc:592: undefined reference to `SSL_free'
nghttp.o: In function `nghttp2::HttpClient::read_tls()':
.../nghttp2-1.0.1/src/nghttp.cc:1119: undefined reference to `ERR_clear_error'
.../nghttp2-1.0.1/src/nghttp.cc:1123: undefined reference to `SSL_read'
.../nghttp2-1.0.1/src/nghttp.cc:1130: undefined reference to `SSL_get_error'
nghttp.o: In function `nghttp2::HttpClient::write_tls()':
.../nghttp2-1.0.1/src/nghttp.cc:1151: undefined reference to `ERR_clear_error'
.../nghttp2-1.0.1/src/nghttp.cc:1155: undefined reference to `SSL_write'
.../nghttp2-1.0.1/src/nghttp.cc:1162: undefined reference to `SSL_get_error'
nghttp.o: In function `nghttp2::HttpClient::connection_made()':
.../nghttp2-1.0.1/src/nghttp.cc:906: undefined reference to `SSL_get0_next_proto_negotiated'
.../nghttp2-1.0.1/src/nghttp.cc:921: undefined reference to `SSL_get0_alpn_selected'
.../nghttp2-1.0.1/src/nghttp.cc:921: undefined reference to `SSL_get0_alpn_selected'
nghttp.o: In function `nghttp2::HttpClient::tls_handshake()':
.../nghttp2-1.0.1/src/nghttp.cc:1079: undefined reference to `ERR_clear_error'
.../nghttp2-1.0.1/src/nghttp.cc:1081: undefined reference to `SSL_do_handshake'
.../nghttp2-1.0.1/src/nghttp.cc:1088: undefined reference to `SSL_get_error'
nghttp.o: In function `communicate':
.../nghttp2-1.0.1/src/nghttp.cc:1964: undefined reference to `SSLv23_client_method'
.../nghttp2-1.0.1/src/nghttp.cc:1964: undefined reference to `SSL_CTX_new'
.../nghttp2-1.0.1/src/nghttp.cc:1974: undefined reference to `SSL_CTX_ctrl'
.../nghttp2-1.0.1/src/nghttp.cc:1975: undefined reference to `SSL_CTX_ctrl'
.../nghttp2-1.0.1/src/nghttp.cc:1976: undefined reference to `SSL_CTX_ctrl'
.../nghttp2-1.0.1/src/nghttp.cc:1977: undefined reference to `SSL_CTX_set_cipher_list'
.../nghttp2-1.0.1/src/nghttp.cc:2002: undefined reference to `SSL_CTX_set_next_proto_select_cb'
.../nghttp2-1.0.1/src/nghttp.cc:2007: undefined reference to `SSL_CTX_set_alpn_protos'
.../nghttp2-1.0.1/src/nghttp.cc:2076: undefined reference to `SSL_CTX_free'
.../nghttp2-1.0.1/src/nghttp.cc:1994: undefined reference to `SSL_CTX_use_certificate_chain_file'
.../nghttp2-1.0.1/src/nghttp.cc:1995: undefined reference to `ERR_get_error'
.../nghttp2-1.0.1/src/nghttp.cc:1985: undefined reference to `SSL_CTX_use_PrivateKey_file'
.../nghttp2-1.0.1/src/nghttp.cc:1986: undefined reference to `ERR_get_error'
.../nghttp2-1.0.1/src/nghttp.cc:1995: undefined reference to `ERR_error_string'
.../nghttp2-1.0.1/src/nghttp.cc:1967: undefined reference to `ERR_get_error'
.../nghttp2-1.0.1/src/nghttp.cc:1978: undefined reference to `ERR_get_error'
nghttp.o: In function `nghttp2::main(int, char**)':
.../nghttp2-1.0.1/src/nghttp.cc:2403: undefined reference to `SSL_load_error_strings'
.../nghttp2-1.0.1/src/nghttp.cc:2404: undefined reference to `SSL_library_init'
.../nghttp2-1.0.1/src/nghttp.cc:2405: undefined reference to `OPENSSL_add_all_algorithms_noconf'
.../nghttp2-1.0.1/src/nghttp.cc:2406: undefined reference to `OPENSSL_config'
ssl.o: In function `nghttp2::ssl::LibsslGlobalLock::LibsslGlobalLock()':
.../nghttp2-1.0.1/src/ssl.cc:71: undefined reference to `CRYPTO_num_locks'
.../nghttp2-1.0.1/src/ssl.cc:76: undefined reference to `CRYPTO_set_locking_callback'
collect2: error: ld returned 1 exit status
make[3]: *** [nghttp] Error 1
make[3]: Leaving directory `/home/vps/rpi/nghttp2-1.0.1/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/vps/rpi/nghttp2-1.0.1/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/vps/rpi/nghttp2-1.0.1'
make: *** [all] Error 2
```

**Comment by Buddle** [comment]
I replaced the three `dependencies_LIBS` with `dependencies.a` just now and it was able to be compiled.I have tried the `nghttpx` in my Raspberry Pi and it works fine and Tor can creates connections via this forward proxy.

Thank you.
But i just wonder why `LDFLAGS` and `PKG_CONFIG_LIBDIR` didn't work.

**Comment by tatsuhiro-t** [comment]
It seems that pkg-config which comes with cross compiler toolchain requires PKG_CONFIG_PATH instead of PKG_CONFIG_LIBDIR, and latter gets ignored.  There is a crucial difference between these two variables, and if I understand correctly, we should use PKG_CONFIG_LIBDIR for cross compiling.  But for some reason, it does not work for this particular pkg-config build.

So, if you replace PKG_CONFIG_LIBDIR with PKG_CONFIG_PATH, then it would work.
Alternatively, you can use build system's pkg-config, which usually understands PKG_CONFIG_LIBDIR correctly.

> I replaced the three dependencies_LIBS with dependencies.a

Acutally, you should list -L flag and actual library (usually, -l + library name, e.g., -lssl) in *_LIBS, not just -L.  Since we are building nghttpx with static library, just listing *.a file works here.


Cross compiling is always tricky, so congratulation to successful build.

**Comment by Buddle** [comment]
I hadn't compiled anything useless,only the five dependencies so the library folder didn't contain any other files except a folder named gcc original from the toolchain package.Meanwhile it was strange this didn't work if I added to `OPENSSL_LIBS` but could if I replaced `OPENSSL_LIBS` with  `.../libssl.a/ .../libcrypto.a` and still set `LIBSPDYLAY_LIBS` `-L<DIR> -lspdylay`.On contrary,`ZLIB_LIBS` seemed OK merely with `-L<DIR>`.Finaly,I replaced all of them with their static library.

**Comment by tatsuhiro-t** [comment]
Linker options are quite complex and ordering is very important.  It is possible that -lz may be included in other *_LIBS or other variables.
