### ISSUE TITLE
proxy problem for nghttpx

### ISSUE THREAD

**Issue by micro-zheng** [tatsuhiro-t/nghttp2#241]
1, with "--backend-http-proxy-uri" parameter,  the CONNECT request host should be the URL host, not the configure value. 

2, with "--backend-http-proxy-uri" parameter, if the backend server is a https(1.x) server, it can not work.

**Comment by tatsuhiro-t** [comment]
I think the current implementation is correct.
nghttpx connects to the backend proxy server through the proxy server specified in `--backend-http-proxy-uri`.  So the host name appeared in CONNECT request must be backend proxy.

**Comment by micro-zheng** [comment]
Refer this example:
CONNECT www.google.com:443 HTTP/1.0
User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E)
Proxy-Connection: Keep-Alive
Content-Length: 0
Host: www.google.com
Pragma: no-cache
Proxy-Authorization: NTLM xxxx

Use firefox access google website, I got the data by wireshark. 
browse connect to -backend-http-proxy-uri,  and the CONNECT request indicate which website the proxy should connect.

**Comment by tatsuhiro-t** [comment]
Probably you misunderstand the option.  Please read carefully my comment above.
Usually, you don't have to use that option.
The actual CONNECT method handling is done elsewhere.
The only use case of `--backend-http-proxy-uri` option is make nghttpx behind firewall connect to the another nghttpx outside firewall.  For the other use case, that option is pretty much useless.
