### ISSUE TITLE
Gzip Compression in nghttp2

### ISSUE THREAD

**Issue by FatimaZar** [tatsuhiro-t/nghttp2#245]
Hi,

I am experimenting with nghttp2. When fetching a webpage via nghttp2 server, I did not find the "Content-Encoding: gzip" response header. Does this mean that the nghttp2 server does not do gzip compression ?
For my experiments I would like to disable gzip compression.

Thank you.

**Comment by tatsuhiro-t** [comment]
Assuming you are talking about nghttpd server, no, it does not support gzip compression when serving static files.

**Comment by FatimaZar** [comment]
Yes, I meant the nghttpd server. Thanks for the reply.
