### ISSUE TITLE
Making sure nghttpx is in front of me

### ISSUE THREAD

**Issue by szepeviktor** [tatsuhiro-t/nghttp2#248]
Is there a way to _safely_ detect `nghttpx` as a reverse proxy?
I use nginx as a HTTP/1.1 server behind `nghttpx`.

**Comment by szepeviktor** [comment]
Up to now I've found only `HTTP_X_FORWARDED_PROTO`.

**Comment by szepeviktor** [comment]
I am thinking of something like `--add-response-header=<HEADER>` for downstream.

**Comment by szepeviktor** [comment]
For example Amazon CloudFront has `HTTP_X_AMZ_CF_ID`.

**Comment by tatsuhiro-t** [comment]
via header field is a candidate, but client can adds it to fake nginx at the back.
It means that currently we don't have no means to achieve this.
Perhaps, we can add --add-request-header option to append some new headers to backend.

**Comment by szepeviktor** [comment]
Thank you for your consideration.

**Comment by tatsuhiro-t** [comment]
--add-request-header option was added via 00efa86

**Comment by szepeviktor** [comment]
Thank you.
I hope it actually works.

**Comment by szepeviktor** [comment]
> This  option just  appends header field  and won't replace anything  already set.

So this could be faked from the client (I mean from the browser)?

**Comment by tatsuhiro-t** [comment]
Yes.  There is not way to distinguish the header from client or proxy if they are the same.
Perhaps, you can create "secret" header name and value, which cannot be guessable from client.

**Comment by szepeviktor** [comment]
Thanks. I will do that.
