### ISSUE TITLE
Detect disconnects the Python API

### ISSUE THREAD

**Issue by mrdon** [tatsuhiro-t/nghttp2#251]
Currently, on_close isn't called when the client disconnects, making it not possible to free up resources, connections, etc.  It would be nice for either on_close to be called whenever the connection goes away or provide another callback to handle this event.

**Comment by tatsuhiro-t** [comment]
With c2ca04c1db0c60614c0f8c71bb9f193709ae5e70, on_close callback is called when connection is lost for server session.

**Comment by mrdon** [comment]
Excellent, thanks for the super quick fix.
