### ISSUE TITLE
503 Service Unavailablenghttpx nghttp2/1.0.1-DEV at port 443

### ISSUE THREAD

**Issue by ilmalalifriansyah** [tatsuhiro-t/nghttp2#252]
Before that,
I introduce, that I'm dummy in Ubuntu and HTTP protocol.
I use HTTP/2 for my final project.

+-------------------------------------------------------------------------------------------------+
WAN  ----------  (front-end,443)  nghttp2 (back-end,444)  ----------  Web Server
                                                   nghttpx (i using proxy)
+-------------------------------------------------------------------------------------------------+

I successed implementation this nghttp/2 in my web page.

But my Final Project is use HTTP/2 in instant messaging.
I can access my instant messaging in my localhost but not using HTTPS, but while I access in my with this nghttp2, I using HTTPS,  I get error this :

503 Unavailable Service 
nghttpx nghttp2/1.0.1-DEV at port 443

==========

My script abaout nghttpx is :

sudo nghttpx -s --backend-http1-connections-per-frontend=4096 --backend-http2-connections-per-worker=4096  -L FATAL --accesslog-file=/home/ilmal/web/log -f*,443 -blocalhost,444 ~/certs/self.key ~/certs/self.crt

==========

The step error like this:

I'm using HTTPS in this.

![home](https://cloud.githubusercontent.com/assets/7435712/8050878/b6132a3c-0e9e-11e5-8d50-035ed18c84ee.jpg)
 
Then I login >>> but after login get this error >>>

![error_home](https://cloud.githubusercontent.com/assets/7435712/8050882/d8dfc6ba-0e9e-11e5-8938-87e4ae5cb7a4.png)

The I refresh (F5) can get throug to my next page >>>

![chat_room](https://cloud.githubusercontent.com/assets/7435712/8050889/ee67e666-0e9e-11e5-8e24-4ded7794226a.jpg)

But in this page can't do anything.

But when using HTTP1 (not using HTTPS) can do chat and anything, like this >>>
![chat_room_upload_http1](https://cloud.githubusercontent.com/assets/7435712/8050904/2ded8782-0e9f-11e5-83c8-0aa478e14d4e.jpg)

==========

What is my error? 
3 days I confused with it.

I really apreciate it for your help.

Regards

**Comment by tatsuhiro-t** [comment]
503 means that nghttpx could not connect to backend web server, or creating backend request failed for some reason.
INFO level logging could be useful here (use -LINFO option).
Which protocol are you using between client and backend web server?  Just plain HTTP? Or WebSocket?

**Comment by ilmalalifriansyah** [comment]
I'm sorry, What does it means? (I'm sorry, I'm dummy in ubuntu an Protocol),

"INFO level logging could be useful here (use -LINFO option)"

backend web server I use HTTP1 (port 444)

I confused, why with HTTPS can't acces function ajax to send chat or upload files.
But, when using HTTP I can do anything normal in chat

And what must I do now?

Really appreciate your help Mr. @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
You use "-L WARN" in your command line, just replace WARN with INFO, then you get detailed logging in your log file.
As for the command-line, you must remove `-s` option in this reverse proxying scenario.
Also `--backend-http1-connections-per-frontend=4096 --backend-http2-connections-per-worker=4096` are meaning less, in this setup, so remove it for clarity.  There are some cases where backend listens only to ipv4 or ipv6.  It is better to stick to either one.  In this particular thread, I recommend to use ipv4, so use `-b127.0.0.1,444`, and make sure that backend server listens on ipv4 address.  From the status code 503, this could be a culprit.
So command-line could be simplified like so:
```
sudo nghttpx  -LINFO --accesslog-file=/home/ilmal/web/log -f*,443 -b127.0.0.1,444 ~/certs/self.key ~/certs/self.crt
```
HTTP/2 ajax requests over TLS should work.  Probably, there are some trouble between proxy and backend.

**Comment by ilmalalifriansyah** [comment]
I tried it,

when i run those command:
sudo nghttpx  -LINFO --accesslog-file=/home/ilmal/web/log -f*,443 -b127.0.0.1,444 ~/certs/self.key ~/certs/self.crt

==========
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:2072 Resolving backend address
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:155 Address resolution for 127.0.0.1 succeeded: 127.0.0.1
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:155 Address resolution for 127.0.0.1 succeeded: 127.0.0.1
10/Jun/2015:22:35:23 +0700 PID11719 [NOTICE] Listening on ::, port 443
10/Jun/2015:22:35:23 +0700 PID11719 [NOTICE] Listening on 0.0.0.0, port 443
10/Jun/2015:22:35:23 +0700 PID11719 [NOTICE] Renew ticket keys: main
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:614 ticket keys generation done
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:616 name: d4dc96624ac26d8dd7cde60f9333f774
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx_connection_handler.cc:366 Start ocsp update for /root/certs/self.crt
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:749 Entering event loop
fetch-ocsp-response (using OpenSSL 1.0.1f 6 Jan 2014)
failed to extract ocsp URI from /root/certs/self.crt
10/Jun/2015:22:35:23 +0700 PID11719 [WARN] shrpx_connection_handler.cc:481 ocsp query command for /root/certs/self.crt failed: error=0, rstatus=65280, status=255
==========

And then I access my localhost,

https://localhost

and then got same error

**Comment by ilmalalifriansyah** [comment]
I tried it,

when i run those command:
sudo nghttpx -LINFO --accesslog-file=/home/ilmal/web/log -f*,443 -b127.0.0.1,444 ~/certs/self.key ~/certs/self.crt

==========

10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:2072 Resolving backend address
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:155 Address resolution for 127.0.0.1 succeeded: 127.0.0.1
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:155 Address resolution for 127.0.0.1 succeeded: 127.0.0.1
10/Jun/2015:22:35:23 +0700 PID11719 [NOTICE] Listening on ::, port 443
10/Jun/2015:22:35:23 +0700 PID11719 [NOTICE] Listening on 0.0.0.0, port 443
10/Jun/2015:22:35:23 +0700 PID11719 [NOTICE] Renew ticket keys: main
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:614 ticket keys generation done
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:616 name: d4dc96624ac26d8dd7cde60f9333f774
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx_connection_handler.cc:366 Start ocsp update for /root/certs/self.crt
10/Jun/2015:22:35:23 +0700 PID11719 [INFO] shrpx.cc:749 Entering event loop
fetch-ocsp-response (using OpenSSL 1.0.1f 6 Jan 2014)
failed to extract ocsp URI from /root/certs/self.crt
10/Jun/2015:22:35:23 +0700 PID11719 [WARN] shrpx_connection_handler.cc:481 ocsp query command for /root/certs/self.crt failed: error=0, rstatus=65280, status=255

==========

And I try again acces my localhost,

https://localhost.

I got the same error
v
v
![error_503_nghttp](https://cloud.githubusercontent.com/assets/7435712/8086874/dd641f64-0fc1-11e5-9b0d-a72dd22ecf22.png)


and then I refresh the page (F5)

And the command-line show this:

![error_when_access_localhost_using_https](https://cloud.githubusercontent.com/assets/7435712/8087005/ac080844-0fc2-11e5-8d99-083594232a62.png)

![2](https://cloud.githubusercontent.com/assets/7435712/8087010/b87e273e-0fc2-11e5-8e72-1abd764bea1d.png)

![4](https://cloud.githubusercontent.com/assets/7435712/8087011/bc173b1a-0fc2-11e5-9f5b-b87e44b0b138.png)

![5](https://cloud.githubusercontent.com/assets/7435712/8087020/c261a9c4-0fc2-11e5-91d7-8d254f11e440.png)

![6](https://cloud.githubusercontent.com/assets/7435712/8087026/c691e9e6-0fc2-11e5-976b-39222d85a8cf.png)


=========

What next I must do. The error still there.

Really appreciate it Mr. @tatsuhiro-t

**Comment by tatsuhiro-t** [comment]
First download connection goes to 127.0.0.1:81, which is very strange, since you specify port 444 in command-line.  Please make sure that comment all lines in /etc/nghttpx/nghttpx.conf or rename it.  I think that file contains backend=localhost:81 or similar.

**Comment by tatsuhiro-t** [comment]
This is a bit old thread.  We have enhanced nghttpx quite a bit since then, and your issue might be fixed.  I close this issue now, but please feel free to reopen if the problem still exists.
