### ISSUE TITLE
Unable to consume data of a closed stream

### ISSUE THREAD

**Issue by lomnicky** [tatsuhiro-t/nghttp2#253]
When using custom flow control, it is not possible to consume data of already closed streams as on_frame_recv_callback is never called by nghttp2_session_on_data_received. When multiple frames arrive for a closed stream (or reset), the connection window is decremented. As there is no way to get notified about such data, it can't be consumed. The situation results in window depletion and complete "dedlock" of the connection.

Induced with library version 1.0.1.

**Comment by tatsuhiro-t** [comment]
We already handles this condition well.  When `nghttp2_option_set_no_auto_window_update(s, 1)` is used, and DATA is arrived to closed stream, its data payload is considered as consumed immediately for connection.  When certain amount of window is consumed, library automatically schedules WINDOW_UPDATE for connection, to avoid deadlock.

Do you have the test case to reproduce the deadlock scenario?

**Comment by lomnicky** [comment]
The scenario is very specific. We are coding an HTTP2 proxy that sits between two endpoints. It creates two sessions - upstream and downstream - and inspects/forwards all the frames. The flow control is managed separately for both sessions. What I do to induce the problem is starting 10 simultaneous connections from client to get a large binary file. The proxy is programmed so that it resets half of those connections after receiving few megs of data (stress testing). So, after few DATA frames, both endpoints receive a RST frame. The proxy immediatelly calls consume to free all data of the reset stream which increases the consumed size of the connection. However, after the last reset, no WINDOW_UPDATE is sent from the proxy to the server and as the server filled the window, it doesn't send any more data. If I debug the proxy, the session has recv_window_size of 0xffff and consumed size > 0.

**Comment by tatsuhiro-t** [comment]
If I understand correctly, you are using 2 nghttp2_session for frontend and backend in proxy,
and your problem is that nghttp2_session to backend server does not send WINDOW_UPDATE to server, so server cannot send more DATA.

Please make sure that when frontend stream is reset, then manually reset backend stream as well, for instance, send RST_STREAM.  There may be some data pending to send frontend, so make it consume in nghttp2_on_stream_close() callback.  And call nghttp2_session_mem_send() (or nghttp2_session_send()), and send scheduled WINDOW_UPDATE to backend server.

We have the same code in nghttpx.  Take a look at https://github.com/tatsuhiro-t/nghttp2/blob/d4d7597efb58211caeb9cb93326ad8986369d40d/src/shrpx_http2_upstream.cc#L65

**Comment by lomnicky** [comment]
I do exactly what you say. If one side is reset, than the other side is reset too. I do not submit WINDOW_UPDATEs directly, but I use "consume" functions to do this.

The behavior I basically see under the debugger after a stream is reset is following:
1. A DATA frame arrives
2. Breakpoint in _session_mem_recv when state is _IB_READ_DATA and _session_get_stream returns NULL is hit. The stream ID corresponds to the one that was reset. In this state, the connection window size is already shrinked by the data size by calling session_update_recv_connection_window_size.
3. If I step further, the code ends current iteration without calling session_update_connection_consumed_size. The next iteration processes the next frame.
4. session_update_connection_consumed_size is called in _IB_IGN_DATA case, but the code never gets there

**Comment by tatsuhiro-t** [comment]
Thanks.  OK, I understand the situation, and it is probably a bug in nghttp2 library.  I'll add unit test for this to confirm, and fix it.

**Comment by tatsuhiro-t** [comment]
Fixed committed via b5717cd.
I confirmed this is a bug, in tricky race condition.  Please test with the latest fix.

**Comment by lomnicky** [comment]
Confirmed. The connection is no longer "deadlocked" in this case. Thanks.

**Comment by tatsuhiro-t** [comment]
Thank you.  Let's close the issue.
