### ISSUE TITLE
Separate ipv4 and ipv6 for frontend

### ISSUE THREAD

**Issue by webeau** [tatsuhiro-t/nghttp2#260]
I have a server with multiple ipv4 addresses and a block of ipv6 addresses.  Each domain I host here has only one ipv4 and ipv6 address per certificate.  However, I don't see a way to specify a single nghttpx instance so it accepts frontend ips for one ipv4 and one ipv6 - it is either one or the other.  Is the workaround starting separate daemons for each address even if they use the same certs?

Also, other ip addresses have other certs.  I am pretty sure the only thing to do for that case is to start more processes pointing to different backend ports for the time being.

**Comment by tatsuhiro-t** [comment]
Separate daemons for each address works.  Alternatively, configure additional hostname for these addresses, and store it in /etc/hosts.  Then you can pass its name to -f option.
Certificate is no problem in this case, it only matters server name presented by client via SNI.  nghttpx supports multiple certificates via --subcert option, and it switches certificate based on SNI.

**Comment by dimaqq** [comment]
@tatsuhiro-t I think you missed the peculiarity of @webeau 's config.

He wants:
* instance #1 listens on 10.0.0.1 & fe80::1 at the same time
* instance #2 listens on 10.0.0.2 & fe80::1 at the same time
* etc...

**Comment by tatsuhiro-t** [comment]
Thanks.  I think that is my understanding too.
I suggested that write something below in /etc/hosts:
```
10.0.0.1  instance1
fe80::1    instance1
```

And, run `nghttpx -finstance1,443`.
A part from the feasibility of the above workaround, am I still missing something?

**Comment by webeau** [comment]
Again, thanks.  This works.

**Comment by berge** [comment]
I'd like to see this issue reopened. It's very useful to configure a daemon to bind to a set of specific addresses (or sets of blocks of addresses, with Any-IP or IP_TRANSPARENT). Setting up a name in /etc/hosts that points to a set of addresses as a workaround doesn't really scale if you've got a lot of addresses, breaks assumptions for humans, is confusing to humans who read the nghttpx config and potentially breaks other things on the system which depends on answers from DNS not being overridden by /etc/hosts. In general, depending on name resolution for daemon configuration can be problematic.

Accepting multiple -f options, or accepting a pattern for -f which allows multiple addresses, would be very helpful.

**Comment by tatsuhiro-t** [comment]
Fair enough.  Allowing multiple -f options is acceptable solution.  The annoying thing is that we have to convey all listening sockets to new process when graceful shutdown is performed, but it is not so hard.

**Comment by tatsuhiro-t** [comment]
As of aa07fe7fa679c9b60f777137ebc77db8282707bb, nghttpx accepts multiple -f options to listen to multiple interfaces.
