### ISSUE TITLE
stream_update_dep_on_detach_item: Assertion `stream->dpri == NGHTTP2_STREAM_DPRI_TOP' failed.

### ISSUE THREAD

**Issue by 64616E69656C** [tatsuhiro-t/nghttp2#264]
Hi,

since this morning after upgrading to v1.0.3, on a high load website nghttpx crashes every few minutes with the following error:

"nghttpx: nghttp2_stream.c:359: stream_update_dep_on_detach_item: Assertion `stream->dpri == NGHTTP2_STREAM_DPRI_TOP' failed."

backend is nginx 1.9.2, which worked fine with v1.0.2. 

Config (unchanged between v1.0.2 and v1.0.3):
```
daemon=yes
no-ocsp=yes
user=www-data
workers=8
frontend=0.0.0.0,443
backend=127.0.0.1,8000
cacert=/etc/ssl/XXX.crt
private-key-file=/etc/ssl/XXX.key
certificate-file=/etc/ssl/XXX.crt
dh-param-file=/etc/ssl/dh4096.pem
tls-proto-list=TLSv1.2,TLSv1.1,TLSv1.0
npn-list=h2,h2-16,h2-14,spdy/3.1,http/1.1
ciphers=ECDH+CHACHA20:ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DHE+CHACHA20:DH+AESGCM:DH+AES256:DH+AES:!MEDIUM:!LOW:!eNULL:!aNULL
log-level=WARN
accesslog-file=/var/log/nghttpx/access.log
errorlog-file=/var/log/nghttpx/error.log
add-x-forwarded-for=yes
add-response-header=Public-Key-Pins:pin-sha256="xxx"; pin-sha256="xxx"; max-age=15768000; includeSubDomains
add-response-header=X-Content-Type-Options:nosniff
add-response-header=X-Frame-Options:SAMEORIGIN
add-response-header=X-XSS-Protection:1; mode=block
add-response-header=Strict-Transport-Security:max-age=31536000; preload
add-response-header=Front-End-Https:on
add-response-header=X-UA-Compatible:IE=Edge,chrome=1
no-host-rewrite=yes
```

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.
Fix committed via 1945d0f
I'll release 1.0.4 in a few hours.

**Comment by tatsuhiro-t** [comment]
1.0.4 released https://github.com/tatsuhiro-t/nghttp2/releases/tag/v1.0.4

**Comment by 64616E69656C** [comment]
Works like a charm. Thanks you for the quick fix and release.

**Comment by 64616E69656C** [comment]
Tatsuhiro, please take look at the referenced issue with hhvm. I just downgraded nghttp2 back to 1.0.2 to be sure, as this version did not have the hhvm unresponsive issues. I'll wait if it happens again, but do you think this could be nghttp2 related?

**Comment by tatsuhiro-t** [comment]
If I understand it correctly, nghttpx acts like HTTP/2 proxy in front of nginx, and then HHVM sits behind the nginx.  If HHVM segfaulted, then I don't think this is triggered by nghttpx, since we are just connected via TCP.  On the other hand, HHVM is alive, but client cannot connect to the service, then nghttpx may have an issue.  We have #267 for similar problem with chrome clients.  If HHVM linked with libnghttp2 library, then there may be some issues related to nghttp2.  We found several rough edges in priority handling (but normally, that code path is not taken), and will fix them very soon.

**Comment by 64616E69656C** [comment]
Yes, that's correct. nghttpx acts as TLS offloader and h2 proxy, nginx serves static files and proxy_passes php/hh files to hhvm.
There are two separate issues, "hhvm crashing randomly" and "hhvm being unresponsive", which are most likely not linked to each other. In production, everything's fine after downgrading back to 1.0.2 for the last 3 hours. All other low/avg traffic sites are not affected by this.

Since I can't poke around in productive, I've tried to reproduce the issue with "hhvm becoming unresponsive" with ab and h2load on my little dev-vm (same setup, same app, nginx 1.9.2, nghttp2 1.0.4, hhvm 3.7.2).
Running 10k requests with 10/100 conccurrent clients, nghttpx just yawns a little, nginx didn't notice the test at all and hhvm/redis are doing their hard work, but nothing happens during testing, I'm also able to browse the site (slowly). Using 1000 concurrent clients, nghttpx starts failing.

````
finished in 5.86s, 1705 req/s, 733.71KB/s
requests: 10000 total, 10000 started, 10000 done, 21 succeeded, 9979 failed, 0 errored
status codes: 21 2xx, 0 3xx, 0 4xx, 9979 5xx
```

nghttpx error logs shows
```
24/Jun/2015:16:01:32 +0200 PID4007 [WARN] shrpx_http_downstream_connection.cc:157 [DCONN:0x7f8a36905f80] socket() failed; errno=24
24/Jun/2015:16:01:32 +0200 PID4007 [WARN] shrpx_connect_blocker.cc:59 connect failure, start sleeping 4
```

But still, hhvm is alive and well, and also, in productive nghttpx error log is empty. So, basicly I'm still not quite sure what happened. Any idea how to reproduce this more effectively than with h2load/ab?

**Comment by tatsuhiro-t** [comment]
errno=24 indicates EMFILE, which is "Too many open files."
It is most likely that nghttpx ran out of file descriptor.  Please check that `ulimit -n`.  By default, it is very low value for high traffic server.

**Comment by tatsuhiro-t** [comment]
Perhaps, you can check which layer behaves weirdly.  For example, when unresponsive time happens, you can send request directly to (1) nghttpx, (2) nginx and (3) hhvm.
If (1) is unresponsive, but (2) and (3) are OK, then nghttpx may have an issue.
Or, if all (1), (2) and (3) are unresponsive, then hhvm could be a culprit.

**Comment by 64616E69656C** [comment]
Will do, but I'll have to wait until sunday or a night shift, since I have to upgrade to 1.0.4 again to test this. Since downgrade, this did not happen anymore, so I guess there's a change between 1.0.2 and 1.0.4 involved.

BTW: I'm having fs.file-max = 100000 and noafile soft 4096/hard 10240 for www-data.

**Comment by tatsuhiro-t** [comment]
There is not much change since v1.0.2.  The large change is priority handling, theoretically it could freeze stream.  I reviewed code several times, and I fixed one bug after v1.0.4 release.
Currently, priority handling is only done by Firefox.  I assume that your site is mainly accessed by browser.  Any other browsers other than Firefox do not use priority, so they should not be affected by this change.

**Comment by tatsuhiro-t** [comment]
I added strict verification code for stream priority state, and used nghttpx as HTTP/2 proxy, and navigated many sites, but no issue has been found so far.  It seems working correctly.
Since you mentioned that low traffic sites are not affected by this issue, so it might be other issues, say, resource exhaustion.  But it does not explain why nghttp2 v1.0.2 works well, but not v1.0.4 didn't.  I can make a guess by saying we have some particular situation when v1.0.4 is deployed to make hhvm unresponsive, and it was not happened while in v1.0.2.  Yeah, it is just a guess, so will see when v1.0.4 is deployed again.

**Comment by 64616E69656C** [comment]
I'm building nghttp2 1.0.5 package now, and will deploy it on monday morning. Let's see what happens then, until now nothing happened after downgrading to 1.0.2 (just one regular hhvm crash) so far. One interesting thing though, after restarting hhvm the first time it became unresponsive, nginx had thrown a few alerts: 
```
2015/06/24 09:49:54 [alert] 25098#0: *170972 open socket #39 left in connection 6
2015/06/24 09:49:54 [alert] 25098#0: *170974 open socket #41 left in connection 9
2015/06/24 09:49:54 [alert] 25098#0: *170980 open socket #45 left in connection 11
2015/06/24 09:49:54 [alert] 25098#0: *170981 open socket #46 left in connection 13
2015/06/24 09:49:54 [alert] 25098#0: *170977 open socket #37 left in connection 14
2015/06/24 09:49:54 [alert] 25098#0: *170975 open socket #42 left in connection 16
2015/06/24 09:49:54 [alert] 25098#0: *170978 open socket #44 left in connection 39
2015/06/24 09:49:54 [alert] 25098#0: *170971 open socket #38 left in connection 60
2015/06/24 09:49:54 [alert] 25098#0: aborting
```

but that didn't happen the second time I had to restart hhvm 3 hours later.

**Comment by tatsuhiro-t** [comment]
Quick googling shows that this is socket leak, and it sounds like nginx bug, but I'm not sure.

Have you observed any crash after 1.0.5 was deployed?

**Comment by 64616E69656C** [comment]
Not a bug per se, I guess restarting HHVM might have closed the waiting streams *through* nginx, so that's more likely an "info" rather than "alert" thing in this case (happened only one time out of four outages).

I still haven't deployed > 1.0.2 to the site in question yet, due to bad mood at the office - so I'm trying to avoid downtimes for now :-)
But I've got a few ideas how to reproduce and pin-point this, it might have something to do with nginx afterall, I will try on sunday. 
BTW: It would be nice to explicitly specify protocol usage (h2, h2-14, h2-16, spdy) in h2load without touching nghttpx' npn-list, looking at nghttp2_select_next_protocol() this should be possible?

**Comment by tatsuhiro-t** [comment]
Understood.  There is no rush.

> BTW: It would be nice to explicitly specify protocol usage (h2, h2-14, h2-16, spdy) in h2load without touching nghttpx' npn-list, looking at nghttp2_select_next_protocol() this should be possible?

Probably we need option to specify which ALPN ID to use.
FYI, in practice, most of the implementations treats h2-14 and h2-16 as h2.
