### ISSUE TITLE
Request without authority and host headers

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#266]
Hello,
I comment :authority header in source code for removing of the request HEADER and when I request without :authority header and not adding host header with -H option, the server response protocol error. I don't understand beacuse whe I read the RFC I understand that is possible and server has to get only path field for creating url
I don't know if it's possible.
Best regards

**Comment by tatsuhiro-t** [comment]
we need :authority or host header field.  http/1.1 semantics still applies here, we need host if :authority is missing.

**Comment by lespla** [comment]
1. Is it possible to run the server only http2 mode for not needing it?
2. I commnet authority header in source code and then I did the next request ant It doesn't work:
./nghttp -v -H':authority: http2.es' http://http2.es

**Comment by tatsuhiro-t** [comment]
1. No plan for that. Just supplying :authority is not much burden BTW.
2. That does not work.  If you commented out :authority, current code just append given :authority after the regular headers, which is a violation of HTTP/2 standard.
