### ISSUE TITLE
Submission of trailing headers precedes submitted data

### ISSUE THREAD

**Issue by lomnicky** [tatsuhiro-t/nghttp2#269]
When submitting a trailing HEADERS frame after data has been submitted, the HEADERS frame is sent before the data. If the frame contains and END_OF_STREAM flag, the DATA is discarded and, if content-length is given, HTTP error is raised and the stream is reset. 

This causes problems especially when implementing proxy, as the DATA may be pending due to flow-control conditions.

Induced with nghttp2 version 1.0.3.

**Comment by tatsuhiro-t** [comment]
trailer headers should be sent using nghttp2_submit_trailer() after DATA is completely sent.
The earliest point is inside nghttp2_data_source_read_callback, when both NGHTTP2_DATA_FLAG_EOF and NGHTTP2_DATA_FLAG_NO_END_STREAM flags set.

**Comment by lomnicky** [comment]
That's how I do it now, thanks.
