### ISSUE TITLE
Add variables to log TLS related information

### ISSUE THREAD

**Issue by tollmanz** [tatsuhiro-t/nghttp2#272]
I really like that nginx's SSL module allows you to log [TLS related variables](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#variables). All of the variables that nginx offers would be great, but I am most interested in the cipher suite and session ID variables. Thank you for considering this request!

**Comment by tatsuhiro-t** [comment]
This sounds interesting.  Let's start to add cipher suite and session ID, which I think rather easy ones.

**Comment by tollmanz** [comment]
Awesome! Thanks @tatsuhiro-t! I'd be happy to test code when you have it ready.

**Comment by tatsuhiro-t** [comment]
197493afd4551d1e874108b6978bc489a4ca69ce adds 3 log variables: $ssl_cipher, $ssl_protocol, and $ssl_session_id.  $ssl_protocol was added for my personal interest.

**Comment by tollmanz** [comment]
I compiled and installed 197493a, as well as updated my log format and this is working perfectly! Thanks a bunch, @tatsuhiro-t!

**Comment by tatsuhiro-t** [comment]
I close this issue for now.  If other specific SSL/TLS related variables are needed, please open issue for them.
