### ISSUE TITLE
where is nghttpx's config file

### ISSUE THREAD

**Issue by fourstring** [tatsuhiro-t/nghttp2#273]

**Comment by fourstring** [comment]
OS is ubuntu 14.04 LTS 64bit

**Comment by tatsuhiro-t** [comment]
Default lookup location is /etc/nghttpx/nghttpx.conf.
https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx--conf

**Comment by luckypoem** [comment]
hi.
i compiled nghttpx as follows:

git clone https://github.com/tatsuhiro-t/nghttp2
cd nghttp2
autoreconf -i
automake
autoconf
./configure
make
make install

but
root@133-130-58-26:~# ls /etc/nghttpx/
ls: cannot access /etc/nghttpx/: No such file or directory
root@133-130-58-26:~# ls /usr/local/nghttpx
ls: cannot access /usr/local/nghttpx: No such file or directory
root@133-130-58-26:~#

so for my case,where is nghttpx's config file?
tks

**Comment by fourstring** [comment]
@luckypoem 
You should write all config to a file,the name of the file is decided by yourself.
Then,use the commond:
nghttpx --config /path/to/config-file

**Comment by tatsuhiro-t** [comment]
What @fourstring said is correct.
A configuration file will not be created automatically.
You should create it by yourself.
The advantage to use default location /etc/nghttpx/nghttpx.conf is you can save --conf option.
