### ISSUE TITLE
The Problem with response.push->end(file_generator(filepath))

### ISSUE THREAD

**Issue by liuli9203** [tatsuhiro-t/nghttp2#274]
Hello, everyone！
I tried to write a push demo based on the libnghttp2_asio: High level HTTP/2 C++ library. However, when I try to run the server, the browser can get the pushed file from the cache but found to be empty, ie. the reponse is empty. Can anybody give me a hand ? Thank you so much.

<h4>This is my server.cpp:</h4>
------------------------------------------------------
#include using namespace nghttp2::asio_http2;
#include using namespace nghttp2::asio_http2::server;
int main(int argc, char * argv[])
{
 &nbsp;&nbsp;&nbsp;    boost::system::error_code ec;
 &nbsp;&nbsp;&nbsp;    http2 server;
 &nbsp;&nbsp;&nbsp;    server.handle("/", [](const request& req, const response& res)
 &nbsp;&nbsp;&nbsp;    {
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;  boost::system::error_code ec;
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;        auto push = res.push(ec,"GET", "/style.css");
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;        push->write_head(200);
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;        push->end(file_generator("style.css"));
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;        res.write_head(200);
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;        res.end(R"(<!DOCTYPE html>&lt;html lang="en"&gt;
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;                         &lt;body&gt;
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;  &nbsp;&nbsp;&nbsp;                         &lt;link href="/style.css" rel="stylesheet" type="text/css"&gt;
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;                          This should be green
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;                           &lt;body/&gt;&lt;html/&gt;)"
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;                      );
 &nbsp;&nbsp;&nbsp;     });

 &nbsp;&nbsp;&nbsp;      if(server.listen_and_serve(ec, "localhost", "3000"))
 &nbsp;&nbsp;&nbsp;      {
 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;           std::cerr<< "error:"<<ec.message() <<std::endl;
 &nbsp;&nbsp;&nbsp;       }
}

**Comment by tatsuhiro-t** [comment]
The possible reason is "style.css" is not in the current working directly this server was started.
Could you check the path to style.css?  Could you try to specify absolute path to style.css, and see how it works?

**Comment by liuli9203** [comment]
Thank you! It works
