### ISSUE TITLE
Add HTTP/2 framing layer information to HAR file

### ISSUE THREAD

**Issue by summerwind** [tatsuhiro-t/nghttp2#275]
Could you add the information of HTTP/2 frameing layer to HAR file of nghttp command?

I'm trying to analyze the effect of HTTP/2 prioritization. The `--har` option of nghttp is very usefull for me but there is no information of HTTP/2 framing layer. I'm glad if the information such as the following specification is included in the HAR file (Sorry! this spec is written in Japanese...).
https://gist.github.com/summerwind/e7d30eedbd1d02857a49

Thank you for considering this request!

**Comment by tatsuhiro-t** [comment]
Thank you for this proposal.  Will read the doc and post comment here.

**Comment by summerwind** [comment]
I implemented the code that extracts stream and frame information from nghttpd's log file.
So I'm going to close this issue. Thank you.

**Comment by tatsuhiro-t** [comment]
Sorry for getting done nothing about this.  At the same time,  grad to hear you have done yet another awesome job.
