### ISSUE TITLE
is it possible vhost?

### ISSUE THREAD

**Issue by redbox2000** [tatsuhiro-t/nghttp2#279]
hi there 
Is it　possible to multi-domain(vhost) settings and several different certs?

Best

**Comment by 64616E69656C** [comment]
Hi,

use
```
private-key-file=/etc/ssl/your-key.key
certificate-file=/etc/ssl/your-cert.crt
```
for your "main" vhost, and

```
subcert=/etc/ssl/sni-host1.key:/etc/ssl/sni-host1.crt
subcert=/etc/ssl/sni-host2.key:/etc/ssl/sni-host2.crt
```
each for your other vhosts.

in addition, I needed 
```
no-host-rewrite=yes
```
also for SNI, at least with nginx.

**Comment by redbox2000** [comment]
Daniel 
Thank you for the quick reply

I understand your explanation.

**Comment by 64616E69656C** [comment]
Hi,

I was able to pin this to mPDF+hhvm, so definitly no nghttpx issue.
