### ISSUE TITLE
How to restart nghttpx gracefully

### ISSUE THREAD

**Issue by fourstring** [tatsuhiro-t/nghttp2#282]
In nginx,we can
kill -HUP `cat /path/to/pid-file`
So, if there is such a manner analogous to restart nghttpx?
tatsuhiro-t said:
nghttpx uses 2 signals to restart nghttpx gracefully.
First send USR2 signal, which spawns new process. Then send QUIT to the old process, which kills it.
See https://nghttp2.org/documentation/nghttpx.1.html#signals and https://nghttp2.org/documentation/nghttpx-howto.html#hot-swapping

**Comment by tatsuhiro-t** [comment]
nghttpx uses 2 signals to restart nghttpx gracefully.
First send USR2 signal, which spawns new process.  Then send QUIT to the old process, which kills it.
See https://nghttp2.org/documentation/nghttpx.1.html#signals and https://nghttp2.org/documentation/nghttpx-howto.html#hot-swapping
