### ISSUE TITLE
Gracefull Restart Failed

### ISSUE THREAD

**Issue by fourstring** [tatsuhiro-t/nghttp2#283]
I restart nghttpx by following command:
kill -USR2 `cat /path/to/pid-file`
but:
root@localhost:~# kill -USR2 `cat /root/nghttpx.pid`
06/Jul/2015:21:45:29 +0800 PID4650 [NOTICE] Executing new binary
06/Jul/2015:21:45:29 +0800 PID4650 [ERROR] shrpx.cc:569 execve failed: errno=2
How to solve that?

**Comment by tatsuhiro-t** [comment]
See https://github.com/tatsuhiro-t/nghttp2/issues/280#issuecomment-118391574

**Comment by tatsuhiro-t** [comment]
I think the above link says the reason for failure.  Reopen if you still have this problem.
