### ISSUE TITLE
Promised stream is stuck

### ISSUE THREAD

**Issue by lomnicky** [tatsuhiro-t/nghttp2#285]
I have the following situation. I send GET request for a large resource with two more promised smaller resources. After the request is sent, I receive two PUSH_PROMISEs and than HEADERS of all three streams. After that, the main stream data is being sent. After the data is sent, data of one of the promised streams is sent. However, the data of the second promised stream never comes and the stream is not ended.

When I debug the code, I come into following state of the dependency tree. Lets say main stream is A, the two promised streams are B and C. A is TOP, B and C are REST. All of them have DATA to send. Items of A and B are also in ob_da_pq of the session. After last DATA frame of A is sent:
1. stream_update_dep_on_detach_item is called
2. stream_update_dep_set_top is called which changes B and C to TOP as they depend on A.
3. stream_update_dep_queue_top finds B and as it is already queued, returns without any action

After last DATA frame of B is sent:
1. stream_update_dep_on_detach_item is called
2. stream_update_dep_set_top has no effect as stream->dep_next is NULL. But, C is still TOP.
3. stream_update_dep_queue_top is NOT called as stream_update_dep_set_top returned 0
4. Main loop of session_mem_send_internal ends as nghttp2_session_pop_next_ob_item returns no items in queues of the session

In my opinion, C should be inspected as well and its data should be added back to the queue, but I am not sure whether I'm correct or not.

Thank you!

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.
I think I have fixed this in d6ca95a0c9f790a45ea682eccafdb12d8d19976e, which is available in nghttp2 1.0.5.
If you encountered this issue with 1.0.5, then there may be another bug in nghttp2.

**Comment by lomnicky** [comment]
Looks like it's working! I spent 3 days debugging your code until my head almost blew up. Thanx for saving it :)!

**Comment by tatsuhiro-t** [comment]
Priority handling is a bit complicated (so does the HTTP/2 spec)... but indeed happy to hear that the problem was solved.

**Comment by tatsuhiro-t** [comment]
Looks like the issue was solved.  Let's close the issue.
