### ISSUE TITLE
Local nghttpx TLS auth failed

### ISSUE THREAD

**Issue by fourstring** [tatsuhiro-t/nghttp2#286]
I use a .crt and a .pem file to auth,but:
shrpx_ssl.cc:755 Certificate verification failed: unable to get local issuer certificate
How to solve it?
Here is my config file:
daemon=yes
frontend=0.0.0.0,8080
backend=remote,443
client-proxy=yes
client-cert-file=/path/to/.crt
client-private-key-file=/rpath/to/.pem
workers=4
add-x-forwarded-for=no
no-via=yes
no-ocsp=yes
npn-list=h2

In fact,I use a .p12 file to auth,but nghttpx seems doesn't support it.

**Comment by tatsuhiro-t** [comment]
nghttpx does not support pkcs12 file.  Use openssl command to convert it to PEM format.
That said, I wonder what is the client-server configuration you are using.  Does nghttpx authenticate web browser?
Then you have to use verify-client and verify-client-cacert.
