### ISSUE TITLE
SNI backend mapping

### ISSUE THREAD

**Issue by StefanHamminga** [tatsuhiro-t/nghttp2#288]
I have a test setup working pretty well, I can use SNI to serve TLS + HTTP/2 on several domains and connect them over a UNIX socket to my (node.js) backend.
I would like to map my domains to different backends, if possible. I dug through the documentation and found no clear way how to do this.

I think adding a whitelist after a backend definition could be a simple way to configure this? Like:
```
backend=unix:/my/apps/app1/run/app.sock:example.com:www.example.com
backend=unix:/my/apps/app2/run/app.sock:www.othersite.com:www.test.com:test.com
# Fallback listens on any:
backend=unix:/my/apps/app2/run/app.sock
```

**Comment by tatsuhiro-t** [comment]
Choosing backend with SNI is very interesting.  Currently, nghttpx does not have the capability to forward request to backend based on server name presented by SNI.

**Comment by StefanHamminga** [comment]
I wish I had the talent to add it myself, but I simply don't have that (yet). Could you consider this as a feature request?
It would be great to be able to ditch NGINX completely for a HTTP/2 & push capable setup.

**Comment by tatsuhiro-t** [comment]
Yes, I'm interested in this idea.  Probably not so difficult, but will see.

**Comment by tatsuhiro-t** [comment]
It is probably better to use Host (or :authority header field in HTTP/2) instead of SNI server name.
This is because HTTP/2 will reuse the TLS connection, and issue the request with host header field other than SNI server name, if both host names resolve to the same IP (and, additionally they are covered by the same cert, but this may depend on client implementation).

**Comment by StefanHamminga** [comment]
Yes, I agree. For example, my SSL certificates (Comodo PositiveSSL) are are valid for both `www.somedomain.com` and `somedomain.com`. I have considered doing automatic (and free) domain sharding that way: Pick one as a primary host, use the alternative valid host to serve images and the like. For HTTP/1.x connections this would allow a single page application to keep a socket connection open while fetching additional resources with the proper caching from a GET request.

I have `no-host-rewrite` turned on and the correct hostnames already appear in Node, so whatever sets that, that is the value that would work for me.

**Comment by ameir** [comment]
I just got on GitHub to see if there were any active issues requesting different backends based on the Host: header field, and it looks like this is the one!  A big +1 for this feature.  We could also get rid of nginx in our stack if nghttpx were able to support host-header switching.

**Comment by tatsuhiro-t** [comment]
3119fc2 implements backend selection based on host header field and request path.
I slightly changed the syntax, it looks like this:
```
backend=127.0.0.1,8080;example.com:www.example.com
```
';' is used to separate host-port and patterns.
host and path matching is closely designed to ServeMux in Go programming language.
https://golang.org/pkg/net/http/#ServeMux

For example, to route request under `/httpbin/` to backend `127.0.0.1,8080`, you can write:
```
backend=127.0.0.1,8080;/httpbin/
```
To further limit the hostname to `www.nghttp2.org`, write like so:
```
backend=127.0.0.1,8080;www.nghttp2.org/httpbin/
```

Writing `nghttp2.org` is just a short hand of `nghttp2.org/`.

**Comment by ameir** [comment]
Awesome!  To clarify, if I want to set multiple backends for your example.com case, would the commandline args look like?:

```--backend=backend1,8080;example.com:www.example.com --backend=backend2,8080;example.com:www.example.com```

**Comment by StefanHamminga** [comment]
I'm impressed, quick work!

After building a fresh package I can confirm this working well for the two hosts I linked up to two backends.

ameir: My config file does exactly that, but I think you need to specify one last entry, a catch-all, like:

```
# Backends, second is fallback
backend=unix:/my/apps/cool-app/run/app.sock;cool-app.com
backend=unix:/my/apps/koa-hello-world/run/app.sock
```

**Comment by tatsuhiro-t** [comment]
Yes, current implementation requires the catch-all pattern.

**Comment by StefanHamminga** [comment]
Shall I close the issue for now, as this seems to be working well?

**Comment by tatsuhiro-t** [comment]
Yes.  If you have any issues, please create a new thread.  Thank you.

**Comment by StefanHamminga** [comment]
Thanks for the quick help in this!
