### ISSUE TITLE
Deprecate --no-host-rewrite option in nghttpx

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#290]
It looks like most users disable host rewrite using --no-host-rewrite on reverse proxy configuration, including default mode.  So I'd like to propose to deprecate --no-host-rewrite option, and make nghttpx not rewrite host header field for backend link by default.  The new --host-rewrite option will be added to rewrite host header field.

Some historical story about --no-host-rewrite option:
Initially, nghttpx did not rewrite host header field.  I added --no-host-rewrite option and make nghttpx rewrite host header by default, when I heard that some server demands host header field and must match its configured server name.  It looks like this is the default behavior of apache and nginx.

**Comment by 64616E69656C** [comment]
--no-host-rewrite is least an required option when using a single backend like nginx with SNI. So, I'd welcome this change.

**Comment by StefanHamminga** [comment]
I don't know if removing the option completely would be the way to go, but so far I've only used the `--no-host-rewrite` option, so I'd welcome the change in default behaviour.

**Comment by tatsuhiro-t** [comment]
Thank you for comments.  For the time being, we will issue warning message when --no-host-rewrite is used (and it is noop), so that nghttpx does not fail to start because of unknown option.

**Comment by tatsuhiro-t** [comment]
Fix committed via cab6c78.
Now host header is not rewritten by default.  --no-host-rewrite option was deprecated, and if it is used, warning message is displayed.  --host-rewrite option was added to rewrite host header field.
