### ISSUE TITLE
libnghttp2_asio build problems with -lssl/-lcrypto from a non-standard location

### ISSUE THREAD

**Issue by 64616E69656C** [tatsuhiro-t/nghttp2#291]
Hi,

I'm trying to build nghttp2-afl-flavour against libressl-afl and spdylay-afl, using the following configure options:
```
./configure \
  OPENSSL_LIBS="-L/opt/afl/libressl/lib -lssl -ltls -lcrypto" \
  OPENSSL_CFLAGS="-I/opt/afl/libressl/include" \
  LIBEVENT_OPENSSL_CFLAGS="-I/opt/afl/libressl/include" \
  LIBEVENT_OPENSSL_LIBS="-L/opt/afl/libressl/lib -lssl -ltls -lcrypto -levent -levent_openssl" \
  CFLAGS="-O2 -Wformat -Werror=format-security -g -fsanitize=address,undefined -Werror=array-bounds -Warray-bounds -Wstrict-prototypes" \
  CXXFLAGS="-O2 -Wformat -Werror=format-security -g -fsanitize=address,undefined -Werror=array-bounds -Warray-bounds -Wstrict-prototypes" \
  LDFLAGS="-Wl,--as-needed -Werror=format-security -fsanitize=address,undefined" \
  CC="afl-clang" CXX="afl-clang++" \
  AFL_USE_ASAN=1 \
  --prefix=/opt/afl/nghttp2 --with-libxml2 --with-jemalloc --with-spdylay=/opt/afl/spdylay --with-boost --enable-hpack-tools --enable-asio-lib
```

Then I get a few warnings from the linker like those:
```
/usr/bin/ld: warning: libssl.so.1.0.0, needed by ../src/.libs/libnghttp2_asio.so, may conflict with libssl.so.33
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by ../src/.libs/libnghttp2_asio.so, may conflict with libcrypto.so.34
```

libcrypto.so.1.0.0 belongs to openssl-1.0.2d-1. I think there's an option LIBASIO_LIBS / LIBASIO_CLFAGS needed, or am I missing something?

Thanks!

**Comment by tatsuhiro-t** [comment]
The thing is nghttp2 asio lib uses boost::ASIO, which is linked to the specific OpenSSL version (probably, OS default one).
To build nghttp2 asio lib with the chosen OpenSSL (or its forked) one, you have to build boost first with that SSL lib.  Please note that boost may not be built with genuine OpenSSL...

**Comment by 64616E69656C** [comment]
That's what I don't get, because boost::ASIO should not be linked to dist-openssl at all, since there is no libboost-asio. boost::ASIO headers are provided by libboost-all-dev -> libboost-dev -> libboost1.55-dev, which are just header files, so linking should be done on compliation? Or is the weather just too nice and it's telling me to GTFO? :-)

```
~ > for I in /usr/lib/x86_64-linux-gnu/libboost_*.so; do ldd $I; done|grep ssl
~ >
```

**Comment by tatsuhiro-t** [comment]
Ah, I missed the fact that boost asio is header only.  I'll look into it.

**Comment by tatsuhiro-t** [comment]
It looks like semi standard location is specified in linker flag by boost detection in configure before our custom OpenSSL flags.  So system installed OpenSSL got linked there.
Fix committed via 8a2543d

**Comment by 64616E69656C** [comment]
That did it, thanks!

**Comment by 0x64616E69656C** [comment]
Hi,

one more thing; I'm trying to build nghttp2 against boringssl (git-current), which fails with the following message:
```
nghttp.o: In function `nghttp2::HttpClient::initiate_connection()':
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/nghttp.cc:562: undefined reference to `SSL_ctrl'
nghttp.o: In function `nghttp2::main(int, char**)':
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/nghttp.cc:2480: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/nghttp.cc:2481: undefined reference to `OPENSSL_config'
nghttp.o: In function `nghttp2::(anonymous namespace)::communicate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nghttp2_data_provider*, long>, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, nghttp2_data_provider*, long> > >, nghttp2_session_callbacks const*)':
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/nghttp.cc:2036: undefined reference to `SSL_CTX_ctrl'
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/nghttp.cc:2037: undefined reference to `SSL_CTX_ctrl'
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/nghttp.cc:2038: undefined reference to `SSL_CTX_ctrl'
ssl.o: In function `nghttp2::ssl::get_tls_session_info(nghttp2::ssl::TLSSessionInfo*, ssl_st*)':
/home/daniel/code/nghttp2/nghttp2-1.3.4/src/ssl.cc:117: undefined reference to `SSL_ctrl'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The PORTING.md from boringssl has something about this:

```
### `*_ctrl` functions

Some OpenSSL APIs are implemented with `ioctl`-style functions such as
`SSL_ctrl` and `EVP_PKEY_CTX_ctrl`, combined with convenience macros, such as

    # define SSL_CTX_set_mode(ctx,op) \
            SSL_CTX_ctrl((ctx),SSL_CTRL_MODE,(op),NULL)

In BoringSSL, these macros have been replaced with proper functions. The
underlying `_ctrl` functions have been removed.

For convenience, `SSL_CTRL_*` values are retained as macros to `doesnt_exist` so
existing code which uses them (or the wrapper macros) in `#ifdef` expressions
will continue to function. However, the macros themselves will not work.

Switch any `*_ctrl` callers to the macro/function versions. This works in both
OpenSSL and BoringSSL. Note that BoringSSL's function versions will be
type-checked and may require more care with types.
```

Do you think it would be a nightmare to get this working, or would it even be a good idea to make nghttp2 compatible to non-OpenSSL libraries (libressl still works though)?

**Comment by 0x64616E69656C** [comment]
Build options:
```
OPENSSL_LIBS="-lcrypto -lssl -L/opt/boringssl/lib" \
LIBEVENT_OPENSSL_LIBS="-I/opt/boringssl/include" \
```

**Comment by tatsuhiro-t** [comment]
I have not tried to build nghttp2 with boringSSL yet.
Considering the fast that many projects now supports all OpenSSL, LibreSSL and BoringSSL family, I don't this it is very hard task.  Still need some time to study the differences from OpenSSL.

**Comment by 0x64616E69656C** [comment]
that would be awesome!

**Comment by tatsuhiro-t** [comment]
BTW, LIBEVENT_OPENSSL_LIBS is not used for source files under src.
{OPENSSL_CFLAGS="-I/opt/boringssl/include" should be used.
The error message indicates that openssl header files are used instead of boringSSL ones.

**Comment by 0x64616E69656C** [comment]
damn, I hoped you wouldn't notice :) 
([LIBEVENT_]OPENSSL_LIBS="-lssl -lcrypto -L/opt/boringssl/lib [LIBEVENT_]OPENSSL_CFLAGS="-I/opt/boringssl/include)

I'm still playing around with this, there are a few other issues with bssl I noticed when I tried to build openvpn against it, different approaches for example in ossl/safestack.h and bssl/stack_macros.h.
In nghttp2 there's 
```
shrpx_ssl.cc:177:30: error: use of undeclared identifier 'CRYPTO_malloc'
      static_cast<uint8_t *>(CRYPTO_malloc(data->size(), __FILE__, __LINE__));
                             ^
shrpx_ssl.cc:593:3: error: use of undeclared identifier 'SSL_CTX_set_tlsext_status_cb'
  SSL_CTX_set_tlsext_status_cb(ssl_ctx, ocsp_resp_cb);
  ^
```

CRYPTO_malloc has been replaced with OPENSSL_malloc in mem.h during google's cleanup of crypto.h.

SSL_CTX_set_tlsext_status_cb has been replaced by a proper SSL_CTX_set_ocsp_response, which makes it nearly impossible without switching between SSL_LIBRARY definitions or something. :-(

**Comment by tatsuhiro-t** [comment]
Yeah, we need `OPENSSL_IS_BORINGSSL` macro everywhere.
I just made successful compilation of applications under src directory.
I still need to fix the return value changes made in BoringSSL, which could be deadly in some cases.
Hopefully, I can push the changes in a few hours.

**Comment by 0x64616E69656C** [comment]
Wow! Unbelievable :) Can't wait to try it out, currently bssl has a few misaligned address issues in some of it's suites (e.g. poly1305 which is why I wanted to use it in the first place), also the server mode in bssl tool leaks quite some memory, but other than that it feels much more cozy than openssl.

**Comment by 0x64616E69656C** [comment]
btw, context for this approach is: 
https://www.zeitgeist.se/2014/08/23/optimize-aes-and-chacha20-usage-with-boringssl/

**Comment by tatsuhiro-t** [comment]
Thanks.  Let's continue the discussion at #373
