### ISSUE TITLE
support disambiguation of variable with curly braces in log-format string

### ISSUE THREAD

**Issue by difro** [tatsuhiro-t/nghttp2#295]
Currently there is no way to log variables followed by arbitrary string without any spaces in between.

For example, I'd like to append "ms" to $request_time variable, but can't do it without inserting a space or a special character in between $request_time and "ms".

Nginx supports disambiguating variable name with curly braces like this ```acceslog-format='${request_format}ms```

It'd be great if nghttp also supported such feature.

**Comment by tatsuhiro-t** [comment]
The suggested functionality was implemented in 7f7b6d6

**Comment by difro** [comment]
fix confirmed on v1.1.0. thanks!
