### ISSUE TITLE
SNI client verify and backend mapping

### ISSUE THREAD

**Issue by mustanonymous** [tatsuhiro-t/nghttp2#300]
Thank you for implement such a good software.

I want to run nghttpx with TLS at port 443 as both a proxy and a web server.

We assume the browser and nghttpx at different computers. www.example.com and proxy.example.com can be resolved to the same public ip in public DNS servers.
When the browser accessing https://www.example.com, I don't want nghttpx verify the client, and it forwards the requests to Apache (listening at a private ip and port 443,such as '10.1.1.1:443', I will write '10.1.1.1 www.example.com' to /etc/hosts ) at backend. So nghttpx looks like a web server.

When the browser use proxy.example.com as a http2 proxy, I want nghttpx verfiy the client(request client certification), and nghttpx forward the request to squid at backend.

I found the https://github.com/tatsuhiro-t/nghttp2/issues/292 is the most similar one. If I use this method, I must disable client verify in nghttpx, and use squid to authenticate. In this way, if someone test if my server is a proxy, he is sure to know that. 
I don't want them to know my server runs squid. So if they connect to my server with SNI 'proxy.example.com', I want them to show their client certification. In this way, if they have no client certification, they don't know what it is at backend. If they connect to my server with any other SNI or no SNI, just forward to Apache.

I have thought this idea for several days, and I tried to implement this, but I failed. I think I am not able to do that.

I wish you could implement this. If you think my idea useless, I thank you all the same.
Thank you again for implement such a good software.

**Comment by tatsuhiro-t** [comment]
If you can run proxy in different port (e.g., 8080), then it is pretty much possible with the current implementation.  Web server and forward proxy have different usage scenario, and user with certificate knows the port the proxy is running, and they can point their browser to that endpoint easily.
nghttpx instances can have its own configuration files, so you can just enable client certificate for proxy instance only.

**Comment by mustanonymous** [comment]
Thank you for your quick response.
What I think is that if GFW(China Great Firewall) knows our server runs as a proxy, it may block the server's IP. So I want to cheat it. If the traffic looks like the normal https traffic, it would be great.

Thanks all the same.

**Comment by mustanonymous** [comment]
I have no other to say. So once you have decided, you can close this issue.
Thank you very much.

**Comment by tatsuhiro-t** [comment]
It looks like haproxy can direct connection from client to backend based on SNI.  I've never used it, so don't know how to do that, but you can do google search to find out.
http://blog.haproxy.com/2012/04/13/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/

**Comment by mustanonymous** [comment]
Thank you very much. I solved the problem.
Haproxy is the frontend, nghttpx is in the middle, Apache and squid is in the backend.
They work perfect!

**Comment by mustanonymous** [comment]
I have implemented this issue at https://github.com/mustanonymous/nghttp2/commit/533a0a70cc1bb78c0d991fd024dfa4c01b325c87 . But its hard codede, and I changed some url rewriting. So I will not create a PR. 
Thank you for your code.
