### ISSUE TITLE
Can't proxy http sites in <FF37

### ISSUE THREAD

**Issue by yegors** [tatsuhiro-t/nghttp2#301]
Im running nghtpx in proxy mode + squid as a backend.

In FF36 and below, Im not able to load http sites. https works fine. 

Firefox just says "The connection was interrupted".

Error log:

>:host: checkip.dyndns.com
:method: GET
:path: http://checkip.dyndns.com/
:scheme: http
:version: HTTP/1.1
accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
accept-language: en-US,en;q=0.5
cache-control: max-age=0
proxy-authorization: Basic dGVzdHVzZXI6dGVzdA==
user-agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

>16/Jul/2015:20:07:10 +0000 PID11624 [INFO] shrpx_spdy_upstream.cc:733 [UPSTREAM:0x7fd3ea0904e0] RST_STREAM stream_id=1
16/Jul/2015:20:07:10 +0000 PID11624 [INFO] shrpx_spdy_upstream.cc:92 [UPSTREAM:0x7fd3ea0904e0] Stream stream_id=1 is being closed
16/Jul/2015:20:07:10 +0000 PID11624 [INFO] shrpx_downstream.cc:152 [DOWNSTREAM:0x7fd3ea093800] Deleting
16/Jul/2015:20:07:10 +0000 PID11624 [INFO] shrpx_downstream.cc:170 [DOWNSTREAM:0x7fd3ea093800] Deleted
16/Jul/2015:20:07:10 +0000 PID11624 [INFO] shrpx_client_handler.cc:397 [CLIENT_HANDLER:0x7fd3ea136000] Deleting
16/Jul/2015:20:07:10 +0000 PID11624 [INFO] shrpx_client_handler.cc:420 [CLIENT_HANDLER:0x7fd3ea136000] Deleted
`

Upgrading to FF37+ solves the issue, but I'm trying to support older clients as well.

**Comment by yegors** [comment]
I was originally using 1.0.5, and then upgraded to 1.1.1. Behavior was the same. Downgraded to 0.7.5, and it started working. 

Any way to get it to work in the latest version, as running a 2nd, outdated instance to serve legacy clients is a bit ghetto.

**Comment by tatsuhiro-t** [comment]
I think this is a good incentive for users who use outdated browser to upgrade it.
HTTP/2 proxy feature in Firefox is relatively new, and it has many bugs fixed in recent release, so users should use latest version.  I don't argue about any particular bugs or security holes in older releases because I have not followed commits, but in general, latest stable should be safest and most reliable, and using insecure browser defeats the purpose of "secure" proxy.

**Comment by yegors** [comment]
I completely agree with you from an idealistic perspective. Everyone SHOULD run the latest version of FF, however some people are are in "enterprise environments" where updates are not up to them, and you can't force them to do it, even if the user wanted to. 

In 0.7.5, it works perfectly all the way from FF33, where HTTPS proxies were added, and negotiates the tunnel over spdy/3.1. So there is nothing wrong with it from a security standpoint. 

So in order to support legacy clients I currently have 2 options: Run 0.7.5 in parallel with 1.1.1, or run 2 instances of 1.1.1, with the legacy one only using http/1.1 in the npn-list (which is actually insecure). 

Would be great to have the <FF37 workaround be in the latest version, especially since there was support for it before.

All that being said, really appreciate the work you did with nghttp2. Really excellent stuff!

**Comment by tatsuhiro-t** [comment]
I completely agree we are not living in ideal world.  If we are in that world, you don't need HTTP/2 proxy for the first place, do you?
I'm afraid to say there is no workaround for this for older Firefox.  I reported several bugs to Firefox developers, and some of the bugs are not apparent in just few minutes of browsing.  But in the end, it just freezes or crashes Firefox.
I think you can use http/1.1 in HTTPS for <FF37, which is secure, but just inefficient.

**Comment by yegors** [comment]
According to this:

https://www.igvita.com/2011/12/01/web-vpn-secure-proxies-with-spdy-chrome/

"the original CONNECT handshake (in green), alongside the host and the port of the destination is sent in clear text. Even worse, the proxy authentication (if any) is also running over the same insecure channel"

Wouldn't using http/1.1 protocol, even over HTTPS suffer from these issues?

**Comment by tatsuhiro-t** [comment]
No. It describes traditional proxy, where connection is made over clear text TCP.  We connect to the proxy over TLS, so it does not apply.
