### ISSUE TITLE
nghttp2 hardened build w/ clang

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#307]
Hi,

I noticed that neither clang-3.5.2 (AFL_HARDEN=1 -D_FORTIFY_SOURCE=2) nor clang-3.6 (-D_FORTIFY_SOURCE=2) builds nghttpx with fortified functions. 
Is this a bug, a feature, a false positive, LLVM incompatibility or is it just me? Thanks :)

```
deflatehd:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
 Read-only relocations: yes
 Immediate binding: yes
h2load:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes
 Read-only relocations: yes
 Immediate binding: yes
inflatehd:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes
 Read-only relocations: yes
 Immediate binding: yes
nghttp:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: unknown, no protectable libc functions used
 Read-only relocations: yes
 Immediate binding: yes
nghttpd:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: unknown, no protectable libc functions used
 Read-only relocations: yes
 Immediate binding: yes
nghttpx:
 Position Independent Executable: yes
 Stack protected: yes
 **Fortify Source functions: no, only unprotected functions found!**
 Read-only relocations: yes
 Immediate binding: yes
```

**Comment by tatsuhiro-t** [comment]
How to reproduce this output?
I compiled nghttp2 source code with clang-3.6 CPPFLAGS=-D_FORTIFY_SOURCE=2, but it just compiled fine.

**Comment by tatsuhiro-t** [comment]
Got it, that is hardening-check

**Comment by 64616E69656C** [comment]
Yes, forgot to mention the output's from hardening-check. Lintian complians about this.

**Comment by tatsuhiro-t** [comment]
Thanks.  I could reproduce this with the following configure option:
```
./configure CC=clang-3.6 CXX=clang++-3.6 CPPFLAGS="-D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -fPIE -fstack-protector-strong" LDFLAGS="-Wl,-z,relro -Wl,-z,now -fPIE -pie"
```

**Comment by tatsuhiro-t** [comment]
With clang-3.6, I got same result with yours.  With gcc 4.9, I got following:
```
src/.libs/nghttpx:
 Position Independent Executable: yes
 Stack protected: yes
 Fortify Source functions: yes (some protected functions found)
	unprotected: memset
	unprotected: read
	unprotected: memcpy
	unprotected: memmove
	unprotected: getcwd
	protected: syslog
	protected: snprintf
	protected: memcpy
	protected: fprintf
 Read-only relocations: yes
 Immediate binding: yes
```

This is a bit strange, since memcpy is both protected and unprotected.
I don't know much about fortify source, but does this come from false positive, or outcome of aggressive optimization?

**Comment by 64616E69656C** [comment]
-O2 was used as always. Interesting though that gcc fortifies at least a few functions. Guess clang goes all in or nothing.

**Comment by tatsuhiro-t** [comment]
How do we proceed from here? Assume you are creating debian package, Google search shows people complain about false positives from Lintian.

**Comment by 64616E69656C** [comment]
I'll take a closer look at this, and see if I can get something more verbose about this. Just wasn't sure if this a well known false positive or if i'm just breaking things.

**Comment by 0x64616E69656C** [comment]
Gonna close this one too, also haven't really gotten  around this yet :/
