### ISSUE TITLE
nghttpx: Sharing SSL/TLS session resumption data (e.g., ticket key) using external source (e.g., memcached)

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#308]
Is there anyone interested in adding a feature to share SSL/TLS session resumption data (e.g., ticket key) among nghttpx clusters via external source (e.g., memcached)?

Currently, nghttpx supports both session id cache and session tickets.  For the latter, nghttpx rotates ticket key automatically.  They are shared inside one nghttpx instance, in other words, multiple worker threads can share these information.  nghttpx supports reading ticket key from file, much like apache and nginx does, and using that file, multiple nghttpx instances share ticket keys.

I myself only use single nghttpx instance (my vps is not much goofy), so I myself has no immediate requirement of multiple nghttpx instance configuration, sharing SSL/TLS session resumption information.

If someone is interested in this, we can talk about how to achieve this.

**Comment by tatsuhiro-t** [comment]
It seems no one is interested in this, but I'm.
I started session cache resumption first in https://github.com/tatsuhiro-t/nghttp2/tree/memcached branch.
It uses same trick invented by kazuho in h2o project, and it enables asynchronous session cache lookup using external memcached server.  Current implementation uses memcached binary protocol.

I'll continue to work on it, and add ticket key sharing.  Current plan is that ticket key must be generated by  external source.  nghttpx just periodically (~10min?) checks memcached for session ticket, and applies to its own session key store.

**Comment by tatsuhiro-t** [comment]
Now merged and available in master branch

**Comment by 0x64616E69656C** [comment]
Hi,

I was playing around with 
```
tls-ticket-key-cipher=aes-256-cbc
tls-ticket-key-memcached=127.0.0.1,11211
tls-session-cache-memcached=127.0.0.1,11211
```

tls-ticket-key-cipher adds a few ms to TTTFB, another few ms are added by tls-ticket-key-memcached, but I noticed a quite heavy slowdown when using tls-session-cache-memcached (resulting in FastCGI timeouts on hiawatha with the default 5s timeout setting). First I though, this was hiawatha, but I confirmed this with nginx. Can you confirm that, or "am I doing it wrong"?

**Comment by tatsuhiro-t** [comment]
I checked these parameters with h2load's "time to 1st byte" report, but not much difference without them.
I'm a bit curious because these parameters affect TLS handshake on frontend connection, which means no request is handed out to backend nginx, so there should be no timeout there.

**Comment by 0x64616E69656C** [comment]
Hi,

Initially I was just clicking through with chrome, so now I added a few tests with h2load:


### dedicated fuzzing server 

> **h2load -t16 -c20 -n10000 https://host.name/test.php**


> **third place**
> tls-ticket-key-cipher=aes-256-cbc
> tls-ticket-key-memcached=127.0.0.1,11211
> tls-session-cache-memcached=127.0.0.1,11211

```
finished in 1.31s, 7609 req/s, 1.28MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 1758682 bytes total, 136876 bytes headers, 1440000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      913us     12.22ms      2.12ms       628us    67.70%
time for connect:     8.27ms     18.41ms     13.88ms      2.74ms    60.00%
time to 1st byte:     8.37ms     18.48ms     13.00ms      2.79ms    60.00%
```


> **winner**
> tls-ticket-key-cipher=aes-256-cbc
> tls-ticket-key-memcached=127.0.0.1,11211

```
finished in 1.30s, 7668.44 req/s, 1.29MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 1759160 bytes total, 137336 bytes headers, 1440000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      928us      4.88ms      2.10ms       582us    63.95%
time for connect:     9.05ms     21.39ms     14.70ms      3.30ms    65.00%
time to 1st byte:     9.12ms     21.45ms     14.80ms      3.31ms    65.00%
```

> **slowest option**
> tls-ticket-key-cipher=aes-256-cbc 

```
finished in 1.32s, 7581.06 req/s, 1.27MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 1758671 bytes total, 136991 bytes headers, 1440000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      914us      6.05ms      2.12ms       587us    65.21%
time for connect:     9.62ms     28.20ms     17.80ms      4.84ms    75.00%
time to 1st byte:     9.69ms     28.26ms     17.91ms      4.83ms    75.00%
```


> **second place**
> [none] 

```
finished in 1.31s, 7639.93 req/s, 1.28MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 1758907 bytes total, 136876 bytes headers, 1440000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      935us     16.24ms      2.11ms       605us    66.21%
time for connect:     8.79ms     22.80ms     15.96ms      4.11ms    60.00%
time to 1st byte:     8.88ms     22.94ms     16.04ms      4.11ms    60.00%
```

--- 

### single CPU / 4GB RAM web-dev machine hitting the start page:

> h2load -c10 -n1000 https://dev-site/folder/

> **slowest option**
> tls-ticket-key-cipher=aes-256-cbc
> tls-ticket-key-memcached=127.0.0.1,11211
> tls-session-cache-memcached=127.0.0.1,11211

```
finished in 39.32s, 25.4304 req/s, 1.77MB/s
requests: 1000 total, 1000 started, 1000 done, 1000 succeeded, 0 failed, 0 errored
status codes: 1000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 73096176 bytes total, 129016 bytes headers, 72894905 bytes data
                     min         max         mean         sd        +/- sd
time for request:   161.07ms    636.82ms    391.25ms     45.77ms    87.20%
time for connect:    23.30ms     57.46ms     39.08ms     14.05ms    40.00%
time to 1st byte:    24.55ms     57.60ms     40.89ms     13.96ms    40.00%
```

> **third place**
> tls-ticket-key-cipher=aes-256-cbc
> tls-ticket-key-memcached=127.0.0.1,11211

```
finished in 38.42s, 26.0307 req/s, 1.81MB/s
requests: 1000 total, 1000 started, 1000 done, 1000 succeeded, 0 failed, 0 errored
status codes: 1000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 73107961 bytes total, 128699 bytes headers, 72907007 bytes data
                     min         max         mean         sd        +/- sd
time for request:   149.82ms    660.15ms    382.22ms     33.13ms    93.50%
time for connect:    29.37ms     55.81ms     38.52ms      9.57ms    80.00%
time to 1st byte:    30.75ms     59.74ms     40.82ms     10.78ms    70.00%
```

> **second place**
> tls-ticket-key-cipher=aes-256-cbc

```
finished in 38.09s, 26.2566 req/s, 1.83MB/s
requests: 1000 total, 1000 started, 1000 done, 1000 succeeded, 0 failed, 0 errored
status codes: 1000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 73092364 bytes total, 128712 bytes headers, 72891388 bytes data
                     min         max         mean         sd        +/- sd
time for request:   162.53ms    649.70ms    378.89ms     28.79ms    94.60%
time for connect:    19.98ms     74.99ms     41.40ms     16.96ms    50.00%
time to 1st byte:    20.09ms     76.01ms     48.94ms     21.56ms    40.00%
```

> **winner**
> [none]

```
finished in 37.93s, 26.364 req/s, 1.84MB/s
requests: 1000 total, 1000 started, 1000 done, 1000 succeeded, 0 failed, 0 errored
status codes: 1000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 73098392 bytes total, 128610 bytes headers, 72897527 bytes data
                     min         max         mean         sd        +/- sd
time for request:   149.49ms    627.52ms    377.13ms     30.55ms    93.00%
time for connect:     5.28ms     55.79ms     32.89ms     16.66ms    50.00%
time to 1st byte:    38.13ms     55.87ms     41.71ms      6.44ms    80.00%
```

---

### Conclusion

The results from the fuzzing server are as to be expected. Encryption takes CPU, so it slows down the page a little, but adding memcached for storing the session and tickets in favour of file i/o speeds the whole thing back up.

The results from the tiny single-core/4G RAM machine are weird. Slowdown by adding encryption to tickets are as well to be expected, I'm even wondering why it's not *that* significant. But the slowdown by each memcached options was unexpected.
Guess this is hardware/kernel/hyper-v related.

**Comment by tatsuhiro-t** [comment]
There parameters only affects TLS handshake.  In the above tests, we use -c20 or -c10, so 20 or 10 TLS handshake.  Rest of the traffic is not affected at all; because of h2load's behaviour, it does not utilize resumption at all.

Maybe I'm missing something, but the test results are very close to each other; not much difference between them.  I agree that aes-256-cbc against aes-128-cbc increases CPU usage, but I'm not sure how much.  I also point out that with --tls-session-cache-memcached, nghttpx will cache session to memcached, and also caches it internal memory.  Unless internal memory cache is expired, it is directly pulled without touching memcached.  But since h2load does not use resumption, this part of the code is not executed in the test run.  For --tls-ticket-key-memcached, we have to make sure that external key generator program (example one is under contrib/tlsticketupdate.go) is required to store ticket keys to memcached.  Without that, nghttpx could not find keys from memcached, and it simply disables ticket based TLS resumption.  But again, resumption is not used in h2load..
