### ISSUE TITLE
Failed to build from git

### ISSUE THREAD

**Issue by zhenyu-zhou** [tatsuhiro-t/nghttp2#310]
Hello,

I'm trying to compile nghttp2. However, I met the following error msg while compiling:

make[3]: Entering directory '/users/zzy/nghttp2/src'
  CXX    shrpx_config.o
In file included from shrpx_ssl.h:31:0,
                 from shrpx_config.cc:55:
/usr/include/c++/4.8/mutex:206:13: error: 'monotonic_clock' in namespace 'std::chrono' does not name a type
     typedef chrono::steady_clock     __clock_t;
             ^
/usr/include/c++/4.8/mutex:274:45: error: wrong number of template arguments (1, should be 2)
  ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                             ^
In file included from /usr/include/c++/4.8/chrono:38:0,
                 from shrpx_log.h:35,
                 from shrpx.h:39,
                 from shrpx_config.h:28,
                 from shrpx_config.cc:25:
/usr/include/c++/4.8/ratio:388:12: error: provided for 'template<class _R1, class _R2> struct std::ratio_less_equal'
     struct ratio_less_equal
            ^
In file included from shrpx_ssl.h:31:0,
                 from shrpx_config.cc:55:
/usr/include/c++/4.8/mutex:274:59: error: template argument 1 is invalid
  ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                                           ^
/usr/include/c++/4.8/mutex:285:46: error: wrong number of template arguments (1, should be 2)
  !ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                              ^
In file included from /usr/include/c++/4.8/chrono:38:0,
                 from shrpx_log.h:35,
                 from shrpx.h:39,
                 from shrpx_config.h:28,
                 from shrpx_config.cc:25:
/usr/include/c++/4.8/ratio:388:12: error: provided for 'template<class _R1, class _R2> struct std::ratio_less_equal'
     struct ratio_less_equal
            ^
In file included from shrpx_ssl.h:31:0,
                 from shrpx_config.cc:55:
/usr/include/c++/4.8/mutex:285:60: error: template argument 1 is invalid
  !ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                                            ^
/usr/include/c++/4.8/mutex:286:7: error: 'template<class _Rep, class _Period> in
t std::timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)' cannot be overloaded
       __try_lock_for_impl(const chrono::duration<_Rep, _Period>& __rtime)
       ^
/usr/include/c++/4.8/mutex:275:7: error: with 'template<class _Rep, class _Period> int std::timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)'
       __try_lock_for_impl(const chrono::duration<_Rep, _Period>& __rtime)
       ^
/usr/include/c++/4.8/mutex: In member function 'int std::timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)':
/usr/include/c++/4.8/mutex:277:24: error: expected initializer before '__atime'
  __clock_t::time_point __atime = __clock_t::now()
                        ^
/usr/include/c++/4.8/mutex:280:24: error: '__atime' was not declared in this scope
  return try_lock_until(__atime);
                        ^
/usr/include/c++/4.8/mutex: In member function 'int std::timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)':
/usr/include/c++/4.8/mutex:288:24: error: expected initializer before '__atime'
  __clock_t::time_point __atime = __clock_t::now()
                        ^
/usr/include/c++/4.8/mutex:291:24: error: '__atime' was not declared in this scope
  return try_lock_until(__atime);
                        ^
/usr/include/c++/4.8/mutex: At global scope:
/usr/include/c++/4.8/mutex:299:13: error: 'monotonic_clock' in namespace 'std::chrono' does not name a type
     typedef chrono::steady_clock   __clock_t;
             ^
/usr/include/c++/4.8/mutex:367:45: error: wrong number of template arguments (1, should be 2)
  ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                             ^
In file included from /usr/include/c++/4.8/chrono:38:0,
                 from shrpx_log.h:35,
                 from shrpx.h:39,
                 from shrpx_config.h:28,
                 from shrpx_config.cc:25:
/usr/include/c++/4.8/ratio:388:12: error: provided for 'template<class _R1, class _R2> struct std::ratio_less_equal'
     struct ratio_less_equal
            ^
In file included from shrpx_ssl.h:31:0,
                 from shrpx_config.cc:55:
/usr/include/c++/4.8/mutex:367:59: error: template argument 1 is invalid
  ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                                           ^
/usr/include/c++/4.8/mutex:378:46: error: wrong number of template arguments (1, should be 2)
  !ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                              ^
In file included from /usr/include/c++/4.8/chrono:38:0,
                 from shrpx_log.h:35,
                 from shrpx.h:39,
                 from shrpx_config.h:28,
                 from shrpx_config.cc:25:
/usr/include/c++/4.8/ratio:388:12: error: provided for 'template<class _R1, class _R2> struct std::ratio_less_equal'
     struct ratio_less_equal
            ^
In file included from shrpx_ssl.h:31:0,
                 from shrpx_config.cc:55:
/usr/include/c++/4.8/mutex:378:60: error: template argument 1 is invalid
  !ratio_less_equal<__clock_t::period, _Period>::value, bool>::type
                                                            ^
/usr/include/c++/4.8/mutex:379:7: error: 'template<class _Rep, class _Period> in
t std::recursive_timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)' cannot be overloaded
       __try_lock_for_impl(const chrono::duration<_Rep, _Period>& __rtime)
       ^
/usr/include/c++/4.8/mutex:368:7: error: with 'template<class _Rep, class _Period> int std::recursive_timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)'
       __try_lock_for_impl(const chrono::duration<_Rep, _Period>& __rtime)
       ^
/usr/include/c++/4.8/mutex: In member function 'int std::recursive_timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)':
/usr/include/c++/4.8/mutex:370:24: error: expected initializer before '__atime'
  __clock_t::time_point __atime = __clock_t::now()
                        ^
/usr/include/c++/4.8/mutex:373:24: error: '__atime' was not declared in this scope
  return try_lock_until(__atime);
                        ^
/usr/include/c++/4.8/mutex: In member function 'int std::recursive_timed_mutex::__try_lock_for_impl(const std::chrono::duration<_Rep1, _Period1>&)':
/usr/include/c++/4.8/mutex:381:24: error: expected initializer before '__atime'
  __clock_t::time_point __atime = __clock_t::now()
                        ^
/usr/include/c++/4.8/mutex:384:24: error: '__atime' was not declared in this scope
  return try_lock_until(__atime);
                        ^
make[3]: *** [shrpx_config.o] Error 1
make[3]: Leaving directory `/users/zzy/nghttp2/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/users/zzy/nghttp2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/users/zzy/nghttp2'
make: *** [all] Error 2

I have run the following commands as the tutorial suggested:
1. sudo apt-get install make binutils autoconf  automake autotools-dev libtool pkg-config \
  zlib1g-dev libcunit1-dev libssl-dev libxml2-dev libev-dev libevent-dev libjansson-dev \
  libjemalloc-dev cython (without python3.4-dev because it cannot be resolved)
2. $ autoreconf -i
$ automake
$ autoconf
$ ./configure
$ make

And the compiler version is showed below:
zzy@node0:~ % gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

zzy@node0:~ % g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

I have also tried gcc-4.9/g++-4.9. The error msg is similar. The OS is:
zzy@node0:~ % lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

Any idea to figure this out?

Many thanks!!

Zhenyu

**Comment by tatsuhiro-t** [comment]
Compiler version looks good. With gcc >= 4.8, std::chrono::steady_clock should be available.
I'm curious what config.log contains after "checking whether std::chrono::steady_clock is available."
If the check is failed, we use std::chrono::monotonic_clock instead of std::chrono::steady_clock.
std::chrono::monotonic_clock is pre-standard name, which gcc 4.6 was used back then.
Now I think gcc 4.6 cannot compile C++11 code in nghttp2, we can just remove this check altogether.
What you get if you apply the following patch?
```diff
diff --git a/src/nghttp2_config.h b/src/nghttp2_config.h
index 9dede35..7fbd365 100644
--- a/src/nghttp2_config.h
+++ b/src/nghttp2_config.h
@@ -29,10 +29,4 @@
 #include <config.h>
 #endif // HAVE_CONFIG_H
 
-// gcc 4.6 has std::chrono::monotonic_clock, which was renamed as
-// std::chrono::steady_clock in C++11 standard.
-#ifndef HAVE_STEADY_CLOCK
-#define steady_clock monotonic_clock
-#endif // !HAVE_STEADY_CLOCK
-
 #endif // NGHTTP2_CONFIG_H
```

**Comment by zhenyu-zhou** [comment]
Fantastic it works!! Thank you so much!!

One more question about set up the server (maybe in general for HTTPS connections): should I make a valid certificate for every server? I tried to use the one from my another server (nghttp2 works well there) but it doesn't work. At client side, I got "ERR_CONNECTION_RESET". At server side, it shows:
IPv4: listen 0.0.0.0:8080
IPv6: listen :::8080
[id=1] [  6.117] closed

I guess it's because of the domain name inside certificate can only match the original server. Is this understanding correct? (I just start to build HTTPS server and indeed know little about certificates.)

Thanks again!

**Comment by tatsuhiro-t** [comment]
> I guess it's because of the domain name inside certificate can only match the original server. Is this understanding correct? (I just start to build HTTPS server and indeed know little about certificates.)

Yes, TLS requires that.  A certificate can cover multiple host names if you want.
For test server (i.e., just used as experiment for limited parties and/or limited time), self signed could do the job (and probably you have to persuade browser to accept invalid certificate, which itself is insecure in general), but if you do some services, you should get valid certificate (which costs some money at the moment), without that, user won't trust your service.

**Comment by zhenyu-zhou** [comment]
Great I got it! Thanks a ton for your patient help!

**Comment by tatsuhiro-t** [comment]
Great, let's close the issue.
