### ISSUE TITLE
nghttpx with tsocks

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#313]
Hi Tatsuhiro,

As part of my work I have returned to an old test VM and updated it to use nghttp2 1.1.3-DEV (from 0.6). 

In this VM I had nghttpx connecting to the backend via SOCKS using tsocks .e.g `tsocks nghttpx --backend='example.com,80' --frontend='192.168.56.101,80' --frontend-no-tls`.

Before updating, clients would make requests and get 200 responses. Now with v1.1.3-DEV I only see 502 (Bad Gateway) responses. I wondered if any of the changes introduced in the meantime may have affected how tsocks works with nghttpx.

I'm not ruling out other possible causes but I've tested my use of tsocks with other applications and they function ok. Looking at a packet trace it appears that nghttpx does not negotiate the SOCKS connection properly, resulting in a failure and ultimately the 502.

**Comment by tatsuhiro-t** [comment]
0.6 uses libevent to connect to backend server.  Now we do it by ourselves, and use connect() syscall, which I think tsock will replace it dynamically, and do the SOCKS handshake.  If that is the only thing tsock does, then I think current version should work too.
Before passing to connect(), we make file descriptor nonblock-ing, close-on-exec, and nodelay flags set.  I don't know libevent does this, so this might be the difference between the releases.

I'd like to setup socks server in my PC.  Which program should I install to reproduce this issue?

**Comment by LPardue** [comment]
I don't have direct access to the SOCKS server so I don't know what software is in use sorry . On the client side I am using tsocks 1.8 from yum repositories. I am using SOCKSv5 and my /etc/tsocks.conf file is like 

`server = [server IP]
server_type = 5
server_port = 1080`

**Comment by tatsuhiro-t** [comment]
Thank you.  I found dante socks server.  I'll try to reproduce this using dante.

**Comment by tatsuhiro-t** [comment]
Tried tsocks and dante server.  They works fine with nghttpx with none method (which probably means no authentication).
But if I set server_type to 5, connection was failed. This is not limited to nghttpx. Connecting to nginx directly also failed, so there must be some additional configuration necessary in danted.

**Comment by tatsuhiro-t** [comment]
It turns out that if I used dante client (socksify), socks 5 just works with latest nghttpx.
When tsocks with socks 5 was used, dante server logged "socks protocol error."

**Comment by LPardue** [comment]
Thanks for looking at this! I will test my set up with socksify on Monday and let you know.

**Comment by LPardue** [comment]
I'm testing with socksify but my knowledge of this tool is minimal. I think I have an issue with my /etc/socks.conf because when I attempt to launch nghttpx I see 

```
    [WARN] shrpx.cc363 bind() syscall failed, error=98
    [WARN] shrpx.cc:379 Listening IPv4 socket failed
    [FATAL] shrpx.cc:741 Failed to listen on address 192.168.56.101, port 80 
````
What is the format of your client configuration?

**Comment by tatsuhiro-t** [comment]
dante socks server listens on 127.0.0.1:1080.  My client side dante.conf is like so:
```
route {
        from: 0.0.0.0/0 to: 0.0.0.0/0 via: 127.0.0.1 port = 1080
        proxyprotocol: socks_v5
        protocol: tcp udp
        method: none
}
```

I have to tell you that my socks knowledge is very scarce too.

**Comment by LPardue** [comment]
So with socksify it looks like my local machine is attempting to bind the nghttpx frontend on the external SOCKS server, rather than the local interface I requested. The server rejects this and I get an error. I wonder if your local SOCKS server means that you don't see my issues.

If I enable debug in socksify 
```
    logoutput: socks.log
    debug: 2
```` 
it prints 
`lt-nghttpx[21276]: info: Rbind(): proxyserver did not let us bind the requested port, 80. Proxyserver offered us instead port 63166, so failing`

**Comment by tatsuhiro-t** [comment]
I misunderstood the situation, and my first attempt was use socksify to client (e.g. curl), and socks server between that client and nghttpx:
```
socksify [client] <----> [dante(socks)] <----> [nghttpx] <----> [web server]
```

Reading your posts carefully, the problem arises when socksify nghttpx:
```
[client] <----> socksify [nghttpx] <----> [dante(socks)] <----> [web server]
```

So I did the second setup.  Although I could not get the error you described, the connection between nghttpx and web server seems to be established via dante, but that event was not raised in epoll() in nghttpx.  In old-school non-blocking socket programming, calling connect() with non-blocking file descriptor will return EINPROGRESS, and we check the connection establishment by checking its writability using epoll (or select, or something).  When used with socksify, writability never get notified in ngttpx process.  We just got 504 gateway timeout eventually.
I'm very curious because curl somehow does workaround this problem.

**Comment by LPardue** [comment]
Apologies for the confusion here. Your second diagram is logically similar to my setup, the main difference is that the socks server and web server are both different physical hosts.

With some assistance I have investigated my issues, it relates to a mis-configuration of socksify client where we allow it to attempt the invalid bind. We added a rule to the client config (at the top of the file) that enforces bind operations to take place locally:

```
   route {
     from: 0.0.0.0/0 to: 0.0.0.0/0 via:direct
     command: bind
   }
```

With that fix in place, I then start to see 504's in my test client. Packet tracing this, I never see nghttpx issue the HTTP GET. I now think we are seeing the same issues.

**Comment by tatsuhiro-t** [comment]
Thank you for clarification.
I compared the socksify debug output between latest nghttp2 and v0.6.7.
Initially, v0.6.7 worked with socksify.
I found that with latest nghttp2, socksify used nonblocking connect code to connect to the backend server, while it used blocking version with v0.6.7.
I checked v0.6.7 code and found that it has a bug that it does not make file descriptor non-blocking.
If I make it non-blocking, v0.6.7 also returns 504 time out.
So this seems that socksify does not work very well with non-blocking socket.

**Comment by LPardue** [comment]
Reading around the subject a bit, I found a dants mailing list item dating back to 2006 - not sure if this was ever fixed as the trail seems to come to an end.. http://permalink.gmane.org/gmane.network.socks.dante.general/54

I also came across this QNX page (http://www.qnx.com/developers/docs/6.5.0/index.jsp?topic=%2Fcom.qnx.doc.neutrino_lib_ref%2Fsocksappendix.html) that says:
>If you call connect() on a nonblocking socket, no I/O can occur on that socket until another connect(), with the same arguments, returns -1 and sets errno to EISCONN.

I have tested this approach, and can see nghttpx work successfully over socks. However, the solution is ugly and probably affects performance.
The change I made was in shrpx_http_downstream.cc, after a successful connect call, I added 

``` 
    bool exit = false;
    while (!exit) {
        rv = connect(conn_.fd, &addr.add.sa, addr.addrlen);
        if (rv ==1 && errno == EISCONN) {
            exit = true;
        }
    }
````

**Comment by tatsuhiro-t** [comment]
Checking EISCONN would work, but the problem is it is very hard to know when we can call it without busy loop.  Waiting for connection to be established completely destroys event based architecture.
Dante FAQ http://www.inet.no/dante/doc/faq.html says about nonblocking socket:

>What does a socksified application need to care about?
>
>A socksified application will normally work without any extra steps needing to be done, within the limits of the SOCKS standard. The exception to this is the following:
>
>Applications combining non-blocking sockets with select(2)/poll(2) need to make sure they can handle the select(2)/poll(2) call being interrupted by a signal (i.e., failing with EINTR). This is due to how the Dante client library implements support for non-blocking connect(2).
>
>Since correctly handling EINTR might be considered recommended practice regardless of whether the application is socksified or not, this should not be a problem for most applications, but some application will fail when socksified due to this.

libev does handle EINTR, and if that happens just started to wait for events again.

**Comment by LPardue** [comment]
Thank you for the suggestion regarding EINTR. I wanted to double check if you are suggesting this change as a 'workaround' fix for my local environment, or if it is something that could/should go into nghttp2 codebase as a general solution to such issues.

**Comment by tatsuhiro-t** [comment]
I mean 'workaround' fix.  Blocking event loop is not general solution.

**Comment by LPardue** [comment]
Sorry I think we may have crossed wires a bit.

It sounded like using EINTR is a solution that does not block the event loop. If so then why would it not be appropriate to make that change and commit back to nghttpx?

I would be happy to prototype using EINTR if you can point me in the right direction.

**Comment by tatsuhiro-t** [comment]
I was not clear enough.  EINTER is correctly handled by libev,  but still socks does not work.  Therefore we have no way to use it.

**Comment by LPardue** [comment]
Thank you for the feedback.

Since it looks like this can't be fixed, can be worked around and probably doesn't affect many people I am closing this issue.
