### ISSUE TITLE
nghttp - Error decoding header

### ISSUE THREAD

**Issue by JanAndersson** [tatsuhiro-t/nghttp2#316]
When I try nghttp (1.0.5) against a custom HTTP/2 server for testing purposes I see:

% nghttp -v https://localhost:8443/index.html
[...]
[  0.214] recv (stream_id=13) :status: 200
[  0.214] [INVALID; error=Invalid HTTP header field was received] recv HEADERS frame <length=77, flags=0x04, stream_id=13>
          ; END_HEADERS
          (padlen=0)
          ; First response header
[  0.214] send RST_STREAM frame <length=4, flags=0x00, stream_id=13>
          (error_code=PROTOCOL_ERROR(0x01))

Looking at the traffic using Wireshark (1.99.8) the received headers looks ok.

Obviously there is a compatibility issue between the server I use and night, but I'm not able to see what the problem is...

Do you know of any limitations in the nghttp HPACK decoder?
Is it any way I can get more information from nghttp why the header can't be decoded?

**Comment by tatsuhiro-t** [comment]
Could you tell us what kind of header field caused this error?

**Comment by tatsuhiro-t** [comment]
nghttp2 HPACK code has no limits about incoming header fields, but we do some validation for incoming ones.  For example, we only allow pseudo-header fields (whose name starts with ':') defined in RFC 7540.

**Comment by JanAndersson** [comment]
Unfortunately I don't know which header that cause the error. But I suspect "content-length (since this is the header after the status header). 

Is there a way I can provide the wireshark capture showing the response headers that fail?

**Comment by tatsuhiro-t** [comment]
If you can run server in http (plain text http), then it is easier to sniff packet traffic in wireshark.
If it is not possible, build nghttp2 with --enable-debug configure option, which emits debugging information including HPACK decoding.

**Comment by JanAndersson** [comment]
I do have a wireshark capture. Is there a way I can post it to you?

**Comment by JanAndersson** [comment]
Please find the capture here:
http://external.pureload.info/product_download/tmp/nghttp-header-issue.pcapng

Server is running on port 8080. 

I tried to build nghttp2 with --enable-debug, but I'm running on Mac OS X and did run into various issues with dependencies...

**Comment by tatsuhiro-t** [comment]
It looks like offending header field value has leading white spaces.  I think removing them would transaction works.
I know this is allowed in HTTP/1.1 construction.  But now we have more machine friendly HTTP/2 framing, and if sender just strips leading and trailing white spaces, we can omit stripping operation in receiving side, and also have possibly increased security.

**Comment by JanAndersson** [comment]
You are absolutely correct. Thanks!
Kind of embarrassing bug on my side ;)
