### ISSUE TITLE
U14.04 build instructions wrong

### ISSUE THREAD

**Issue by bbulkow** [tatsuhiro-t/nghttp2#318]
For the README.md

You can remove libevent-dev ( I don't see why the project would require it since the project is libev based and it seems to build fine without it )

You need to add python-setuptools

And it would be nice to remove the / so the line can be cut and paste, 

to wit :

sudo apt-get install make binutils autoconf  automake autotools-dev libtool pkg-config
  zlib1g-dev libcunit1-dev libssl-dev libxml2-dev libev-dev libjansson-dev
  libjemalloc-dev cython python3.4-dev python-setuptools

**Comment by tatsuhiro-t** [comment]
libevent is used for programs under examples directory.  We have client and server tutorial and they use libevent.

**Comment by tatsuhiro-t** [comment]
I added python-setuptools to apt-get line as you suggested.  libevent -dev is still there since we used it in examples.
