### ISSUE TITLE
> 100% cpu load on nghttpx when --tls-ticket-key-cipher=aes-256-cbc enabled

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#320]
Hi,

on a high load website, nghttpx uses constantly > 100% cpu (up to nearly 200%) when tls-ticket-key-cipher=aes-256-cbc is used in nghttpx.conf.
After uncommenting and restarting, nghttpx goes back to sleep (0-20% cpu).

**Comment by tatsuhiro-t** [comment]
I think this was fixed with the recent commit https://github.com/tatsuhiro-t/nghttp2/commit/ff44e211ed9abda19fbdde66a16e4d6bdf784f86

**Comment by 0x64616E69656C** [comment]
Uh, missed that one. I'll feed this patch to quilt tomorrow und der what happens.

**Comment by 0x64616E69656C** [comment]
fix confirmed!
