### ISSUE TITLE
Don't use virtual /dev/stderr

### ISSUE THREAD

**Issue by thinred** [tatsuhiro-t/nghttp2#325]
Hi,
I'm trying to run nghttp2x under systemd and I get this kind of warnings/errors:

    nghttpx[20201]: Failed to open errorlog file /dev/stderr

Without --errorlog-syslog this message is shown 3 times and nghttp2x does not start.
With --errorlog-syslog nghttp2x works, but the message is shown 2 times nevertheless.

It seems that systemd does not like /dev/stderr:
http://lists.freedesktop.org/archives/systemd-devel/2015-April/031218.html

I propose to replace the logic of "/dev/stderr" in the source code with something that duplicates the stderr under fd = 2 (and using /proc/self/fd/2 does not count).

Cheers!
Tomasz

**Comment by tatsuhiro-t** [comment]
Fixed by PR #326
