### ISSUE TITLE
libnghttp2_asio.so, may conflict with libssl.so.1.0.0

### ISSUE THREAD

**Issue by centminmod** [tatsuhiro-t/nghttp2#327]
I have a Docker image for nghttp2 https://hub.docker.com/r/centminmod/docker-ubuntu-nghttp2/ and has worked fine until I tried to rebuild it today. The Dockerfile at https://github.com/centminmod/docker-ubuntu-nghttp2/blob/master/Dockerfile

I got the following errors in build log

    warning: libssl.so.1.0.2, needed by ../src/.libs/libnghttp2_asio.so, may conflict with libssl.so.1.0.0
    /usr/bin/ld: warning: libcrypto.so.1.0.2, needed by ../src/.libs/libnghttp2_asio.so, may conflict with libcrypto.so.1.0.0
    
    warning: libssl.so.1.0.2, needed by ../src/.libs/libnghttp2_asio.so, may conflict with libssl.so.1.0.0

configure: summary of build options:
    
        Version:        1.2.1-DEV shared 14:7:0
        Host type:      x86_64-unknown-linux-gnu
        Install prefix: /usr/local
        C compiler:     gcc
        CFLAGS:         -g -O2
        WARNCFLAGS:     
        LDFLAGS:        
        LIBS:           
        CPPFLAGS:       
        C preprocessor: gcc -E
        C++ compiler:   g++
        CXXFLAGS:       -g -O2 -std=c++11
        CXXCPP:         g++ -E
        Library types:  Shared=yes, Static=yes
        Python:
          Python:         /usr/bin/python
          PYTHON_VERSION: 2.7
          pyexecdir:      ${exec_prefix}/lib/python2.7/dist-packages
          Python-dev:     yes
          PYTHON_CPPFLAGS:-I/usr/include/python2.7
          PYTHON_LDFLAGS: -L/usr/lib -lpython2.7
          Cython:         cython
        Test:
          CUnit:          yes
          Failmalloc:     yes
        Libs:
          OpenSSL:        yes
          Libxml2:        yes
          Libev:          yes
          Libevent(SSL):  yes
          Spdylay:        yes
          Jansson:        yes
          Jemalloc:       yes
          Zlib:           yes
          Boost CPPFLAGS: -pthread -I/usr/include
          Boost LDFLAGS:  -L/usr/lib/x86_64-linux-gnu
          Boost::ASIO:    -lboost_system
          Boost::System:  -lboost_system
          Boost::Thread:  -lboost_thread
        Features:
    Applications:   yes
          HPACK tools:    yes
          Libnghttp2_asio:yes
          Examples:       yes
          Python bindings:yes
          Threading:      yes
          Third-party:    yes

further down the build log

    [0m
    make[2]: Leaving directory '/usr/local/src/nghttp2/examples'
    Making all in python
    make[2]: Entering directory '/usr/local/src/nghttp2/python'
    cython -o nghttp2.c nghttp2.pyx
    /usr/bin/python setup.py build
    [91mTraceback (most recent call last):
    [0m
    [91m  File "setup.py", line 24, in <module>
    [0m
    [91m    [0m
    [91mfrom setuptools import setup, Extension
    [0m
    [91mImportError: No module named setuptools
    [0m
    Makefile:524: recipe for target 'all-local' failed
    [91mmake[2]: *** [all-local] Error 1
    [0m
    make[2]: Leaving directory '/usr/local/src/nghttp2/python'
    Makefile:540: recipe for target 'all-recursive' failed
    [91mmake[1]: *** [all-recursive] Error 1
    [0m
    make[1]: Leaving directory '/usr/local/src/nghttp2'
    Makefile:448: recipe for target 'all' failed
    [91mmake: *** [all] Error 2     
so somethings changed ?

**Comment by tatsuhiro-t** [comment]
There was a change, but it fixes the bug that OpenSSL installed in custom location was not used for asio library.
Looking into the dockerfile, We also need OPENSSL_CFLAGS in nghttp2 configure line.
Without that, OPENSSL_LDFLAGS is ignored, and system default OpenSSL header files are used, and version mismatch could occur.  For OpenSSL, it uses pkg-config, so using ``PKG_CONFIG_PATH=/usr/local/http2-15/lib/pkgconfig`` instead of OPENSSL_LIBS would do the job.

And now python build requires python-setuptools...

**Comment by centminmod** [comment]
@tatsuhiro-t thank you so much - works wonderfully now :+1: 

Was missing nghttp in my tool set now that Nginx HTTP/2 patch is out :)

    nghttp --version
    nghttp nghttp2/1.2.1-DEV

**Comment by tatsuhiro-t** [comment]
Great, let's close this issue.
