### ISSUE TITLE
Timing script combined with -c

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#332]
Timing script added capability for number of requests to be assumed from the number of script lines, when `-n` is not defined .

The following example command shows how to trigger a parameter validation bug due to sequencing.

`h2load --timing-script-file='/path/to/file' -c2`

This bug occurs because `config.nreqs` defaults to 1, any value larger than 1 triggers this issue. 

I will look into fixing this. Would it be reasonable move the input file parsing block earlier in the validation sequence?

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this. I think it is a reasonable solution.
