### ISSUE TITLE
h2load: Add HTTP/1.1 support 

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#333]
h2load is a great tool for load testing of HTTP/2 servers, supporting both h2c and h2. SPDY is also supported if build with spdylay library.

This issue is a feature request for the addition of HTTP/1.1 support  (cleartext and encrypted) to h2load.

Having a single tool capable of supporting multiple versions of HTTP will allow for fairer comparisons between the results of load test runs. Other tools such as  [Apache Bench (ab)](http://httpd.apache.org/docs/2.4/programs/ab.html) or [wrk](https://github.com/wg/wrk) support HTTP/1.1 but comparing the results to h2load is unfair, due to different architectures and calculation of statistics.

## Design Goals
* Support for HTTP/1.1, cleartext and encrypted
* Convenient selection of HTTP/1.1 usage:
  * Use existing mechanisms where possible
* Convenient fallback to HTTP/.1:
  * E.g. failure of ALPN will cause fallback to HTTP/1.1 (if enabled)

## Constraints
* h2load architecture uses a single connection per origin per client
  * UA's typically use up to 6-10 HTTP/1.1 connections per origin

## Implementation details
* Add Http1Session class and use it in h2load.cc
* Add new command-line parameter for client ALPN/NPN protocol identifier list, mirror [nghttpx parameter] (https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx--npn-list)
* Add support for http/1.1 to [`-p` option](https://nghttp2.org/documentation/h2load.1.html#cmdoption-h2load-p)

**Comment by tatsuhiro-t** [comment]
I think user defined -m option is effectively ignored for HTTP/1, and it is treated as if -m1 is set, and we can reuse connection (keep-alive) to send multiple requests one by one.
For web server which does support HTTP/1 only, if server does not select anything in ALPN, we should fallback to HTTP/1.

**Comment by LPardue** [comment]
Thanks for the feedback. I've incorporated the fallback into Parent post.

> I think user defined -m option is effectively ignored for HTTP/1, and it is treated as if -m1 is set, and we can reuse connection (keep-alive) to send multiple requests one by one.

Are you suggesting that HTTP Pipelining should be effectively disabled?

**Comment by tatsuhiro-t** [comment]
When I was writing the previous post, I thought h1 pipelining should be disabled, so yes.
This was because in real world h1 pipelining is not used in browsers.  However, if it is commonly used in non browser cases, for example, cli tool or rpc, then I have no objection to support it in h2load.

**Comment by LPardue** [comment]
I'll have a deeper think about pipelining. A better emulation of browser client behavior would be to have a connection pool (of 6 or so connections) that can be used. This is more complicated than what I originally had in mind, so may need to come later.

**Comment by LPardue** [comment]
> For web server which does support HTTP/1 only, if server does not select anything in ALPN, we should fallback to HTTP/1.

I've been working on this part of the code. OpenSSL documentation is not great for NPN and ALPN. 

What happens if a server does not support either extension? At the moment I am testing with an apache instance that causes OpenSSL to call `client_select_next_proto_cb` with an `in` value of `" "`. The current logic causes SSL_TLSEXT_ERR_NOACK to be returned and the connection terminates. 

A more graceful fallback would be to assume HTTPS/1.1 would work in this case and give it a go.

**Comment by tatsuhiro-t** [comment]
I agree that browser emulation is a bit hard since h2load has no capability to group connections.
Usually, this kind of tool use the number of connection to measure the load.  For h2load caes, -c option does that job.  I think --timing-script option could be affected by the serialized request per connection in HTTP/1.1 without emulation.  I think it is reasonable to make first PR without emulation.

**Comment by tatsuhiro-t** [comment]
If server didn't select anything in ALPN, next_proto could be nullptr (https://github.com/tatsuhiro-t/nghttp2/blob/e6566a1e3aa7b489e85420546e4abfba2667891e/src/h2load.cc#L539).

For NPN, its specification allow the client to choose whatever protocol it can choose.
However, if server does not support NPN, then I think no callback is called to choose protocol.

Fortunately, In either case, we can still catch these situations in connection_made() function.  If no protocol was selected, then we should go with HTTP/1.1 as fallback.

**Comment by LPardue** [comment]
#356 PR closed this issue..

Single connection for HTTP/1.1 still a constraint. Pipelining can occur if combined with an appropriate timing script.

Let's go from here and keep improving HTTP/1.1 feature if required!

**Comment by s0j0urn** [comment]
@LPardue 

In the case of HTTP/1.1 with h2load, Do we still have the constraint of single connection per origin per client? Sorry, I am curious and haven't had the chance to test it myself yet.

And about your statement: "Pipelining can occur if combined with an appropriate timing script". Will you please provide a small example? How is it different from straightaway using the -m =N option in h2load?

**Comment by s0j0urn** [comment]
@LPardue @tatsuhiro-t 

I tested h2load with http/1.1 to verify no. of connections made. Unfortunately, yes there is contraint of single connection per origin per client. 
Considering this constraint, I would say it will not be a fair for http/2 performance to comapred with http/1.1 performance using h2load as only one TCP connection is one of the major benefits of http/2 and h2load is offering the same advantage to http/1.1 .

What do you think ?

Also, I am still hoping for some explanation about @LPardue statement about pipeling requests.

**Comment by tatsuhiro-t** [comment]
You can do fair comparison by properly adjusting -c and -m options.
For HTTP/2, -m means number of concurrent requests, and it is typically 100.
For HTTP/1, -m means in flight HTTP pipelining requests, so to reflect the current practice, it should be 1 (which is default).  The number of connections used by HTTP/1 is typically 6, so use 6 times more connections.
So if we use 100 connections for HTTP/2, and we use 600 connections for HTTP/1.

**Comment by s0j0urn** [comment]
@tatsuhiro-t 
Your explanation helped and I was able to test it :) . Thank You

Just to make sure I am understanding this clearly :

For HTTP/2, -c option is acting as the number of clients.
For HTTP/1.1, -c options is acting as the number of connections that a single client is making.

So, if I want multiple HTTP/1.1 clients to perform the same operations in parallel so as to load a server, let's say: 

 h2load -n205 -c6 --h1 -m1 -i all_urls.txt

I will have to code a script that execute the above command in parallel by multiple instances.
or h2load can handle this case as well for HTTP/1.1

**Comment by tatsuhiro-t** [comment]
> I will have to code a script that execute the above command in parallel by multiple instances.

It would work.

-c option is just the number of connections h2load makes.  There is no distinction there between http2 and http1.  If your usecase does not differentiate input URIs (e.g., ordering is not important, and just load server with bunch of requests), just use 6 times more connections may simulate HTTP/1 clients.  Otherwise, you have to create multiple h2load instance to simulate multiple http1 clients since there is no feature in h2load to group up multiple connections to form HTTP/1 client.

**Comment by LPardue** [comment]
So, I have worked with an older version of h2load before the change to `-m`. With the old version, you could create a script like:

```
    100.0	https://localhost/index.html
    101.0	/style.css
    102.0	/script.js
    103.0	/image.png
```
This would issue 4 requests with a gap of 1 millisecond between each request. h2load does not wait for the response 1 before issuing request 2, request 3 and so on. Assuming the request time happens before a previous response is received then pipelining is achieved.

Of course, following a script doesn't really give a feel for how well a client can perform if makes use of features or optimisations. However, the script features was developed with the intention of repeatable load tests to characterise server behavoiur. To get really clever, you could create different timing scripts for HTTP/1.1 clients (with/without pipelining) and HTTP/2.

@tatsuhiro-t  In the newer h2load does -`m1` prevent this behavior in timing script? Or does it just limit non-timing script function?

**Comment by tatsuhiro-t** [comment]
I only changed default value of -m option.  Previously, it was special value "auto", which is the number of URIs which appear in command-line or timing script.  In the above, example, using -m4 is the old default.
The reason for removal of "auto" is disable HTTP pipelining feature which is not used in practice by browsers.

**Comment by LPardue** [comment]
Ok cool!
