### ISSUE TITLE
h2load: timing script file false postitive error

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#339]
When loading h2load, certain conditions may lead to errno being set to a nonzero value during startup. These conditions do not prevent the successful loading of h2load, and normal usage should continue. However, in combination with the timing script, we see a false positive error returned for parsing/validation of the timing script e.g. `if (end == start || errno != 0) `.

Better practice would be to set errno to 0 before the call to `strtod`. A more specific check of errno (`ERANGE`) would also help.

**Comment by tatsuhiro-t** [comment]
I agree.  man page also says about errno.
