### ISSUE TITLE
websocket proxy

### ISSUE THREAD

**Issue by mhf-ir** [tatsuhiro-t/nghttp2#342]
We used nginx as websocket proxy:

````
location /wsapp/ {
    proxy_pass http://wsbackend;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
```

Is there any option for nghttp for use this use case. backend maybe socket.io or php Ratchet projects. it's many popular for web apps.

**Comment by tatsuhiro-t** [comment]
nghttpx can proxy websocket assuming that both frontend and backend are HTTP/1.1 and backend does HTTP Upgrade job.  For instance, to forward request to /wsapp/ to backend server wsbackend:
```
$ nghttpx -b"wsbackend;/wsapp/" ...
```

Please make sure that nghttpx needs catch all backend pattern.  See https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-b

**Comment by mhf-ir** [comment]
:+1:

**Comment by tatsuhiro-t** [comment]
So guessing from the commend, I think we can close this issue.
