### ISSUE TITLE
END_STREAM flags

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#346]
Hello,
I would like to have traffic with request HEADERS with END_STREAM flag == 0 and response DATA with END_STREAM flag == 0. Can you tell me what source code file and how I have to change it?
Best Regards

**Comment by tatsuhiro-t** [comment]
HEADERS:
* https://github.com/tatsuhiro-t/nghttp2/blob/753f6d4a3e5696438d96f560f79352a59841ef08/lib/nghttp2_submit.c#L383
* https://github.com/tatsuhiro-t/nghttp2/blob/753f6d4a3e5696438d96f560f79352a59841ef08/lib/nghttp2_submit.c#L413

DATA:
* https://github.com/tatsuhiro-t/nghttp2/blob/753f6d4a3e5696438d96f560f79352a59841ef08/lib/nghttp2_session.c#L6199

**Comment by lespla** [comment]
I've commented these lines but it continue sending with END_STREAM==1

**Comment by tatsuhiro-t** [comment]
Perhaps, there may be another locations.  Grepping NGHTTP2_FLAG_END_STREAM would show the locations.

**Comment by lespla** [comment]
I have looked for it and comment one more line(nghttp2_submit.c#L169) but it contunues without working

**Comment by tatsuhiro-t** [comment]
nghttp2_submit.c#169 is not relevant.  When I commented out those lines, no END_STREAM was seen.

**Comment by lespla** [comment]
It's working now, at the end I only comment DATA END_STREAM. Now I think there is a open stream limit at the same time, because when it gets 211 streams it stops.Can I change this value?
BR

**Comment by tatsuhiro-t** [comment]
Assuming that you are creating streams from client, server can adverse maximum number of concurrent streams by nghttp2_submit_settings with NGHTTP2_SETTINGS_MAX_CONCURRENT_STREAMS.

**Comment by lespla** [comment]
Hello,
I run it with client and server with next option: --max-concurrent-streams=200 and proxy with this one:
--http2-max-concurrent-streams=200 
It Works now
Thanks a lot
