### ISSUE TITLE
Change server header name and remove via

### ISSUE THREAD

**Issue by mhf-ir** [tatsuhiro-t/nghttp2#348]
i have configuration like this :
```
frontend=0.0.0.0,443
backend=127.0.0.1,8080
private-key-file=/ssl/selfsigned.key
certificate-file=/ssl/selfsigned.crt
http2-proxy=no
errorlog-file=/logs/nghttpx.error.log
no-via=1
add-response-header="Server: ExampleWS"
```
`no-via` not applied in config file also `add-response-header` also after add arguments in cli via
`--add-response-header="Server: ExampleWS" --no-via` arguments no via work well but server name appened to nghttpx name not replace it.

```
Server: nghttpx nghttp2/1.3.1-DEV, ExampleWS

**Comment by tatsuhiro-t** [comment]
Try no-via=yes

--add-response-header just appends header fields, and it does not replace the existing one.
Currently no way to change server header field with command-line arguments.
If you can build nghttp2 with mruby support, you can change response headers in anyway you like.

**Comment by tatsuhiro-t** [comment]
Please reopen this issue if you still have this problem.
