### ISSUE TITLE
MSVC Build Broken

### ISSUE THREAD

**Issue by BrisingrAerowing** [tatsuhiro-t/nghttp2#349]
The following code in nghttp2_helper.h does not build with MSVC due to the missing typeof operator and missing __builtin_offsetof method/define/whatever.

```c
#define nghttp2_struct_of(ptr, type, member)                                    \
  ({                                                                            \
    const typeof(((type *)0)->member) *nghttp2__mptr = (ptr);                   \
    (type *)(void *)((char *)nghttp2__mptr - __builtin_offsetof(type, member)); \
  })
```

I don't know much about C/C++, but I did find that MSVC supports a [decltype](https://msdn.microsoft.com/en-us/library/dd537655.aspx) operator, similar to typeof, and supports an [offsetof](https://msdn.microsoft.com/en-us/library/dz4y9b9a.aspx) macro that works like __builtin_offsetof. Just changing those calls doesn't work, sadly.

Any ideas on this?

**Comment by tatsuhiro-t** [comment]
We can avoid typeof altogether, and just use ptr since we cast it to char* anyway.
And replacing __builtin_offsetof with offsetof should work.

**Comment by tatsuhiro-t** [comment]
The proposed fix was committed via 1bbef4b

**Comment by BrisingrAerowing** [comment]
I'll (probably) test this later, if I have time.

**Comment by tatsuhiro-t** [comment]
Please reopen if you have still failing build.
