### ISSUE TITLE
Several CONTINUATION frames

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#354]
Is there any way to generate a capture with several CONTINUATION frames. In case it is what should we modify in the code or what parameter should we use to achieve this goal?
BR

**Comment by tatsuhiro-t** [comment]
nghttp has --continuation option for this purpose.

**Comment by lespla** [comment]
Thanks for your quick response.
Yes we already knew about this --continuation option but what we actually are looking for is to generate more than one continuation frame.
What we can see is that using this --continuation only generates one continuation frame

**Comment by tatsuhiro-t** [comment]
https://github.com/tatsuhiro-t/nghttp2/blob/4aaf111c5853f5d00594724ebbffffc5cd011931/src/nghttp.cc#L363

Change how many garbage header field to send.  For example, changing 6 to 12 will send 2 CONTINUATION frames.
Note that nghttp2 has limitation for internal send buffer, and anything beyond that does not work.
