### ISSUE TITLE
nghttpx crash in 1.3.1

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#355]
Hi,

one of my nghttpx instances (the high-load-webthingy as always) just crashed, error.log shows:
> nghttpx: shrpx_connection.cc:149: int shrpx::{anonymous}::shrpx_bio_write(BIO*, const char*, int): Assertion `wbuf.rleft() == 0' failed.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this. I'll look into this issue.

**Comment by tatsuhiro-t** [comment]
I just reproduced this issue now.

**Comment by tatsuhiro-t** [comment]
Fix committed via 4aaf111c5853f5d00594724ebbffffc5cd011931

**Comment by 0x64616E69656C** [comment]
thanks!
