### ISSUE TITLE
h2load: rate feature modification

### ISSUE THREAD

**Issue by LPardue** [tatsuhiro-t/nghttp2#358]
Hi,

I am considering an enhancement to the `-r, --rate` feature, where defining a rate between 0 and 1 would allow clients to be created at a rate less than every second. For example, to create a new client every 10 seconds we could provide the rate value `0.1`.

I've done some tinkering in the code to test if this would be possible (and it is by ultimately varying the timeout value given to `timeout_watcher`) but I keep hitting issues with the validation logic, and also calculations when running multiple `--threads`.

I wanted to get a better understanding of the current ruleset for rate mode. Perhaps @nshoemaker may be able to help too? 

For instance, why is this rule `-r, -t: the connection rate must be greater than or equal to the number of threads.` enforced?

Regards
Lucas

**Comment by LPardue** [comment]
Further,

The current rate feature creates N clients after 1 second elapses. This means the creation is not 'smooth' but instead is quantised/discrete on the second boundaries. For large N, the stepping effect of this is going to be more pronounced. 

A solution to this issue would be to allow the definition of the timeout period. This is not directly associated with my first enquiry, but could go towards a more expressive syntax for defining longer timeout periods. Some care would need to be paid to avoid over-complicating the h2load interface but I think it is possible. 

Any thoughts?

**Comment by tatsuhiro-t** [comment]
I think -r > -t rule is done just because making calculation/code easier.  If I allow it, then we get floating point exception.  If we make it robust, perhaps, we reduce -t to -r.

**Comment by tatsuhiro-t** [comment]
Smoothing out for creating connection sounds good.
I'm wondering which is better for load testing scenario, stepping or smooth slope?  Perhaps, we may have both.

**Comment by LPardue** [comment]
> I'm wondering which is better for load testing scenario, stepping or smooth slope? Perhaps, we may have both.

To take it even further, even a smooth linear trend for client connection may not correctly simulate the load on a server. Thinking on more of a macro scale, the rate of connection could be described as a curve over time period. For example, some of the ease in curves described [here](http://easings.net/) and shown below. 

![easing-curves](https://cloud.githubusercontent.com/assets/6571445/9935092/b46c10b6-5d4c-11e5-8771-2e4c1b03546d.png)

This is maybe too much complexity for h2load, but it could be implemented by h2load internally generating a "client creation schedule" based upon rate, and choice of straight line, curves, discrete or smooth.

**Comment by nshoemaker** [comment]
> I think -r > -t rule is done just because making calculation/code easier. If I allow it, then we get floating point exception.

I just want to confirm that this was the reason for enforcing that rule. 

The implementation relies heavily on the second interval in the upfront calculations for distributing the work over threads, clients, etc. The various outputs of those calculations are often used as ending criteria.

for instance:
```if (worker->nconns_made >= worker->nclients) {``` 
[(you can view this line in context here)](https://github.com/tatsuhiro-t/nghttp2/blob/master/src/h2load.cc#L179)

So in addition to changing `timeout_watcher`, you would probably need to completely re-work those calculations and/or find different ending criteria.

**Comment by tatsuhiro-t** [comment]
You are right, it affects all calculations later.

**Comment by LPardue** [comment]
Thanks for the feedback. I will have a think about what to do.

**Comment by LPardue** [comment]
Through the now merged PR, we implemented this feature using a different approach, providing a rate period option to increase the time between client creation.

Rate mode can now be used with script mode, however there are some complications when combing certain parameters. These can be addressed later on.

Closing this issue now, thanks for merging!
