### ISSUE TITLE
nghttp2_asio Cannot Compile due to Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by hardywu** [tatsuhiro-t/nghttp2#360]
I am building on Mac 10.10.5 with `LDFLAGS='-L/usr/lib -lstdc++  -L/usr/local/opt/openssl/lib -lcrypto '` and `CPPFLAGS=-I/usr/local/opt/openssl/include`

````
  CXX      libnghttp2_asio_la-asio_client_stream.lo
  CXX      libnghttp2_asio_la-asio_client_tls_context.lo
  CXXLD    libnghttp2_asio.la
Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in libnghttp2_asio_la-asio_common.o
````

**Comment by tatsuhiro-t** [comment]
It looks like "-lssl" is missing or openssl libs under /usr/lib is used instead of custom location.
What do you get if you change LDFLAGS to `-lstdc++ -L/usr/local/opt/openssl/lib -lssl -lcrypto`?

**Comment by hardywu** [comment]
It works. Thanks a lot.

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
