### ISSUE TITLE
Chunked server

### ISSUE THREAD

**Issue by lespla** [tatsuhiro-t/nghttp2#361]
Hello,
I would like to setup my server for responsing in chunked mode for downloading files or videos. Is it available?
BR

**Comment by tatsuhiro-t** [comment]
I'm not aware of "chunked mode" in HTTP/2.  If you are referring to chunked encoding in HTTP/1.1, it is deprecated in HTTP/2.  In HTTP/2, DATA frame is inherently chunked.

**Comment by lespla** [comment]
In rfc: https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.6[14/09/2015
speaks about it:
 HTTP/1.1 100 Continue            HEADERS

     Extension-Field: bar       ==>     - END_STREAM

                                        + END_HEADERS

                                          :Status = 100

                                          extension-field = bar

 

     HTTP/1.1 200 OK                  HEADERS

     Content-Type: image/jpeg   ==>     - END_STREAM

     Transfer-Encoding: chunked         + END_HEADERS

     Trailer: Foo                         :Status = 200

                                          content-length = 123

     123                                  content-type = image/jpeg

     {binary data}                        trailer = Foo

     0

     Foo: bar                         DATA

                                        - END_STREAM

                                      {binary data}

 

                                      HEADERS

                                        + END_STREAM

                                        + END_HEADERS

                                          foo = bar

**Comment by tatsuhiro-t** [comment]
That is non-final response code.  I'm not sure what "chunked" means.
Also you should refer to RFC 7540 instead of draft version.

**Comment by lespla** [comment]
In RFC 7540 says the same. Http2 translates chunked http 1.1 to http2 coding

**Comment by tatsuhiro-t** [comment]
Well, yes.  And it is just regular HTTP/2.
Again, in HTTP/2, everything is chunked.

**Comment by lespla** [comment]
Thanks

On 22 September 2015 at 11:38, Tatsuhiro Tsujikawa <notifications@github.com

**Comment by lespla** [comment]
Hello
I don't have it very clear yet. I want to simulate a real time video server,that doesn't know the end length of the video. Questions:
1. How would it work?
2. Would It send a lot of DATA FRAME with end_stream flag ==0 and the last DATA frame with end_stream ==1?
3. Would the length of content-length field in HEADERS frame response be? would it send a HEADER frame for each DATA frame?
4. Do you have a Http2 real time video server?  

BR

**Comment by tatsuhiro-t** [comment]
> 1. How would it work?

I have no experience about real time video server.  There seems several ways to do this.

https://en.wikipedia.org/wiki/HTTP_Live_Streaming
https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP

These methods split video file into several chunks and download parts which requires smooth playback in parallel.  Again, I have no experience about this, so please investigate them yourself.

> 2. Would It send a lot of DATA FRAME with end_stream flag ==0 and the last DATA frame with end_stream ==1?

In HTTP/2 protocol wise, yes.

> 3. Would the length of content-length field in HEADERS frame response be? would it send a HEADER frame for each DATA frame?

If content-length is known, you can put it in HEADERS.
Otherwise, you cannot.

In general, if you cannot HEADERS frame for each DATA frame inside the same stream in HTTP/2.
If you want to send HEADERS for each DATA frame, create stream for each.

> 4. Do you have a Http2 real time video server? 

No.
