### ISSUE TITLE
Frontend UNIX socket owner and mode

### ISSUE THREAD

**Issue by rraptorr** [tatsuhiro-t/nghttp2#362]
I'm trying to use UNIX socket as a frontend. Unfortunately, it seems it is not possible to change socket owner and mode. UNIX socket is created before dropping privileges so it usually is owned by root with mode 644, which is not very useful. Ideally it should be possible to change socket owner, group and mode.

**Comment by tatsuhiro-t** [comment]
OK, let's chown UNIX socket to user specified --user option.

**Comment by tatsuhiro-t** [comment]
Fix committed via 87a38bdf8d16d225ed3eca6548901e91d0d7562c

**Comment by rraptorr** [comment]
Seems to be working fine for me, thanks:)
