### ISSUE TITLE
CONTINUATION frame following HEADERS frame that includes padding

### ISSUE THREAD

**Issue by shane-kearns** [tatsuhiro-t/nghttp2#367]
nghttp nghttp2/1.3.4-DEV commit 913b95336b8be9356ff754c77d788445b4816f76

Steps to reproduce:
1. Use the 'nghttp' program to make a HTTP/2 request, using -v or --har to save the headers
2. On the HTTP/2 server, send a HEADERS frame that includes the PADDED flag and one or more bytes of padding.
3. Send a CONTINUATION frame that includes the END_HEADERS flag

Expected result:

All headers are included

Actual result:

The headers which were transmitted in the HEADERS frame are included
The headers which were transmitted in the CONTINUATION frame are silently dropped

Additional info:

If padding is disabled, nghttp correctly reassembles the fragmented headers.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.
I believe it was fixed with the commit 93ba75b

**Comment by shane-kearns** [comment]
I've retested with commit d618cd92ccc02962745cec317f8e60b85f137945 and the problem seems to be fixed.
Thanks for the quick fix.

**Comment by tatsuhiro-t** [comment]
Thank you.  Let's close the issue.
