### ISSUE TITLE
'WINDOW_UPDATE' MUST not have an increment of 0

### ISSUE THREAD

**Issue by daurnimator** [tatsuhiro-t/nghttp2#369]
If you pass `-w 0` on command line nghttp will send invalid window updates:
```
[  0.001] send WINDOW_UPDATE frame <length=4, flags=0x00, stream_id=13>
          (window_size_increment=0)
```

According to the http2 spec:
> A receiver MUST treat the receipt of a WINDOW_UPDATE frame with an flow-control window increment of 0 as a stream error (Section 5.4.2) of type PROTOCOL_ERROR; errors on the connection flow-control window MUST be treated as a connection error (Section 5.4.1).

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this bug.
I believe this bug was fixed by the commit ef3e2c7
