### ISSUE TITLE
Cython Out of Date

### ISSUE THREAD

**Issue by RandomDSdevel** [tatsuhiro-t/nghttp2#370]
You've got the ngHTTP2 build process using a copy of [Cython v0.23.1](https://github.com/cython/cython/releases/tag/0.23.1) when [Cython v0.23.2](https://github.com/cython/cython/releases/tag/0.23.2) is already available.

**Comment by tatsuhiro-t** [comment]
Do you point us to the file where we copy cython v0.23.1?

**Comment by RandomDSdevel** [comment]
No, I just saw Cython running during the build process that [Homebrew](https://github.com/Homebrew/homebrew) ran for me.  If I remembered the file path that I saw, though, I'd tell you.  Have you tried searching this repository for files or folders named 'Cython' or files containing references to it?

**Comment by tatsuhiro-t** [comment]
We don't hard coded cython path.  Instead we find cython executable path when running ./configure.
--with-cython configure option can override this process.  Perhaps, configure found old version in homebrew installation?  Or package maintainer might set --with-cython to the particular cython version.

**Comment by RandomDSdevel** [comment]
Never mind, it's not you; the culprit is [lines 93-96 of ngHTTP2's Homebrew formula].  If I had experience with programming in Ruby, I'd submit a pull request, but, unfortunately, I don't, so I guess you can fix it if you want…
