### ISSUE TITLE
Support BoringSSL

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#373]
Since we support OpenSSL and LibreSSL, it would be nice to also support BoringSSL.
Ref https://github.com/tatsuhiro-t/nghttp2/issues/291#issuecomment-143711259

**Comment by bagder** [comment]
Let me just mention that BoringSSL is much harder to support than libressl and they more or less say that it is a moving target that isn't for non-google Software...

**Comment by tatsuhiro-t** [comment]
Thank you.  I agree that moving target is really hard job to keep up especially for API changes.
I just imagined the differences are just  few configuration APIs, but it appears more substantial?

**Comment by 0x64616E69656C** [comment]
I agree with the argument of boringssl being a moving target, and should not replace openssl as default crypto-library. I have forked bssl internally for "personal use", modified the build system, kicked out a few obsolete/unneccessary/insecure ciphers, and merge changes from upstream boringssl to the remaining code. As far as implementation goes, boringssl uses openssl header files and provides -lcrypto and -lssl like openssl does, the issue with boringssl is that they dropped support for *_ctrl macros, as far as I understood, replacing those in nghttp2 with their proper functions should not affect compilation against openssl/libressl.

```
Switch any `*_ctrl` callers to the macro/function versions. This works in both
OpenSSL and BoringSSL. Note that BoringSSL's function versions will be
type-checked and may require more care with types
```

Which other issues are to be expected when providing support for boringssl that I might be missing?

**Comment by tatsuhiro-t** [comment]
f0d2c9f94bbc08b22633f1a20a9ee1982c50d208 enables compilation with BoringSSL, except for neverbleed and libnghttp2_asio.
The latter  uses boost::asio, which calls OpenSSL functions deleted in BoringSSL.

**Comment by BenPope** [comment]
It's a shame, because the patch to asio is small and significantly improves scalability across threads:
https://konradzemek.com/2015/08/16/asio-ssl-and-scalability/
https://gist.github.com/kzemek/37aa2a2138b2651f2c55

**Comment by tatsuhiro-t** [comment]
Do you have a plan to submit the patch to boost upstream?

**Comment by BenPope** [comment]
I think it's been done:
https://github.com/chriskohlhoff/asio/issues/52
https://github.com/chriskohlhoff/asio/issues/74
But my understanding is that Chris Kohlhoff is pretty busy with standardisation efforts.

**Comment by tatsuhiro-t** [comment]
Thanks.  We will revisit libnghttp2_asio and BoringSSL when these patches are merged.

**Comment by 0x64616E69656C** [comment]
@BenPope thanks for the link to konrad zemek's blog post, this is very interesting.

@tatsuhiro-t which FLAGS are you using when compiling against boringssl? It won't work here (latest git nghttp2 + boringssl), for example:

```
clang++ -DHAVE_CONFIG_H -I. -I..  -DPKGDATADIR='"/opt/nghttp2/share/nghttp2"' -Wall -I../lib/includes -I../lib/includes -I../lib -I../src/includes -I../third-party -I/usr/include/libxml2 -I/opt/boringssl/include -DHAVE_CONFIG_H   -D_FORTIFY_SOURCE=2 -O0 -g3 -fno-omit-frame-pointer -Wformat -Wformat-security -Werror=format-security -fstack-protector-all -fPIE -fPIC -fsanitize=address,undefined -Werror=array-bounds -Warray-bounds -Wstrict-prototypes -Wpointer-type-mismatch -Wreorder -Wpointer-sign -Wsign-compare -std=c++11 -stdlib=libc++ -MT nghttp.o -MD -MP -MF $depbase.Tpo -c -o nghttp.o nghttp.cc &&\
/bin/bash ../libtool  --tag=CXX   --mode=link clang++  -D_FORTIFY_SOURCE=2 -O0 -g3 -fno-omit-frame-pointer -Wformat -Wformat-security -Werror=format-security -fstack-protector-all -fPIE -fPIC -fsanitize=address,undefined -Werror=array-bounds -Warray-bounds -Wstrict-prototypes -Wpointer-type-mismatch -Wreorder -Wpointer-sign -Wsign-compare -std=c++11 -stdlib=libc++  -Wl,-z,relro -Wl,-z,now -O0 -g3 -fno-omit-frame-pointer -fPIE -fPIC -pie -Wformat -Wformat-security -Werror=format-security -fstack-protector-all -Wreorder -Wsign-compare -o nghttp util.o http2.o timegm.o app_helper.o nghttp2_gzip.o  nghttp.o HtmlParser.o  ssl.o ../lib/libnghttp2.la ../third-party/libhttp-parser.la -ljemalloc -lxml2 -lev -L/opt/boringssl/lib -lcrypto -lssl -ljansson -L/usr/lib/x86_64-linux-gnu -lz -pthread
```

```
ldd src/nghttp
[...]
        libcrypto.so => /usr/lib/x86_64-linux-gnu/libcrypto.so (0x00007f3da0e68000)
        libssl.so => /usr/lib/x86_64-linux-gnu/libssl.so (0x00007f3da0bfe000)
[...]
```

```
./src/nghttp
./src/nghttp: symbol lookup error: ./src/nghttp: undefined symbol: SSL_CTX_set_options
```

```
./src/nghttpx
./src/nghttpx: symbol lookup error: ./src/nghttpx: undefined symbol: BIO_clear_retry_flags
```


options used for compilation:
```
CFLAGS="-D_FORTIFY_SOURCE=2 \
-O0 -g3 -fno-omit-frame-pointer \
-Wformat -Wformat-security -Werror=format-security \
-fstack-protector-all -fPIE -fPIC \
-fsanitize=address,undefined \
-Werror=array-bounds -Warray-bounds \
-Wstrict-prototypes -Wpointer-type-mismatch \
-Wreorder -Wpointer-sign -Wsign-compare" \
CXXFLAGS="-D_FORTIFY_SOURCE=2 \
-O0 -g3 -fno-omit-frame-pointer \
-Wformat -Wformat-security -Werror=format-security \
-fstack-protector-all -fPIE -fPIC \
-fsanitize=address,undefined \
-Werror=array-bounds -Warray-bounds \
-Wstrict-prototypes -Wpointer-type-mismatch \
-Wreorder -Wpointer-sign -Wsign-compare -std=c++11 -stdlib=libc++" \
LDFLAGS="-Wl,-z,relro -Wl,-z,now \
-O0 -g3 -fno-omit-frame-pointer \
-fPIE -fPIC -pie \
-Wformat -Wformat-security -Werror=format-security \
-fstack-protector-all \
-Wreorder -Wsign-compare" \
CC="clang" \
CXX="clang++" \
OPENSSL_LIBS="-L/opt/boringssl/lib -lcrypto -lssl" \
OPENSSL_CFLAGS="-I/opt/boringssl/include" \
LIBEVENT_OPENSSL_LIBS="-L/opt/boringssl/lib -lcrypto -lssl" \
LIBEVENT_OPENSSL_CFLAGS="-I/opt/boringssl/include" \
./configure \
--disable-shared \
--prefix=/opt/nghttp2 \
--with-libxml2=yes \
--with-jemalloc=yes \
--enable-hpack-tools \
--enable-examples=no \
--disable-python-bindings
```

Thanks!

**Comment by tatsuhiro-t** [comment]
The build process is good.  The problem is dynamic linker failed to find boringSSL library (I assume you built shared library, right?).
Try adding /opt/boringssl/lib to linker search path, or use LD_LIBRARY_PATH=/opt/boringssl/lib for short term workaround.

**Comment by 0x64616E69656C** [comment]
Hm, nope, should be static (--disable-shared), but this differs from my libressl build. I just retried with shared, same result after make install. I'll try again with LD_LIBRARY_PATH tomorrow, thanks!

**Comment by 0x64616E69656C** [comment]
couldn't wait. Added /opt/boringssl/lib to /etc/ld.so.conf.d/boring.conf and now it works.

```
ldd nghttpx|grep boring
        libcrypto.so => /opt/boringssl/lib/libcrypto.so (0x00007f6f6da46000)
        libssl.so => /opt/boringssl/lib/libssl.so (0x00007f6f6d7f9000)
```

let the games begin. :-)

**Comment by 0x64616E69656C** [comment]
Okay, so far it's *slightly* slower than with openssl, I guess this is because it's missing boost::ASIO?

Also, h2load does not use CHACHA-POLY1305 as cipher but always ECDHE-RSA-AES256-GCM-SHA384. Would it be possible that h2load uses server prefered cipher order, or even to be able to manually chose the cipher?
Thanks!

**Comment by tatsuhiro-t** [comment]
boost::asio is used by libnghttp2_asio only.  h2load, nghttpd, nghttpx, and nghttp never use it.

h2load has --ciphers option to set ciphers in common OpenSSL ciphers format.

**Comment by tatsuhiro-t** [comment]
nghttpx also has that option.  But nghttpd does not.
If you in a hurry, edit DEFAULT_CIPHER_LIST in src/ssl.cc directory and recompile.

**Comment by 0x64616E69656C** [comment]
yeah, one should not look for cipher options in _nghttp_ when coming down with the flu. not the proudest moment :)

**Comment by tatsuhiro-t** [comment]
Take care ;)

**Comment by tatsuhiro-t** [comment]
I close this issue since nghttp2 application now can be compiled with boringSSL, that is the original issue.
