### ISSUE TITLE
Push on HTTP2 proxy

### ISSUE THREAD

**Issue by rfmcpherson** [tatsuhiro-t/nghttp2#374]
I'm sorry if this isn't the place for this. If not, I'm sorry.

I'm able to get push to work when I use nghttp2 as a server. Connecting to it with Firefox pushes the css page and loads the main page. However, when I switch to using it as an HTTP2 proxy in Firefox, I'm no longer able to push anything. The main page loads, but the pushed page never gets through. 

My code is below:

    import io
    import nghttp2
    import ssl
    
    class Handler(nghttp2.BaseRequestHandler):
    
        def on_headers(self):
            self.push(
                path="/style.css", body="body{background-color:green}", 
                status=200)
            self.send_response(
                body='<html><link rel="stylesheet" type="text/css" href="style.css">Hello world!</html>', 
                status=200) 
    
    
    ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    ctx.options = ssl.OP_ALL | ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3
    ctx.load_cert_chain('./cert/server.crt', './cert/server.key', password="1234")
    
    server = nghttp2.HTTP2Server(('0.0.0.0', 8080), Handler, ssl=ctx)
    server.serve_forever()

**Comment by tatsuhiro-t** [comment]
I think PUSH_PROMISE is sent, but browser refused it because proxy is not authoritative to the pushed resource.
See https://tools.ietf.org/html/rfc7540#section-8.2

> The server MUST include a value in the ":authority" pseudo-header
>   field for which the server is authoritative (see Section 10.1).  A
>   client MUST treat a PUSH_PROMISE for which the server is not
>   authoritative as a stream error (Section 5.4.2) of type
>   PROTOCOL_ERROR.

**Comment by tatsuhiro-t** [comment]
.. thus this is expected behavior.  If doubt, please ask Firefox dev.

**Comment by rfmcpherson** [comment]
Thanks for the response!

I don't think that's the issue. If that were the case, I think the main page would not have gotten through. Looking at the push headers, the authority is the from the requested domain, not the proxy's.

That being said, the issue was on my end. Changing the path to the full URL instead of just "/style.css" allowed me to inject the push request. As long as the path matches the requested :scheme and :authority, it works.

Here's my correct code (for future posterity's sake):  

    import io
    import nghttp2
    import ssl
    
    class Handler(nghttp2.BaseRequestHandler):
    
        def on_headers(self):
            url =  self.scheme.decode('utf-8') + "://"
            url += self.host.decode('utf-8')
    
            pr = self.push(
                path=url+"/style.css", body="body{background-color:green}", 
                status=200)
            self.send_response(
                body='<html><link rel="stylesheet" type="text/css" href="style.css">Hello world! <br/> This is "{}"</html>'.format(url), 
                status=200) 
    
    
    ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    ctx.options = ssl.OP_ALL | ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3
    ctx.load_cert_chain('./cert/server.crt', './cert/server.key', password="1234")

    server = nghttp2.HTTP2Server(('0.0.0.0', 8080), Handler, ssl=ctx)
    server.serve_forever()
