### ISSUE TITLE
licensing terms

### ISSUE THREAD

**Issue by LakhanRathi92** [tatsuhiro-t/nghttp2#376]
Hi 

I am not sure what licensing terms I am subjected to if I am using the nghttp2 or libnghttp2 libraries. 
Is it curl license only? 

Best
Lkum

**Comment by tatsuhiro-t** [comment]
MIT license. https://github.com/tatsuhiro-t/nghttp2/blob/master/COPYING

**Comment by LakhanRathi92** [comment]
Thank you.
