### ISSUE TITLE
Option to disable the use of AES-NI in h2load?

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#377]
Hi,

in [open|libre|boring]ssl, you can disable the usage of AES-NI by setting OPENSSL_ia32cap="~0x200000200000000", e.g.

> OPENSSL_ia32cap="~0x200000200000000" openssl speed -elapsed -evp aes-128-gcm

Is there a way to make use of this in h2load?

**Comment by tatsuhiro-t** [comment]
If OPENSSL_ia32cap is recognized by OpenSSL library, then I think setting it as environment variable to h2load is enough, and it should work.  Have you tried that?

**Comment by 0x64616E69656C** [comment]
Yeah, I tried that, it doesn't make a difference in duration & req/s (aes-128-gcm/aes-256-gcm), whereas I think it should.

**Comment by tatsuhiro-t** [comment]
c71c357fa67e310fb38d978eb09cf4cc194bb1a2 may make OPENSSL_ia32cap effective.
I could not validate it since my cpu has no AES-NI (yeah, old core2duo..)
BTW, the added function call does nothing in boringssl.

**Comment by 0x64616E69656C** [comment]
I'm gonna close this one for now, I'm currently under a sh*tload of work, and it turns out there are a few issues with boringssl, especially performance wise, which I can't pursue ATM :-(
