### ISSUE TITLE
Better logging for disabled TLS-versions

### ISSUE THREAD

**Issue by prauscher** [tatsuhiro-t/nghttp2#388]
currently, when trying to connect using TLSv1 to TLSv1-disabled server, nghttpx will close the connection without further notice and I receive "Network error: Success" in the nghttpx-log. An better option would be to reply with a TLS-Alert of FATAL PROTOCOL_VERSION (0x0246) and choose a "better" message for the log, possibly referencing to --tls-proto-list.

Log:

    14/Oct/2015:13:44:28 +0200 PID13592 [INFO] shrpx.cc:1826 Resolving backend address
    14/Oct/2015:13:44:28 +0200 PID13592 [INFO] shrpx.cc:139 Address resolution for ::1 succeeded: ::1
    14/Oct/2015:13:44:28 +0200 PID13592 [INFO] shrpx.cc:283 Listening on ::, port 9999
    14/Oct/2015:13:44:28 +0200 PID13592 [INFO] shrpx.cc:283 Listening on 0.0.0.0, port 9999
    14/Oct/2015:13:44:28 +0200 PID13592 [INFO] shrpx.cc:644 Entering event loop
    14/Oct/2015:13:44:31 +0200 PID13592 [INFO] shrpx_listen_handler.cc:213 [LISTEN:0x7f192e841c00] Accepted connection. fd=9
    14/Oct/2015:13:44:32 +0200 PID13592 [INFO] shrpx_client_handler.cc:108 [CLIENT_HANDLER:0x7f192e860200] Network error: Success
    14/Oct/2015:13:44:32 +0200 PID13592 [INFO] shrpx_client_handler.cc:282 [CLIENT_HANDLER:0x7f192e860200] Deleting
    14/Oct/2015:13:44:32 +0200 PID13592 [INFO] shrpx_client_handler.cc:315 [CLIENT_HANDLER:0x7f192e860200] Deleted

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  All we can do is get error message from OpenSSL, and log it.  Let's see what I can improve in this aspect.

**Comment by tatsuhiro-t** [comment]
Pulling error from OpenSSL error queue, we can log handshake error like this:
```
14/Oct/2015:22:27:33 +0900 PID13540 [INFO] shrpx_connection_handler.cc:295 [LISTEN:0x7ffce73795f0] Accepted connection. fd=12
14/Oct/2015:22:27:33 +0900 PID13540 [INFO] shrpx_connection.cc:354 tls: handshake libssl error: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
14/Oct/2015:22:27:33 +0900 PID13540 [INFO] shrpx_client_handler.cc:420 [CLIENT_HANDLER:0x62500000a100] Deleting
14/Oct/2015:22:27:33 +0900 PID13540 [INFO] shrpx_client_handler.cc:443 [CLIENT_HANDLER:0x62500000a100] Deleted
```
It seems that there is no easy way to know the specific reason why handshake was failed.

**Comment by tatsuhiro-t** [comment]
ed1e84fc0a438282f68f736c7bc7a9f34cb006d1 implements the above error logging.

**Comment by prauscher** [comment]
Great, thank you for the quick response! Maybe if you now add some sentence like `otherwise you will receive the error message "unknown protocol"` to the manpage for --tls-proto-list section, then greping and/or googling the error will point this out :)

**Comment by tatsuhiro-t** [comment]
All right, done via 41710bf

**Comment by prauscher** [comment]
Thank you! Marking this issue as closed then
