### ISSUE TITLE
PUT request is changed to POST

### ISSUE THREAD

**Issue by gpurrenhage** [tatsuhiro-t/nghttp2#389]
I am using nghttpx in --client mode, accepting HTTP/1.1 connections and translating them to HTTP/2.  This configuration was originally built out w/ shrpx and I am trying to drop nghttpx in instead.

What I'm seeing is that requests which arrive as PUT at the frontend of nghttpx are being changed to a POST by the time they reach the backend.  (This behavior was NOT present with shrpx)  The only other change to the request that I notice is an additional 'access-control-allow-origin' header being added. 

I've looked through the documentation and can't find any reason why nghttpx would be changing the request method.  I am happy to provide any additional details you need.

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this issue.
The issue that PUT is replaced with POST was a bug, and was fixed via e8c608a.
We don't add 'access-control-allow-origin' explicitly, so may be bug in HPACK encoder.
Could you give us how to reproduce this issue?  I'd like to know the original request headers.
If you use curl, please tell us the complete command-line options.

**Comment by tatsuhiro-t** [comment]
I thought that 'access-control-allow-origin' was added by nghttpx, but reading your comment twice, probably it is added in the original request, and not added by nghttpx.  If that is the case, the only issue is that PUT is replaced by POST, and was fixed in the above commit.

**Comment by gpurrenhage** [comment]
That update resolved the issue for me.  Thanks for the quick turnaround!

**Comment by tatsuhiro-t** [comment]
Thanks.  Let's close the issue.
