### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [tatsuhiro-t/nghttp2#391]
Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigaction.html "Change a signal action.") ⇒ [signal_set_handler](https://github.com/tatsuhiro-t/nghttp2/blob/f7fdb6503786fc6e4fc9ba5b34cf217debea6f31/src/shrpx_signal.cc#L94)
- [strdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html "Duplicate a string.") ⇒ [main](https://github.com/tatsuhiro-t/nghttp2/blob/338b4ba7396816323da30f9f69c77c8fa723bcfa/src/shrpx.cc#L1659)

**Comment by tatsuhiro-t** [comment]
Thank you for pointing this out.  Fix committed via 85bc696

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/tatsuhiro-t/nghttp2/commit/85bc696c38ee8b980e1c694233edaa50f9c4a007 "More error handling").
