### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [tatsuhiro-t/nghttp2#394]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/tatsuhiro-t/nghttp2/blob/f7fdb6503786fc6e4fc9ba5b34cf217debea6f31/src/nghttpd.cc#L173 "main() function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "Uncaught exceptions") like they are described by Danny Kalev?

**Comment by tatsuhiro-t** [comment]
Thank you for pointing this out.
I've added exception handling code according to referenced article.  See 5594e3d

**Comment by elfring** [comment]
I would [also appreciate](http://stackoverflow.com/questions/8311457/are-destructors-called-after-a-throw-in-c "Are destructors called after a throw in C++?") the addition of [a catch-all clause](http://en.cppreference.com/w/cpp/language/try_catch "try-block").

**Comment by tatsuhiro-t** [comment]
We don't use exceptions in our code, so handling std::exception is enough for now.  May I be missing something?

**Comment by elfring** [comment]
Would you like to [care also for C++ exceptions](http://stackoverflow.com/questions/1824910/is-there-an-occassion-where-using-catch-all-clause-catch-is-justified "Is there an occassion where using catch all clause : catch (…) is justified?") which are not derived from the class "std::exception"?

**Comment by tatsuhiro-t** [comment]
I mean we don't use custom exceptions which do not inherit std::exception.

**Comment by elfring** [comment]
Can any plug-ins/add-ons throw an unexpected exception type eventually?

**Comment by tatsuhiro-t** [comment]
We have not any such mechanism at the moment.  But it could be future-proof.
This will be handled in "application template" we discussed in the other thread. Thanks!

**Comment by tatsuhiro-t** [comment]
Check out the latest master branch.  We did 1) catch-all 2) use "application template".
I think we can close this issue.

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/tatsuhiro-t/nghttp2/commit/eff3dfd50bb773086540f68c33ca62818b63310b#diff-4340a7a7e0f3827385601e75bb7accacR201 "Movement of exception handling code to one function").

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
