### ISSUE TITLE
h2load never completes when tested against caddy

### ISSUE THREAD

**Issue by Lukasa** [tatsuhiro-t/nghttp2#397]
As you know, earlier this evening I was profiling Hyper-h2 using h2load to get a feel for how fast it went. One of my twitter followers wanted to see a comparison with Caddy, a HTTP/2 server written in Go, so I attempted to compare it. However, h2load never completed, instead hanging forever around 90%:

```
$ h2load -n100000 -c100 -m10 https://localhost:2015/twisted-server.py
starting benchmark...
spawning thread #0: 100 concurrent clients, 100000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
acprogress: 70% done
progress: 80% done
progress: 90% done
```

I installed caddy by running `go get github.com/mholt/caddy`. I'm using `go version go1.5.1 darwin/amd64`. I'm also using the following Caddyfile:

```
localhost

browse
tls server.crt server.key
```

where `server.crt` is a self-signed certificate.

It's not immediately clear to me whether this is h2load's fault or Caddy's fault, but I thought I'd get more success opening the issue here first, as we can probably more effectively debug what's going wrong first. If it turns out to be Caddy's fault, we can open an issue on their repository.

**Comment by Lukasa** [comment]
Aha, I turned on error logging in caddy and got this: `20/Oct/2015:08:48:54 +0000 [ERROR 503 /twisted-server.py] open twisted-server.py: too many open files`. I suspect that's the core problem, so I'll raise this over at caddy.

**Comment by Lukasa** [comment]
In fact, I think this is fundamentally a dupe of mholt/caddy#15, so I'm not going to bother considering it a caddy bug.

**Comment by Lukasa** [comment]
Oh, maybe not. Raising the ulimit removes those errors, but h2load still fails to complete.

**Comment by Lukasa** [comment]
Hmm. For now I'm going to disregard Caddy: I believe it's at fault here, it seems to be hanging on I/O, but without better diagnostic output I'm not really able to pin-down what's going on.

**Comment by tatsuhiro-t** [comment]
I found that this is a bug in go http2 package. I have a patch to fix this.  Will raise an issue in golang repo, and submit code review.
BTW, it seems that go uses all cpu cores since go 1.5 release by default.  So it is unfair to compare it to other single threaded server if you want similar condition.

**Comment by Lukasa** [comment]
@tatsuhiro-t Nicely done! Do you mind linking the bug from here?

Yeah, I know that Go uses all the CPU cores. For now, I'm ok with that: I'll worry about nailing down that kind of testing later.

**Comment by tatsuhiro-t** [comment]
No.  Will paste here as soon as I did.

**Comment by tatsuhiro-t** [comment]
https://github.com/golang/go/issues/12998

**Comment by mholt** [comment]
Currently caddy's http2 lib can leak goroutines when slammed with requests. This is fixed upstream in Go tip, but won't make it into Caddy until next month, probably.

Excellent job finding the frame transmission failure though -- this should help improve things quite a bit!
