### ISSUE TITLE
How to build command-line tools

### ISSUE THREAD

**Issue by raptortech-js** [tatsuhiro-t/nghttp2#398]
I apologize for the question, I'm sure I'm missing something obvious. I just can't seem to find the command line tools when I build nghttp2. I've tried building from both HEAD and the 1.3.4 release, on both the AWS Linux AMI and OS X Yosemite. There are a bunch of .o files, so I'm pretty sure the library is getting built, but I'm looking for an nghttpx executable, and I can't seem to find it anywhere. I'm pretty sure the 1.3.4 release is supposed to include the compiled executables, but I can't seem to find them. What am I doing wrong?

**Comment by tatsuhiro-t** [comment]
There are several third party libraries to build command-line tools and nghttpx.
We need at least:

*    OpenSSL >= 1.0.1
*    libev >= 4.15
*    zlib >= 1.2.3
*    Also jemalloc is recommended.

https://nghttp2.org/documentation/package_README.html#requirements describes the dependencies.

We need development package for these libraries.
When configure script is executed, it prints out configuration summary, including detected libraries.
Could you share this summary output?

**Comment by raptortech-js** [comment]
Thanks for that! When I went to examine the config summary, I actually realized I didn't have all the libraries needed. I installed those, plus g++, though I still had to do `export CXXFLAGS="-std=c++11"` to get it to work. I'm still having some sort of an issue with not being able to open libnghttp2.so.14, but that's a separate issue.

**Comment by tatsuhiro-t** [comment]
It is a bit strange since -std=c++11 is automatically added by configure script if compiler supports it.

**Comment by raptortech-js** [comment]
Hmm. When I try it now, it works as you say, and so even when CXXFLAGS is unset `./config` will show `-std=c++11` in its report. I suspect that I ran `./config` before installing g++, and so that flag was not supported, and then forgot to run it again after.
