### ISSUE TITLE
nghttp2_session_resume_data returns -501

### ISSUE THREAD

**Issue by fmoraes74** [tatsuhiro-t/nghttp2#399]
My server implementation runs into the problem when my internal data callback is called when there is more data available to read from the source server. Normally, this all works well and I am able to send the initial headers and some data, but occasionally, under a heavier load of requests, I get error -501 (NGHTTP2_ERR_INVALID_ARGUMENT) from the call to nghttp2_session_resume_data.

My code has an internal state knowing whether it sent the initial headers and data. If this is the first time around, we send the headers+data. If we are being called as new data has arrived, I use the session resume to attempt to send more data, but I hit this error code occasionally.

Any suggestion on how to find what I am doing wrong and solve the issue?

**Comment by tatsuhiro-t** [comment]
nghttp2_session_resume_data returns NGHTTP2_ERR_INVALID_ARGUMENT when:
*  The stream does not exist; or no deferred data exist.

In your case, you can ignore this error.  When I first designed this function, I thought that it is better to tell application more details about failure.  But this failure case leaks implementation details, which application might not need to care about.  I'll make this function not return this error code in the next release to reduce noise.

**Comment by fmoraes74** [comment]
Well, the issue I am having is that the library is always giving me that return error code even after I call it after each cycle of my read notification being called. From looking at the debugger, the following condition is happening:

  if (stream == NULL || !nghttp2_stream_check_deferred_item(stream)) {
    return NGHTTP2_ERR_INVALID_ARGUMENT;
  }

And inside nghttp2_stream_check_deferred_item is returning false because stream->item is not NULL and stream->flags is 0.

Any thoughts on how can I get out of this state?

**Comment by tatsuhiro-t** [comment]
nghttp2_stream_check_deferred_item returns nonzero (true) if its stream is choked by flow control or application returns NGHTTP2_ERR_DEFERRED from nghttp2_data_source_read_callback.
In other words, as long as there is data to send, it returns false.
This is completely implementation detail of libnghttp2.  It is harmless to ignore  NGHTTP2_ERR_INVALID_ARGUMENT from nghttp2_session_resume_data now.

**Comment by fmoraes74** [comment]
I was able to fix my code problem but it seems like I depend on the error being returned now. If you remove that return code, would there be a way to know this was why no data was processed (other than having my data read callback set a flag) ?

**Comment by tatsuhiro-t** [comment]
OK, I leave this return value as is if it serves some purpose.

**Comment by fmoraes74** [comment]
Thanks. I will let you know if I hit an issue again, so I am closing this.
