### ISSUE TITLE
running nghttpd alongside nginx behind nghttpx / issues & feature requests

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#402]
Hi,

I wanted to achieve something like this:

vhost1, vhost2 -> tls/h2 -> nghttpx -> http2, notls -> nghttpd as backend serving static content

catchall -> tls/h2 -> nghttpx -> http1, notls -> nginx as backend serving dynamic content
(_I don't think it would be any improvement by using nginx with h2/tls enabled behind nghttpx, in fact rather the opposite, cpu and latency wise?_)

I tried:

> nghttpx.conf
```
backend=127.0.0.1:8888;host1:host2:host3 // nghttpd
backend=127.0.0.1:8000 // catchall, nginx
http2-bridge // required for talking http2 to nghttpd, but breaks nginx (only h2 over tls)
backend-no-tls // required for both backends
```

#### issues
- enabling http2 bridge breaks connection to backend nginx
- specifying multiple vhosts (like nghttp2.org:www.nghttp2.org) creates duplicate content - e.g. if you want to redirect traffic von nghttp2 to www.nghttp2.org there's no way for that when using nghttpd as a backend
- there seems to be no way to teach nghttpd content-types, so it spits out html/css/js as plaintext (wanted to use it this as CDN and sites generated by gohugo)

#### feature requests
- would it be possible to specify http2-bridge/backend-no-tls per-backend?
- are there any plans to improve nghttpd with config & init files, implement content types for static file types and implement basic site-configurations including vhosts  & 301 redirect functions?

Thanks in advance!

**Comment by tatsuhiro-t** [comment]
nghttpx only supports one type of backend at the moment.  And --http2-bridge completely turns off HTTP/1 support in backend.
I think it is not possible to support both protocol in backend (it needs careful review of code base, since most of the code assumes one protocol), but usually backend connections have lower latency, and in that situation, HTTP/1 is not so bad for static content delivery.

Now that nginx supports HTTP/2, putting nginx at the front is viable option.  Comparing nginx and nghttpx, nghttpx has more robust TLS futures such as asynchronous resumption, session ticket rotation, SPDY, and NPN. It also has more stable HTTP/2 implementation, server push is also supported.  nginx, on the other hand, is battle tested web server, and lots of options, and extension modules.  Latency wise, fewer servers have the advantage.

I'd like to make nghttpd as simple as possible, because it is somewhat suitable for debugging purpose rather than production server.  But I think it would be good to add content-type support.
We can use https://mimesniff.spec.whatwg.org/ to sniff content-type from file.

**Comment by 0x64616E69656C** [comment]
Ok, thanks for clearing that up.

>Comparing nginx and nghttpx, nghttpx has more robust TLS futures such as asynchronous 
> resumption, session ticket rotation, SPDY, and NPN. It also has more stable HTTP/2 implementation, 
> server push is also supported.

That's exactly why I'm using (and will keep doing so ;) nghttpx as TLS offloader and http2 proxy - we've had a huge performance gain compared to nginx (up to 1.6?) as frontend webserver with TLS enabled.

I just thought, hey, why not gaining a few extra ms by talking http2 to the backend server, w/o TLS and just for serving static content. I'll make some benchmarks with ```nghttpx -> h2+tls -> nginx``` vs ```nghttpx -> h1 -> nginx``` and decide then whether to keep things as they are or switch to http2-bridge with nginx as backend.

I can understand the nghttpd situation, so I'll close that as wont-fix :-)

**Comment by tatsuhiro-t** [comment]
Making nghttpx serve static content is another option.  We have mruby extension support, and it already return custom response without requesting backend server (but no file I/O support, since it requires third-party mrbgem).

**Comment by tatsuhiro-t** [comment]
Yeah, benchmarking result is very interesting.  Probably you need to tweak flow control options so that it does not choke the transfer speed: 

*  --backend-http2-window-bits=<N>
*  --backend-http2-connection-window-bits=<N>

In my opinion, default --backend-http2-connection-window-bits value 64K is too small.

**Comment by 0x64616E69656C** [comment]
> Making nghttpx serve static content is another option

I thought about that too, also the possibility to handle redirects of virtual hosts, but I think it would be better to keep proxy server & application/content-server apart from each other.
And file I/O is very delicate :)

I'll try nginx http2 tomorrow.

**Comment by tatsuhiro-t** [comment]
Thanks.  I forget to mention that --backend-http2-connections-per-worker option.  You may want to increase this.  In my experience, too many connection will result lower performance.

**Comment by 0x64616E69656C** [comment]
Quick benchmark, h2load/nghttpx 1.3.4 release against nginx 1.9.5+brotli+h2, simple hello world on localhost w/o fiddeling with window-bits:

> http2-bridge / insecure on nghttpx
> http2 ssl on nginx

```
starting benchmark...
spawning thread #0: 1 concurrent clients, 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 6.19s, 1616.73 req/s, 99.55KB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 10000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 630525 bytes total, 320495 bytes headers, 130000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      327us     11.34ms       599us       156us    97.07%
time for connect:     8.25ms      8.25ms      8.25ms         0us   100.00%
time to 1st byte:    17.73ms     17.73ms     17.73ms         0us   100.00%
```


> talking unencrypted http1 with nginx backend

```
spawning thread #0: 1 concurrent clients, 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 3.86s, 2593.94 req/s, 760.06KB/s
requests: 10000 total, 10000 started, 10000 done, 0 succeeded, 10000 failed, 0 errored, 0 timeout
status codes: 0 2xx, 0 3xx, 10000 4xx, 0 5xx
traffic: 3000452 bytes total, 180422 bytes headers, 2640000 bytes data
                     min         max         mean         sd        +/- sd
time for request:      250us       732us       369us        83us    60.87%
time for connect:     6.62ms      6.62ms      6.62ms         0us   100.00%
time to 1st byte:     7.37ms      7.37ms      7.37ms         0us   100.00%
```

> h2load against nginx directly:

```
starting benchmark...
spawning thread #0: 1 concurrent clients, 10000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-RSA-AES256-GCM-SHA384
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 1.11s, 8987.6 req/s, 2.47MB/s
requests: 10000 total, 10000 started, 10000 done, 10000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 0 2xx, 10000 3xx, 0 4xx, 0 5xx
traffic: 2880049 bytes total, 920000 bytes headers, 1780000 bytes data
                     min         max         mean         sd        +/- sd
time for request:       87us       351us        99us         7us    96.84%
time for connect:     7.80ms      7.80ms      7.80ms         0us   100.00%
time to 1st byte:     8.17ms      8.17ms      8.17ms         0us   100.00%
```

The last one's a bit surprising though...

**Comment by tatsuhiro-t** [comment]
Direct connection tends to be faster.
The interesting thing is that header compressor in nginx does not compress headers much: see 1,400,000 vs 320,495.

**Comment by LPardue** [comment]
> The interesting thing is that header compressor in nginx does not compress headers much

Yes very interesting.

Ignoring HPACK, is there difference in the response headers fields between tests? Or does your nghttpx pass them through unmodified?

**Comment by tatsuhiro-t** [comment]
nghttpx usually passes all headers from backend to frontend except for the banned header field in HTTP/2 (e.g., connection, transfer-encoding) if frontend is HTTP/2.  For all frontend protocols, nghttpx will add proxy related headers like "via".

**Comment by tatsuhiro-t** [comment]
FYI, f29ccc9c208fd67749a7a1a3accc1ad871c2962d adds content-type support to nghttpd.
