### ISSUE TITLE
nghttpx sending http/2 to backend in default mode with --frontend-no-tls and --accept-proxy-protocol

### ISSUE THREAD

**Issue by mstaudinger** [tatsuhiro-t/nghttp2#406]
I'm testing nghttpx in several scenarios.

Stand-alone, default mode works as expected, accepting http2 connections on the frontend, and passing along http/1.1 requests to the defined backend.

I am also testing with an upstream TLS proxy, using nghttpx with similar config but adding the --frontend-no-tls and --accept-proxy-protocol settings.  NPN is used to steer h2 traffic to nghttpx, using the PROXY v1 protocol. However, in this instance, nghttpx sends the following to the backend when the connection is made:

>"PRI * HTTP/2.0"

Since the backend is not http2-capable, this cannot be responded to appropriately.  Output of nghttp -nv below.

>[  0.009] Connected
>[  0.055][NPN] server offers:
>          * h2
>          * http/2
>          * spdy/2
>          * http/1.1
>The negotiated protocol: h2
>[  0.101] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
>          (niv=2)
>          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
>          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
>[  0.101] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
>          (dep_stream_id=0, weight=201, exclusive=0)
>[  0.101] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
>          (dep_stream_id=0, weight=101, exclusive=0)
>[  0.101] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
>          (dep_stream_id=0, weight=1, exclusive=0)
>[  0.101] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
>          (dep_stream_id=7, weight=1, exclusive=0)
>[  0.102] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
>          (dep_stream_id=3, weight=1, exclusive=0)
>[  0.102] send HEADERS frame <length=37, flags=0x25, stream_id=13>
>          ; END_STREAM | END_HEADERS | PRIORITY
>          (padlen=0, dep_stream_id=11, weight=16, exclusive=0)
>          ; Open new stream
>          :method: GET
>          :path: /
>          :scheme: https
>          :authority: www.testhost.net
>          accept: */*
>          accept-encoding: gzip, deflate
>          user-agent: nghttp2/1.3.4
>Some requests were not processed. total=1, processed=0

Is this expected behavior?  This is my ideal use case (upstream TLS with NPN) but I need nghttpx to speak only http/1.1 to the backend in this mode.

**Comment by tatsuhiro-t** [comment]
First make sure that --http2-bridge, --client or --client-proxy option does not appear configuration or command-line.  They make backend traffic HTTP/2.
Meanwhile, I'll check that --accept-proxy-protocol works properly.

**Comment by tatsuhiro-t** [comment]
In my environment, both --accept-proxy-protocol and --frontend-no-tls works fine with default mode, and nghttpx sends HTTP/1.1 request to the backend.

**Comment by mstaudinger** [comment]
This is the config.  proxy protocol works (backend sees the right client IP, not the upstream TLS proxy,) but receives the http2 "PRI *" command.

command-line
`nghttpx --conf=/usr/local/etc/nghttpx.conf -D --add-x-forwarded-for --frontend-no-tls`

Contents of nghttpx.conf
>user=www
>npn-list=h2,h2-16,h2-14,spdy/3.1
>accesslog-file=/var/log/nghttpx
>accesslog-format='$remote_addr ${http_x_forwarded_for} $alpn $request_time [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
>no-via=1
>frontend=127.0.0.1,444
>backend=127.0.0.1,80
>frontend-no-tls=1
>accept-proxy-protocol=1

**Comment by tatsuhiro-t** [comment]
> no-via=1
> ...
> frontend-no-tls=1
> accept-proxy-protocol=1

Specifying "1" does not work.  "yes" must be used to enable these options.

**Comment by mstaudinger** [comment]
Many thanks, I had missed that in the docs.  I am now able to proxy properly by handling TLS upstream and passing along via PROXY to nghttpx.

I do notice that even if adding the field "$http_host" to the log format, it is not logged.  Here's a sample log file and the format definition.

`accesslog-format=$remote_addr $request_time [$time_local] $http_host "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"`

>1.2.3.4 0.001 [28/Oct/2015:05:43:56 -0400] - "GET /assets/images/footer.gif HTTP/2" 304 0 "https://www.hostname.net/assets/css/homestyle.css" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:41.0) Gecko/20100101 Firefox/41.0"

**Comment by tatsuhiro-t** [comment]
HTTP/2 request usually does not contain Host header field in favor of :authority pseudo header field.
Do you think it would be better to handle this case specially, and log the content of :authority header field?

**Comment by mstaudinger** [comment]
Yes, I think In the case of a proxy serving multiple host names it would be very useful to log the :authority header for each request.  Especially with --frontend-no-tls as nghttpx does not have access to the SNI or ssl_session_id any longer.

**Comment by tatsuhiro-t** [comment]
I just pushed commit d9f73c3 to log :authority if host is missing

**Comment by mstaudinger** [comment]
Works well so far - I am manually specifying $http_host in the log format.  Much appreciated!

**Comment by tatsuhiro-t** [comment]
OK, closing now.
