### ISSUE TITLE
Show incoming proxy connection's HTTP version?

### ISSUE THREAD

**Issue by nutinshell** [tatsuhiro-t/nghttp2#408]
I got a H2 proxy with nghttpx, it accepts both http/2 or http/1.1 proxy requests, is that possible to log proxy connection HTTP version(to determine only Chrome's http/2 proxy connection)? I try -L INFO, but it seems show no useful info.

**Comment by tatsuhiro-t** [comment]
We have several access log variables
https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx--accesslog-format

For example, $request contains version information.
For SSL/TLS connections, $alpn contains negotiated protocol ID (e.g., http/1.1 or h2).

**Comment by nutinshell** [comment]
Thanks, that's it!
