### ISSUE TITLE
'make check' no longer works if configured with --disable-static

### ISSUE THREAD

**Issue by kdudka** [tatsuhiro-t/nghttp2#410]
```
./configure --disable-static
make check
```
results in a build failure while linking ```tests/main```:
```
make[3]: Entering directory '/tmp/nghttp2-1.4.0/tests'
  CC       main.o
  CC       nghttp2_pq_test.o
  CC       nghttp2_map_test.o
  CC       nghttp2_queue_test.o
  CC       nghttp2_test_helper.o
  CC       nghttp2_frame_test.o
  CC       nghttp2_stream_test.o
  CC       nghttp2_session_test.o
  CC       nghttp2_hd_test.o
  CC       nghttp2_npn_test.o
  CC       nghttp2_helper_test.o
  CC       nghttp2_buf_test.o
  CCLD     main
main.o: In function `main':
/tmp/nghttp2-1.4.0/tests/main.c:54: undefined reference to `nghttp2_enable_strict_preface'
nghttp2_pq_test.o: In function `check_nodes':
/tmp/nghttp2-1.4.0/tests/nghttp2_pq_test.c:180: undefined reference to `nghttp2_pq_top'
/tmp/nghttp2-1.4.0/tests/nghttp2_pq_test.c:183: undefined reference to `nghttp2_pq_pop'
nghttp2_pq_test.o: In function `test_nghttp2_pq':
/tmp/nghttp2-1.4.0/tests/nghttp2_pq_test.c:61: undefined reference to `nghttp2_mem_default'
/tmp/nghttp2-1.4.0/tests/nghttp2_pq_test.c:61: undefined reference to `nghttp2_pq_init'
/tmp/nghttp2-1.4.0/tests/nghttp2_pq_test.c:62: undefined reference to `nghttp2_pq_empty'
/tmp/nghttp2-1.4.0/tests/nghttp2_pq_test.c:63: undefined reference to `nghttp2_pq_size'
[...]
```
This used to work prior to ce74a309.

**Comment by tatsuhiro-t** [comment]
We hide private symbols recently, and unit test links to libnghttp2.so in this case, so this error.
As a workaround, we can create intermediate library to use in unit test to offer private symbols.

**Comment by kdudka** [comment]
Do you mean to build each object file twice (with/without symbol hiding)?

Alternatively we could just modify the failing target(s) in tests/Makefile.am to link the needed object files directly, instead of linking the library.

**Comment by tatsuhiro-t** [comment]
> Do you mean to build each object file twice (with/without symbol hiding)?

I meant no, but it turns out that with libtool we have to compile files twice..

> Alternatively we could just modify the failing target(s) in tests/Makefile.am to link the needed object files directly, instead of linking the library.

Can we do this without duplicating source file list into tests/Makefile.am?

If creating static library is not a problem, then create both shared and static libraries and run tests, and just pick up shared thing would be easiest.

**Comment by kdudka** [comment]
The above patch fixes it.  It is probably not an absolutely sane solution, but it fixes the problem and it does not affect builds without --disable-static.

**Comment by tatsuhiro-t** [comment]
Thank you.  I think the PR is good enough for the workaround.

**Comment by kdudka** [comment]
Great.  Thank you for merging it!
