### ISSUE TITLE
Building libnghttp2 with MSVC

### ISSUE THREAD

**Issue by josmad** [tatsuhiro-t/nghttp2#416]
I tried using the included Makefile.msvc but it depends heavily on linux/cygwin tools. Trying to run the build in a cygwin prompt results in CL not being able to find the standard library headers.

I see others mentioning creating their own CMake configurations. I have no experience using CMake, if this is the way to go, any help is appreciated and removal of the msvc makefile would nice...

**Comment by SteffenAL** [comment]
For building with Makefile.msvc, Have a look at https://www.apachelounge.com/viewtopic.php?p=31514#31514

Works fine and is included in Apache 2.4.17 from Apachelounge. Have change $ ./configure --disable-shared to $ ./configure

**Comment by tatsuhiro-t** [comment]
I also don't know much about cmake either.  If someone contributes cmake support, then we'll happy to merge it.

**Comment by josmad** [comment]
@SteffenAL Thanks, I got it to build using the provided link.
