### ISSUE TITLE
When I am trying to make "POST" call with generator callback, all my client requests are getting closed with error_code 0x2

### ISSUE THREAD

**Issue by rameshrajagopal** [tatsuhiro-t/nghttp2#417]
Hi, 

I am trying to make a POST call to the server and pass 1k data using generator callback. Request is reaching server but before even I receive the response on the client, the client is getting status code of 0x2 and the request is getting closed. 

Any pointers, how to make POST call ? 
https://github.com/rameshrajagopal/nghttp2_asio_example/blob/master/client/nghttpclient.cpp

Regards,
Ramesh

**Comment by tatsuhiro-t** [comment]
MASTER_NODE_URI is undefined in this code, but make sure that it is absolute URI (e.g., "https://localhost/"), rather than "/".

**Comment by rameshrajagopal** [comment]
MASTER_NODE_URI is defined as absolute URI in 
https://github.com/rameshrajagopal/nghttp2_asio_example/blob/master/common/config.h

The call is working for normal usecase. it doesn't work if i want to test for 100 concurrent connections and requests. I smell there is a problem of using data_generator callback in my client. Not sure, please let me know how can I use POST with some data. 

There is write_trailer() call, when exactly should i use this, any example would be much appreciated. 

Thanks,
Ramesh

**Comment by tatsuhiro-t** [comment]
Yeah, I found a problem in data_generator.
https://github.com/rameshrajagopal/nghttp2_asio_example/blob/50bbcce43352cdcc77a8a39fa26c8938a2ccf05e/client/nghttpclient.cpp#L140

You should not write more than len bytes to buf.  It seems REQUEST_SIZE bytes are always written.
This is not guaranteed to work if flow control window gets small and len < REQUEST_SIZE.

**Comment by rameshrajagopal** [comment]
will try out and if i see any issues, i will reopen, for now closing this
