### ISSUE TITLE
openssl, boost-asio and SSLv3_method()

### ISSUE THREAD

**Issue by 0x64616E69656C** [tatsuhiro-t/nghttp2#419]
Hi,

debian recently began to remove SSLv3 and all API functions out of openssl (since 1.0.2d-3), which breaks boost-asio (1.58.0.1), see: http://anonscm.debian.org/viewvc/pkg-openssl/openssl/tags/1.0.2d-3/debian/patches/disable_sslv3_test.patch?view=log

```
  CXX      libnghttp2_asio_la-asio_common.lo
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from ../src/includes/nghttp2/asio_http2.h:37,
                 from asio_common.h:32,
                 from asio_common.cc:25:
/usr/include/boost/asio/ssl/impl/context.ipp: In constructor 'boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)':
/usr/include/boost/asio/ssl/impl/context.ipp:93:29: error: '::SSLv3_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv3_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:96:29: error: '::SSLv3_client_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv3_client_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:99:29: error: '::SSLv3_server_method' has not been declared
     handle_ = ::SSL_CTX_new(::SSLv3_server_method());
                             ^
Makefile:2017: recipe for target 'libnghttp2_asio_la-asio_common.lo' failed`
```

Is it possible to work around this in nghttp2, or do we have to wait until the API call is fixed in boost?

Thanks!

**Comment by tatsuhiro-t** [comment]
I don't think we can workaround this in nghttp2 code, since SSLv3_method use is hard-coded in boost asio header without any #ifdef guard.
So sadly, we have to wait for boost asio debian package update.  Apparently, there is no debian bug for boost?

**Comment by 0x64616E69656C** [comment]
The upgrade was pushed last night, so I guess I was the first one to bump into this issue. Though I agree with this approach in general, they should've checked first if there were any dependencies left, I guess boost is not alone in this. I'll just wait for boost to be fixed ;-)

**Comment by tatsuhiro-t** [comment]
I've just upgrade libssl-dev to 1.0.2d-3, and now I could not build asio lib anymore too ;)

**Comment by tatsuhiro-t** [comment]
For Debian sid, installing latest libboost1.58-dev fixes this issue.
