### ISSUE TITLE
nghttpx: optional verify host name

### ISSUE THREAD

**Issue by devlearner** [tatsuhiro-t/nghttp2#420]
Hi Tatsuhiro,

Is it possible to specify an optional peer hostname for backend ssl cert verification
so that, eg, I could specify `-b` with a dotted ip but also a host name so that cert verification won't fail?

For example, the current syntax for the backend option is:
`-b, --backend=(<HOST>,<PORT>|unix:<PATH>)[;<PATTERN>[:...]]`

If I specify the backend by ip, like ` -b 106.186.112.116,443`, it will fail when nghttpx verifies the backend server's certificate (by default), since the dotted ip won't match any of the domain names on the cert (nghttp2.org). [A workaround is to use `-k, --insecure` option to suppress verification altogether, which is apparantly not recommended for sake of security.]

Adding a bit to the complexity, the `--backend` option could be specified multiple times. I was thinking like:

Ideally, we could expand the option a little bit, like:
`-b, --backend=(<HOST>,<PORT>|unix:<PATH>)[,<VERIFY HOST>][;<PATTERN>[:...]]`
so that we could specify an optional hostname to use in ssl verify.

Or a simplier way to go, an extra option similar to 
>--backend-tls-sni-field=\<HOST\>
>Explicitly set the content of the TLS SNI extension. This will default to the backend HOST name.

something like `--backend-tls-verify-host` so that it would apply to all backends.

How do you think about the idea?

Thanks in advance

**Comment by tatsuhiro-t** [comment]
I think we should use the hostname specified in --backend-tls-sni-field to verify certificate from backend, but current we don't.
Do you think doing this fixes this issue?

**Comment by tatsuhiro-t** [comment]
With 9b18e47, nghttpx uses --backend-tls-sni-field to verify certificate from backend

**Comment by devlearner** [comment]
Using the tls sni host name to verify cert makes sense ;)
but of course i'm just raising this as a suggestion
(in my use case i could fiddle with my local dns instead so it's not really an issue)
um... i'm not entirely sure myself; sounds like a good idea to use sni [but anyway there's no rush to move ;)]

**Comment by devlearner** [comment]
oh, thanks for the quick fix!

**Comment by tatsuhiro-t** [comment]
I think when we send SNI, then we should use it to verify certificate hostname since, that is the hostname we are going to connect and authenticate.  Fix is very simple, as you know, so it is worth doing.

**Comment by devlearner** [comment]
Yeah, basically that's what SNI is designed for --- to solve cert issues ;)
nghttpx is doing a better job again
