### ISSUE TITLE
Plain server without tsl, when I am trying to connect from google chrome, getting ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by rameshrajagopal** [tatsuhiro-t/nghttp2#424]
Hi, 

I am just trying to access my simple server via google-chrome but it returns ERR_EMPTY_RESPONSE
my server code is placed 
https://github.com/rameshrajagopal/nghttp2_asio_example/blob/master/server/server.cpp

Please let me know how can I access my server via browser 

Regards,
Ramesh

**Comment by tatsuhiro-t** [comment]
Chrome only supports HTTP/2 over TLS.  You have to configure HTTP/2 server with TLS.

**Comment by rameshrajagopal** [comment]
Okay.
