### ISSUE TITLE
session on_error callback is not getting invoked when server crashes

### ISSUE THREAD

**Issue by rameshrajagopal** [tatsuhiro-t/nghttp2#426]
Client has registered for on_connect and on_error callbacks on a session. While client is requesting a service, its along loop, during this time, if server crashes or if you kill a server, client should get notification of this error, but currently i don't get any on_error callback, just io_service exits. 

client code 
https://github.com/rameshrajagopal/nghttp2_asio_example/blob/master/server/proxy_slave.cpp:111

Thanks,
Ramesh

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  I think ab1e8305a1dc967439acaaf3f6cbd02244464bc0 fixes this issue.

**Comment by tatsuhiro-t** [comment]
Please reopen if you still have this issue.
