### ISSUE TITLE
HTTP CONNECT requests failing to end

### ISSUE THREAD

**Issue by rfmcpherson** [tatsuhiro-t/nghttp2#428]
I'm trying to write a simple proxy with the Python bindings. However, I'm running into an issue with CONNECT requests. If an https link is the first request my proxy receives, I can respond with a 5xx status to close it. However, if it's a later request (like below), I'm unable to respond to the request in such a way to close it.

    #!/usr/bin/env python

    import asyncio
    import nghttp2
    import ssl

    ip = "127.0.0.1"
    port = 8080

    class Handler(nghttp2.BaseRequestHandler):

        def __init__(self, x, y):
            nghttp2.BaseRequestHandler.__init__(self, x, y)
            self.first = True
            self.b = b'<script src="https://here/test.js">'

        def on_headers(self):
            if self.path:
                print(self.method, self.host + self.path)
            else:
                print(self.method, self.host)
            
            if self.first:
                self.send_response(body=self.b, status=200)
                self.first = False
            else:
                self.send_response(status=426)

    def main():
        loop = asyncio.get_event_loop()

        # setup ssl
        ctx = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
        ctx.options = ssl.OP_ALL | ssl.OP_NO_SSLv2 | ssl.OP_NO_SSLv3
        ctx.load_cert_chain(
            './server.crt', './server.key', password="1234")

        server = nghttp2.HTTP2Server((ip,port), Handler, ctx)
        loop.run_forever()
        
    if __name__ == "__main__":
        main()

**Comment by tatsuhiro-t** [comment]
The reason is that Handler instance is created per stream.

**Comment by rfmcpherson** [comment]
Thanks for the response. If I change the if statement to check for `self.scheme`, it branches correctly, but the CONNECT stream still fails to close. Using Firefox's Network Monitor, it looks like it's not getting any response from the proxy.

**Comment by tatsuhiro-t** [comment]
It seems that we need to explicitly send RST_STREAM in this case.  
8481bc6 will do this.  But you need to specify body in self.send_response, otherwise stream hangs.

**Comment by rfmcpherson** [comment]
Thanks for the response. I really appreciate your help with this. 

When I test the latest version of nghttp2, it still doesn't work. The if statement in https://github.com/tatsuhiro-t/nghttp2/commit/b27b002a3f0fa47a7e9a8d0dfbcd6ee8abe9b3f3 is being traversed, but Firefox continues to expect a response and doesn't end the stream. I tried on FF 39.0.3 and FF-dev 44.0a2 both on Linux.

**Comment by tatsuhiro-t** [comment]
Please make sure that on_close is called.  If it was called, nghttp2 server thought that stream was closed.  Firefox might not give user clear indication about stream closure.  If that is the case, it is a Firefox issue.

**Comment by rfmcpherson** [comment]
on_closed is being called. Looks like the issue is with Firefox. Thanks
