### ISSUE TITLE
Priority of pushed streams

### ISSUE THREAD

**Issue by icing** [tatsuhiro-t/nghttp2#429]
Pushed streams alway depend on the stream they are initiated on and are given the default weight. I think it is up to the client to manipulate those dependencies, just like for any other stream.

However I would like to use a different initial weight, depending on the type (as param for example) of the resource pushed. 

What do you think?

**Comment by tatsuhiro-t** [comment]
There is several options I have in my mind.

1. add new nghttp2_submit_push_promise2() function which has nghttp2_priority_spec parameter.
    This is only useful if server knows the desired priority when sending PUSH_PROMISE.
    This may be true if we know the type of resource using "as" parameter of Link header field.

2. add new function to change priority without sending PRIORITY frame.
    Since server is a master mind of stream scheduling, it can do so without sending PRIORITY.
    We can do this using nghttp2_submit_priority but not sending frame, but we will call nghttp2_on_frame_send_callback for this, and it is strange since we didn't send it anyway.
    So we need new dedicated "stealth" API.
    This option is more generic, and it could bring more freedom to the app.

**Comment by tatsuhiro-t** [comment]
In generally, server could not assume the shape of the tree client constructed.  For pushed streams, server may just change the weight and leave the dependency as is, or create its own idle streams with higher (or lower) priority and make pushed streams depend on it, or just make it depend on the root stream with its custom weight.  @kazuho did another strategy in h2o.  h2o checks content-type, and if it is a critical resource (e.g., css), they are assigned "257" weight, and h2o sends them as fast as it can.

**Comment by igrigorik** [comment]
Both options seem reasonable. I like @kazuho's approach of looking at Content-Type, this seems like a good default strategy -- you need to know the headers anyway to send the push promise, right? On the other hand, the "stealth API" also enables new avenues for reprioritization on the server.. which seems generally useful.

**Comment by tatsuhiro-t** [comment]
Thank you for your comment.  In reverse proxy situation, I think we will send PUSH_PROMISE without knowing content-type; for example, "as" is not known in Link header field, or it is not given in configuration.  We will learn content-type from response header from backend server, but usually we don't wait for it, since we'd like to send PUSH_PROMISE before sending parent stream's response headers.  Also I think content-type is not part of PUSH_PROMISE, because it is a request, not response.  So we need to change priority after PUSH_PROMISE was sent, which means option 2 is more useful than 1.

**Comment by kazuho** [comment]
:+1 to option 2.

**Comment by tatsuhiro-t** [comment]
#430 adds function proposed in option 2 (stealth API version).
It is kinda very basic stuff.  This is like a offline version of re-prioritization of stream dependency usually we do when PRIORITY frame is received.
You can make stream depend any stream.  But weight is still in range [1, 256], so interleaving with parent stream is definitely possible if we make push stream depend parent stream's parent or one of ancestor.

**Comment by icing** [comment]
Excellent!

**Comment by tatsuhiro-t** [comment]
Thanks.  After adding some tests, I'll merge #430 into master.

**Comment by tatsuhiro-t** [comment]
#430 was merged just now.

**Comment by igrigorik** [comment]
> Thank you for your comment. In reverse proxy situation, I think we will send PUSH_PROMISE without knowing content-type; for example, "as" is not known in Link header field, or it is not given in configuration. We will learn content-type from response header from backend server, but usually we don't wait for it, since we'd like to send PUSH_PROMISE before sending parent stream's response headers. 

Right, makes sense.

:+1: for (2).

**Comment by tatsuhiro-t** [comment]
OK, everything has been done for this issue.  Let's close it.

**Comment by icing** [comment]
Thanks, and eagerly awaiting 1.4.1... ;-)

**Comment by tatsuhiro-t** [comment]
We just shipped 1.5.0.

**Comment by icing** [comment]
I just updated by documentation. ;-)

**Comment by cellscape** [comment]
Is it possible to somehow open idle stream and change it's priority? I want to try to group pushed streams in a way similar to http://bitsup.blogspot.se/2015/01/http2-dependency-priorities-in-firefox.html, however nghttp2_session_change_stream_priority works only with already opened streams and I basically need some way to create idle stream without sending anything to client. I can create those group streams by sending priority frame to client but it's kind of lame.

**Comment by tatsuhiro-t** [comment]
You can indirectly create idle stream given in nghttp2_priority_spec.stream_id.  This does not change the fact that you need existing stream ID to create idle stream.  After creating idle stream, you can change its priority using nghttp2_session_change_stream_priority().. but it sounds very tedious.
I would not mind to add new function, say, nghttp2_session_create_idle_stream, to create idle stream with dependency.

**Comment by cellscape** [comment]
> I would not mind to add new function, say, nghttp2_session_create_idle_stream, to create idle stream with dependency.

Such a function would be really useful to have. It seems that pushing with dependency priorities is more effective than weight priorities, and idle streams are required to easier group dependencies.

**Comment by tatsuhiro-t** [comment]
Sounds good.  Would you mind creating new issue for this?

**Comment by cellscape** [comment]
Done!

**Comment by tatsuhiro-t** [comment]
Thank you!

**Comment by tatsuhiro-t** [comment]
@icing I changed nghttp2_submit_push_promise so that stream object is created in that call via commit 2288ee8.
I admit the previous design is a bit tedious for server with the fast back pressure from backend stream.

**Comment by icing** [comment]
Oh, nice. That makes it more flexible to consider when there is a "best" time for a write. In Apache, there is a balance between writing less often (-> better performance) and writing more (-> less memory footprint). Having push streams handled automagically, makes the strategy simpler to adopt, I hope.

**Comment by acesso** [comment]
Hello,

Sorry for reopening this old issue but I could not find where in the code of nghttpx or startup parameter the Push priority can be altered since it is not defined by "as" on link  field. 
On my tests all pushed data are send after all data on ancestor resource even when the ancestor size is way bigger then the pushed ones. 

Thanks

**Comment by tatsuhiro-t** [comment]
We have not implemented functionality to change priority of pushed request in nghttpx.  I have some WIP branch for that, but I have not seen any difference with changing strategy, so I just keep it private.

And this thread is specifically for the adding functionality to change priority of streams to libnghttp2, not nghttpx, this thread should be kept closed.  If you want to track nghttpx priority thing, please open new issue.
