### ISSUE TITLE
stream lookup after push_promise

### ISSUE THREAD

**Issue by icing** [tatsuhiro-t/nghttp2#434]
I have the following sequence in my code:
```
    nid = nghttp2_submit_push_promise(...);
    s_push = nghttp2_session_find_stream(session->ngh2, nid);
    ASSERT(s_push);
```
which fails in ```master```. 

This is a test of the lookup, as ```nghttp2_session_change_stream_priority()``` fails with -501 on the promised stream. Could you have a look?

**Comment by tatsuhiro-t** [comment]
Its stream object is created during nghttp2_session_mem_send()/nghttp2_session_send() call.
We ensure that stream object is available in nghttp2_on_frame_send_callback.

To set priority, calling nghttp2_session_change_stream_priority() just before nghttp2_submit_response() for pushed stream is enough, because priority control is done for response HEADERS and DATA only.

**Comment by icing** [comment]
Ok, thanks for the explanation. I will then change my code accordingly and report back here...

**Comment by icing** [comment]
Ok, this works as you described. Thanks!

**Comment by icing** [comment]
Ok, 1-2 pushed promises on a stream allow me later during send to lookup the ```nghttp2_stream *``` objects, but I have one test html with 13 push promised and for them all lookups fail.

```
promised new stream 2 for GET /apache.org-files/defaulten.js on 13
promised new stream 4 for GET /apache.org-files/css.css on 13
...
promised new stream 26 for GET /apache.org-files/ant.jpg on 13
```
and shortly after:
```
h2_stream(1-2): lookup of nghttp2_stream failed
h2_stream(1-4): lookup of nghttp2_stream failed
...
```
The strange thing is that none of them works. So, I tested by varying push numbers:
1 push -> ok
2 pushes -> ok
3 pushes -> ok
4 pushes -> lookup 1-3 fails, 4 succeeds
5 pushes -> all fail
6 pushes -> all fail

tested against ```master``` from yesterday.

Anything I can do to resolve this, pls let me know.

**Comment by tatsuhiro-t** [comment]
I inserted assertion for nghttp2_session_find_stream lookup in nghttpx code, and all success for pushed streams.  I pushed 6 resources and all looks good.
Can I see your code?

**Comment by icing** [comment]
So you can blame this one me? Phhh.....

See [h2_session.c:line 1291 ff.](http://svn.apache.org/viewvc/httpd/httpd/trunk/modules/http2/h2_session.c?view=markup) for changing the priority, lines 1178 for call and h2_session_push at line 1233 for submitting the promise.

The logging of failed lookups is on line 1300.

**Comment by tatsuhiro-t** [comment]
No one blame you ;)

I think this could be a race condition.  As I wrote earlier, nghttp2_stream object for pushed stream is created during nghttp2_session_mem_send()/nghttp2_session_send() call.  You can ensure that PUSH_PROMISE is sent in nghttp2_on_frame_send_callback.
In your case, probably backend headers are received before PUSH_PROMISE is sent.
If submit_response() is called before PUSH_PROMISE is sent, looking up nghttp2_stream can fail.
The thing I'm not sure is getting response headers from backend takes some time, so usually sending PUSH_PROMISE is faster than that.  Of course, it depends on how the apache internal is setup.
So making sure that setting nghttp2_on_frame_send_callback and watching PUSH_PROMISE is sent  before submit_response() is called is a good debug operation for now.

**Comment by icing** [comment]
That explains it. Apache was too fast. ;-O

I now let nghttp2 write after every submit and stream lookups just work fine. Thanks for the quick (and always correct) help!

**Comment by jimjag** [comment]
LOL
