### ISSUE TITLE
Add new function to create idle streams

### ISSUE THREAD

**Issue by cellscape** [tatsuhiro-t/nghttp2#436]
I would like to somehow to open idle stream and change it's priority. I want to try to group pushed streams in a way similar to http://bitsup.blogspot.se/2015/01/http2-dependency-priorities-in-firefox.html, however nghttp2_session_change_stream_priority works only with already opened streams and I basically need some way to create idle stream without sending anything to client.

As discussed in #429, such a function can be potentially named nghttp2_session_create_idle_stream and could be used to create idle stream on server. Such idle stream could be later used as dependency for pushed streams.

**Comment by tatsuhiro-t** [comment]
Added nghttp2_session_create_idle_stream() in the referenced commit above.

**Comment by cellscape** [comment]
That was quick! Thanks, it works like a charm.
