### ISSUE TITLE
How to push multiple media segments serially during one push transaction? asio_http2_server

### ISSUE THREAD

**Issue by liuli9203** [tatsuhiro-t/nghttp2#438]
Hi all!
I want to implement one push strategy using asio_http2_server. The client firstly specify a list of media segments with one Get Request. Once receiving above request, the server should push the specified segments list serially, i.e., one after another, only one segment is being pushed each moment. 

My realizing idea is that invoking the on_close member function of the push response object and registering a callback function to trigger next push action. Can it work ? Can anyone give me a favor? Thank you so much !

Below is our current implementation, however, it cannot meet our demand since the segments are pushed concurrently.
<html/>
server.handle("/push",[](const request &req, const response &res)
{
&nbsp;&nbsp;	boost::system::error_code ec;
&nbsp;&nbsp;		std::vector<std::string> ArrRequests;
&nbsp;&nbsp;		for(auto &kv : req.header())
&nbsp;&nbsp;		{
&nbsp;&nbsp;&nbsp;&nbsp;			if(kv.first == "push-dash")
&nbsp;&nbsp;&nbsp;&nbsp;			{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;				boost::split(ArrRequests, kv.second.value, boost::is_any_of(","));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;				for(size_t i=0; i\<ArrRequests.size(); ++i)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;				{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;					auto push = res.push(ec, "GET","/"+ ArrRequests[i]);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;					push->write_head(200);
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;					push->end(file_generator(ArrRequests[i]));
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;					std::cout\<\<ArrRequests[i]\<\<std::endl;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;				}
&nbsp;&nbsp;&nbsp;&nbsp;			}
&nbsp;&nbsp;		}
&nbsp;&nbsp;		res.write_head(200);
&nbsp;&nbsp;		res.end(R"(end)");
&nbsp;&nbsp;		std::cout\<\<"end"\<\<std::endl;
});
</html>

**Comment by tatsuhiro-t** [comment]
I think chaining from on_close should work, though I have tried that.
Have you tried that already?

**Comment by LindaXiaomi** [comment]
Hello,

I also have similar problem.
I want to push many things,  but I want to push one by one. Could you give me a demo.
