### ISSUE TITLE
How can I capture the signal when I push a source to the client? (Linux C++) 

### ISSUE THREAD

**Issue by JamesXu20150314** [tatsuhiro-t/nghttp2#444]
Hello,

I want to know how can I capture the signal when I push a source to the client ?

If I want to push some sources, can I make the push of these source one by one. 
It means that can I control the begin of the push and end of the push.
It seems that the push->on_closed() function will help. But I am failing with this method.
Do you have any other suggestions? Or how should I configure the nghttp2 on the linux?

Thanks.

James.

**Comment by tatsuhiro-t** [comment]
I think push->on_closed() is the right way to do.
But keep in mind that you should call push(...) all resources before the associated (main) resource is closed.
If you already did this, and still have no luck, can I see your source code?

**Comment by JamesXu20150314** [comment]
Thanks for your reply.

Here is my handle code:

server.handle("/list",[](const request &req, const response &res)
    {	
        boost::system::error_code ec;
        std::vector<std::string> Requests;
		int k;
		
        for(auto &kv : req.header())
        {
            if(kv.first == "requests")
            {
                boost::split(Requests, kv.second.value, boost::is_any_of(","));          
            }
        } 
        
        k = 1;
        auto cb = [&req, &res, Requests, &ec, k](unsigned int a)
		{ 	
            auto push1 = res.push(ec, "GET","/"+ Requests[k]);
		    push1->write_head(200);
		    push1->end(file_generator("output/"+ArrRequests[k]));
		    std::cout<<Requests[k]<<std::endl<<std::endl;
            
                       sleep(5000000);//sleep 5 sec
            
                        res.write_head(200);
			res.end(R"(ok)");
		};
          
	    auto push = res.push(ec, "GET","/"+ Requests[0]);
	    push->write_head(200);
	    push->end(file_generator("output/"+Requests[0]));
	    std::cout<<Requests[0]<<std::endl<<std::endl;
	    push->on_close(cb);
    });

I want to receive the push things about Request[0] first, but I will receive all the request after the res.end() function. Although I have add the sleep() function, it is no use.

Could you give me some suggestions. Thank you very much.

James.

**Comment by tatsuhiro-t** [comment]
Something like this should work:
```cpp
struct Push {
  Push(const response *res) : res(res), closed(false), processed(false) {}
  const response *res;
  bool closed;
  bool processed;
};

struct PushContext {
  std::vector<Push> v;
};

...

int main(int argc, char *argv[]) {
    http2 server;

    server.handle("/", [](const request &req, const response &res) {
      auto push_ctx = std::make_shared<PushContext>();
      for (size_t i = 0; i < 5; ++i) {
        boost::system::error_code ec;

        auto push_res = res.push(ec, "GET", "/push/" + std::to_string(i + 1));
        if (!ec) {
          push_ctx->v.emplace_back(push_res);
          push_res->on_close([push_ctx, i](uint32_t error_code) {
            // Send next push response
            auto &p = push_ctx->v[i];
            p.closed = true;
            if (!p.processed) {
              return;
            }

            for (size_t j = i + 1; j < push_ctx->v.size(); ++j) {
              auto &np = push_ctx->v[j];
              if (np.closed) {
                continue;
              }

              assert(!np.processed);
              np.processed = true;

              auto push_res = np.res;
              push_res->write_head(200);
              push_res->end("this is pushed content\n");

              break;
            }
          });
        }
      }

      // Start first push response here
      if (!push_ctx->v.empty()) {
        auto &p = push_ctx->v[0];
        p.processed = true;
        auto push_res = p.res;
        push_res->write_head(200);
        push_res->end("this is pushed content\n");
      }

      res.write_head(200);
      res.end("you'll receive server push!\n");
    });

  ...
}
```

**Comment by JamesXu20150314** [comment]
Thank you very much.
Your code is very well.

However, I want to receive the push content one by one. It means that I want to receive the push content every 10 seconds.
I add usleep(10000000); sentence as follow:

assert(!np.processed);
              np.processed = true;

              auto push_res = np.res;
              push_res->write_head(200);
              push_res->end("this is pushed content");
			  usleep(10000000);//sleep 10s	
              break;

But I will receive all the push content after the sentence of 
res.write_head(200);
      res.end("you'll receive server push!\n");

Could we make the push content received by client every 10 sec before the sentence  res.write_head(200);
      res.end("you'll receive server push!\n"); ?

Thank you very much.

James.

**Comment by tatsuhiro-t** [comment]
So the left part is delay 10 seconds.
You cannot use usleep() here, because it is a blocking function.  The event loop must not be blocked.
I think you need to use boost::asio::deadline_timer or something similar.
See examples/asio-sv.cc how to use this timer.
Also please be careful the capture in lambda function.  C++ lambda is not like Java or JavaScript, and you have to understand how variable is captured otherwise undefined behaviour is triggered.

**Comment by LindaXiaomi** [comment]
Hello tatsuhiro-t,

I have tried your code. It is very useful for me.
I also want to push things one by one. But the first push content cannot be received until the res.end(...). I also use the push.on_close() function in the server, but I am failing.

Could you modify the code as your provide in this comment. I can't realize my idea.

My idea is that I want to make the client can receive the push content before the code res.end(...) executed in the server. But I will push many things, they should received by the client one by one.

Thanks.

Linda

**Comment by tatsuhiro-t** [comment]
Postpone res.end() until all pushed content are delivered.

**Comment by LindaXiaomi** [comment]
Hello tatsuhiro-t,

Thank you very much, 

I have postponed the res.end(). If I postpone a very long time I cannot receive any push content at the client until the res.end executed. But the first push content should come to client at a reasonable time. When I push many things, I found that all the push content will come in order after the res.end() executed at a time. However, I hope the push content can come to the client although I haven't execute the res.end().

 How can I realize that. I think I need your help.


Linda.

**Comment by tatsuhiro-t** [comment]
There is no limitation about how much the response is delayed and some pushed content is not pushed properly.
Most likely this is the application program bug.
Make sure that
* push is daisy chained properly in on_close callback.
* asynchronous timer is used to schedule pushed stream and associated stream (first stream)
* be aware that captured objects life time.

**Comment by JamesXu20150314** [comment]
Hello tatsuhiro-t,

Thanks for your answer.
There is a problem I can't understand.
When the push content will come to the client. Dose it come to the client after the push.on_close(...)
 executed.

Thanks.

James.

**Comment by LindaXiaomi** [comment]
Hello tatsuhiro-t,

I want to add sleep time between the push content. 
I have tried the deadline_timer(...) function, but when I execute the program, the problem will shutdown.
Here is my code:

server.handle("/", [](const request &req, const response &res) {
      auto push_ctx = std::make_shared<PushContext>();//New 
      for (size_t i = 0; i < 2; ++i) {
        boost::system::error_code ec;

        auto push_res = res.push(ec, "GET", "/push/" + std::to_string(i + 1));
        if (!ec) {
          push_ctx->v.emplace_back(push_res);
        }
      }
      
      // Start first push response here
      if (!push_ctx->v.empty()) {
        auto &p = push_ctx->v[0];
        p.processed = true;
        auto push_res = p.res;
        push_res->write_head(200);
        push_res->end("this is pushed content 0000\n");
      }
	  
	  if (!push_ctx->v.empty()) {
        auto &p1 = push_ctx->v[1];
        p1.processed = true;
        auto push_res1 = p1.res;
        push_res1->write_head(200);
        
        auto timer1 = std::make_shared<boost::asio::deadline_timer>(
        push_res1->io_service(), boost::posix_time::seconds(5));//sleep 5 sec
      	auto closed_t1 = std::make_shared<bool>();
        
        push_res1->on_close([timer1, closed_t1](uint32_t error_code) {
        timer1->cancel();
        *closed_t1 = true;
      	});
        
        timer1->async_wait([&push_res1, closed_t1](const boost::system::error_code &ec) {
        if (ec || *closed_t1) {
          return;
        }

        push_res1->end("this is pushed content 1111\n");
      	});
      }	  
	  
      res.write_head(200);
      auto timer = std::make_shared<boost::asio::deadline_timer>(
          res.io_service(), boost::posix_time::seconds(15));//sleep 15 sec
      auto closed_t = std::make_shared<bool>();

      res.on_close([timer, closed_t](uint32_t error_code) {
        timer->cancel();
        *closed_t = true;
      });

      timer->async_wait([&res, closed_t](const boost::system::error_code &ec) {
        if (ec || *closed_t) {
          return;
        }

        res.end("finally!\n");
      });
      
    });

Could you tell me why the problem will shutdown. How can I modify my problem.

Thanks.

Linda.

**Comment by LindaXiaomi** [comment]
Hello tatsuhiro-t,

I know that the problem come from the captured objects life time. Thank you very much.

Linda

**Comment by tatsuhiro-t** [comment]
> When the push content will come to the client. Dose it come to the client after the push.on_close(...)
executed.

on_close is called when all data is pushed to application buffer.
You cannot make any assumption when the data will reach client.  HTTP/2 does not have such a mechanism.

**Comment by JamesXu20150314** [comment]
Thank you very much

James
