### ISSUE TITLE
How do I test nghttpx proxy server?

### ISSUE THREAD

**Issue by nubela** [tatsuhiro-t/nghttp2#447]
I have an nghttpx instance setuped in a reverse proxy mode, and I will like to do some performance testing with this setup.

Currently, Chrome is able to proxy its contents through the setup, however, I will like a programmatic/CLI manner to access this setup.

Something like a [curl with proxy included](http://stackoverflow.com/questions/9445489/linux-curl-command-with-proxy). Can I do this with `nghttp`? 

`nghttp` seems to be a client for http2-enabled servers, so it's almost like a curl that's http2 enabled. Can I instead enable for it to work as a proxy client setting?

Thank you!

**Comment by nubela** [comment]
Nvm got it:

    $ spdycat -h

**Comment by tatsuhiro-t** [comment]
h2load is also handy
