### ISSUE TITLE
nghttpx does not support multiple entries in link header

### ISSUE THREAD

**Issue by crooy** [tatsuhiro-t/nghttp2#449]
The following does not trigger a server-push, now it took me quite some reading but this is valid according to the RFC as far as I can determine.. 
Play Framework (which I use) chooses to only return a single entry for each header.

```
link:</assets/javascripts/commons.css>; rel=preload; as=stylesheet, </assets/javascripts/homepage.css>; rel=preload; as=stylesheet, </assets/javascripts/commons.js>; rel=preload; as=script, </assets/javascripts/homepage.bundle.js>; rel=preload; as=script, </api/v1/userVariables.js>; rel=preload; as=script
server:nghttpx nghttp2/1.5.1-DEV
```

**Comment by tatsuhiro-t** [comment]
It works for me.
Make sure that --no-server-push is not used.  Also make sure that client is connecting via HTTP/2, and enables server push.

**Comment by tatsuhiro-t** [comment]
There is one condition to enable server push:

> Currently, the following restriction is applied for server push:

>    The associated stream must have method "GET" or "POST". The associated stream's status code must be 200.

**Comment by crooy** [comment]
Hmm, give me a couple of days to retry. Will come back to you

**Comment by crooy** [comment]
so i pulled the latest version of the nghttp Ubuntu container and retested
it it, with spaces and comma's exactly like I mailed and it works now:)

**Comment by tatsuhiro-t** [comment]
Good to hear that.  Let's close this issue.
