### ISSUE TITLE
link error using nghttp2

### ISSUE THREAD

**Issue by valour01** [tatsuhiro-t/nghttp2#454]
I am trying to use nghttp2 to write my own client. But when I start to compile the code. It showed error like this

    http-test.cpp:(.text+0x2364): undefined reference to `nghttp2_session_callbacks_new'
    http-test.cpp:(.text+0x23a0): undefined reference to `nghttp2_option_new'
    http-test.cpp:(.text+0x23b1): undefined reference to `nghttp2_option_set_no_auto_window_update'
    http-test.cpp:(.text+0x23d1): undefined reference to `nghttp2_session_client_new2'
    http-test.cpp:(.text+0x2412): undefined reference to `nghttp2_session_callbacks_del'
    http-test.cpp:(.text+0x2461): undefined reference to `nghttp2_submit_settings'
    http-test.cpp:(.text+0x24a0): undefined reference to `nghttp2_submit_window_update'
    http-test.cpp:(.text+0x24b9): undefined reference to `nghttp2_submit_ping'
    http-test.cpp:(.text+0x24d4): undefined reference to `nghttp2_priority_spec_init'
    http-test.cpp:(.text+0x250c): undefined reference to `nghttp2_priority_spec_init'
    http-test.cpp:(.text+0x2544): undefined reference to `nghttp2_priority_spec_init'
    http-test.cpp:(.text+0x257c): undefined reference to `nghttp2_priority_spec_init'
    http-test.cpp:(.text+0x2604): undefined reference to `nghttp2_priority_spec_init'
    http-test.cpp:(.text+0x2639): undefined reference to `nghttp2_submit_settings'
    http-test.cpp:(.text+0x27e8): undefined reference to `nghttp2_session_want_read'
    http-test.cpp:(.text+0x27fb): undefined reference to `nghttp2_session_want_write'

I know this is an link error, But I don't know what's wrong. The command for compile below:

    g++ -v -I/usr/local/src/nghttp2/lib -I/usr/local/include -I/usr/local/src/openssl-1.0.2e/include -L/usr/local/lib -L/usr/local/src/openssl-1.0.2e -lnghttp2 -lssl -lcrypto -o http-test http-test.cpp

And the lib location:

    /usr/local/lib/libnghttp2.a
    /usr/local/src/nghttp2/lib/.libs/libnghttp2.a

The code is under`/usr/local/src/http-test `. Do you know what's wrong with it or you may need more infomation.

BTW: If I changed the api internally, is it compulsory that I have to recompile the whole lib once again? Many Thanks

**Comment by tatsuhiro-t** [comment]
Put `-lnghttp2 -lssl -lcrypto` after http-test.cpp.

> BTW: If I changed the api internally, is it compulsory that I have to recompile the whole lib once again? 

If you link nghttp2 dynamically (shared lib), then as long as you don't change public APIs, it is not required to recompile your application.

**Comment by valour01** [comment]
>Put -lnghttp2 -lssl -lcrypto after http-test.cpp.

Thanks. It works. 

>If you link nghttp2 dynamically (shared lib), then as long as you don't change public APIs, it is not required to recompile your application.

Since both dynamic and static files under the path `/usr/local/lib/`.  Which one will the compiler choose when I use the command mentioned above. I want to change some code in the nghttp_session.c. So in your opinion I don't need to recompile the nghttp2 once again?

**Comment by tatsuhiro-t** [comment]
> Which one will the compiler choose when I use the command mentioned above. 

Shared library.

> I want to change some code in the nghttp_session.c. So in your opinion I don't need to recompile the nghttp2 once again?

You have to compile libnghttp2 itself.  You don't have to recompile your application.

**Comment by valour01** [comment]
I see. Thanks. Back to the compile part. It seems the compile command is available to generate the running program but still miss something.

    sudo g++ -v -I/usr/local/src/nghttp2/lib -I/usr/local/include -I/usr/local/src/openssl-1.0.2e/include -L/usr/local/lib -L/usr/local/src/openssl-1.0.2e  -o http-test http-test.cpp -lnghttp2 -lssl -lcrypto -ldl

My client is based on the client.c in the examples. The shakehand part is nearly the same as the client.c. when I run my own client with https://www.google.com or any other websites(I am sure they support http2 because I tried it on my laptop with the same client code but compile them using xcode). It just returns a error:

    FATAL: getaddrinfo: Name or service not known

I guess that I missed some configuration or anything related to the http2 handshake support. What do you think so.

**Comment by tatsuhiro-t** [comment]
This is DNS error, and is most likely to OS or its configuration, and not HTTP/2 related.

**Comment by valour01** [comment]
I mean when I use xcode to compile it. It can worked. But moved to ubuntu 14.04 and compile it like that. The error occurs. I don't think it's DNS error. Because I can ping google.com successfully.

**Comment by valour01** [comment]
I am thinking is it because of the openssl version

**Comment by tatsuhiro-t** [comment]
So does stock client.c work for you on ubuntu?

**Comment by valour01** [comment]
I complied the client.c using the same command just now. It works for me. Maybe this error is  related to my code. But it's really strange because when I use xcode it's okay.

**Comment by valour01** [comment]
Oh my god. My bad. I am going to parse a url I input on the console. And I do it like this, which gives an extra mark on the host. Sorry for my carelessness. 

    char *inputURI = (char*)malloc(1024 * sizeof(char));
    scanf("%s", inputURI);
    inputURI[1023] = '\0';

**Comment by tatsuhiro-t** [comment]
OK, so can we close this issue?

**Comment by valour01** [comment]
Sure, thank you very much.

**Comment by defliation** [comment]
Hi，I want to useing libnghttp2_asio.a to implement an http2 client, but i meet following error when compiling, can anyone help me with this? thanks

/data/luojinguo/bias/imserver/server_im/brpc_push_proxy_apn/src/Https2Process.cpp:74: undefined reference to `nghttp2::asio_http2::client::session::session(boost::asio::io_context&, boost::asio::ssl::context&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
