### ISSUE TITLE
non-blocking mode timeout

### ISSUE THREAD

**Issue by valour01** [tatsuhiro-t/nghttp2#457]
I find it may cost much time using nghttp2 as the client to connect to some website. So I want to add a timeout.
It seems the most used way for the timeout on socket connection is to set the fd to be nonblock mode and then use select to do the judgement. But when I set the fd to be nonblock before the connection, the rv is always -1 so that the program will die because the fd will be -1 at last. The code below:

        for (rp = res; rp; rp = rp->ai_next) {
        fd = socket(rp->ai_family, rp->ai_socktype, rp->ai_protocol);
        cout<<"fd"<<fd<<endl;
        if (fd == -1) {
            continue;
        }
        long arg;
        arg = fcntl(fd, F_GETFL, NULL);
        arg |= O_NONBLOCK;
        fcntl(fd, F_SETFL, arg);
        socklen_t lon;
        int valopt;
        timeout.tv_sec=5;
        timeout.tv_usec=0;
        
            while ((rv = connect(fd, rp->ai_addr, rp->ai_addrlen)) == -1 && errno == EINTR);
        cout<<"rv"<<rv<<endl;
                if (rv == 0) {
                    break;
               }
        if (rv < 0) {
            if (errno == EINPROGRESS) {
                cout<<"test"<<endl;
                timeout.tv_sec = 10;
                timeout.tv_usec = 0;
                FD_ZERO(&fdset);
                FD_SET(fd, &fdset);
                if (select(fd+1, NULL, &fdset, NULL, &timeout) > 0) {
                    lon = sizeof(int);
                    getsockopt(fd, SOL_SOCKET, SO_ERROR, (void*)(&valopt), &lon);
                    if (valopt) {
                        fprintf(stderr, "Error in connection() %d - %s\n", valopt, strerror(valopt));
                        exit(0);
                    }
                }
                else {
                    fprintf(stderr, "Timeout or error() %d - %s\n", valopt, strerror(valopt));
                    exit(0);
                }
            } 
            else { 
                fprintf(stderr, "Error connecting %d - %s\n", errno, strerror(errno)); 
                exit(0); 
            } 
        }

        close(fd);
        fd = -1;
    }

If I don't set it to be non-block. I cannot set the timeout because the socket will keep blocking. Do you have any idea on timeout. Many Thanks.

**Comment by tatsuhiro-t** [comment]
With non-blocking connect, `rv` from connect(2) is -1. Yes.
Then you wait for the socket to become writable using select(2).
So you handle select(...) > 0 case. Then it looks like you don't handle the case when connection was made.  If `valopt` is 0, operation was successful, and you should break the loop, or print something "we make it!", or something rather.

**Comment by valour01** [comment]
Thanks. You are right. It works

**Comment by tatsuhiro-t** [comment]
OK, let's close this issue.
