### ISSUE TITLE
add-request-header not working on client-proxy

### ISSUE THREAD

**Issue by ayanamist** [tatsuhiro-t/nghttp2#460]
I'm using a squid as a forward proxy, and use nghttp2 to enable it as a h2 proxy.
```
backend=xxxx.com,443
frontend=127.0.0.1,8080
client-proxy=yes
add-x-forwarded-for=no
no-via=yes
no-ocsp=yes
npn-list=h2
insecure=yes
workers=1
```
When i want to add some header like `add-request-header="x-foo: bar"`, i can't capture the header in the server with `frontend-http2-dump-request-header`

Is it intended to behave like this?

**Comment by tatsuhiro-t** [comment]
It is not clear to me what the configuration looks like.
Is that like this?:
```
[client]  --- [squid] --- [nghttpx client-proxy] --- [h2 server]
```
And did you use `frontend-http2-dump-request-header` in nghttpx client-proxy?
Then it does not work, since it only dumps frontend HTTP/2 connection.
If the above configuration is correct, HTTP/2 connection is between nghtpx client-proxy and h2 server, which is backend connection, and their headers are not dumped.

**Comment by ayanamist** [comment]
Sorry for misunderstand, here is the flow:
`app -> nghttpx (client-proxy) -> nghttpx (server-proxy) -> squid`
I add `frontend-http2-dump-request-header` in server-proxy and `add-request-header` in client-proxy.

**Comment by tatsuhiro-t** [comment]
Thank you for clarification.
add-request-header still works for me with that configuration.
Some header fields are prohibited in HTTP/2, so they are stripped in forwarding path.
x-foo is allowed here, so it should be forwarded.

**Comment by ayanamist** [comment]
I test as follow:

Generate key and cert
```
openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mykey.pem -out mycert.pem
```

Start `nghttpx --conf server.conf` with an invalid upstream proxy
```
frontend=127.0.0.1,8443
backend=127.0.0.1,3128
private-key-file=mykey.pem
certificate-file=mycert.pem
http2-proxy=yes
no-ocsp=yes
add-x-forwarded-for=no
strip-incoming-x-forwarded-for=yes
no-via=yes

frontend-http2-dump-request-header=request.log
```

Start `nghttpx --conf client.conf` pointing to the server
```
backend=127.0.0.1,8443
frontend=127.0.0.1,8180
client-proxy=yes
add-x-forwarded-for=no
no-via=yes
no-ocsp=yes
insecure=yes
add-request-header="x-foo: bar"
```

Use curl which will get a 502 error, but it does not matter.
```
curl -x 127.0.0.1:8180 http://example.com
```

Open `request.log` and found no `x-foo: bar` header.
```
:method: GET
:authority: example.com
:scheme: http
:path: /
user-agent: curl/7.45.0
accept: */*

```

**Comment by ayanamist** [comment]
I found the problem is quotes around `x-foo: bar`, if i removed them
```
add-request-header=x-foo: bar
```
It works.
Sorry to bother.

**Comment by tatsuhiro-t** [comment]
OK.  I added a bit more strict validation for header fields to catch this kind of error.

**Comment by daustin2011** [comment]
I ran into this as well, works without quotes but not with, contrary to documentation. Quotes seem useful here.

**Comment by daustin2011** [comment]
Update - it works with single, but not double quotes (?)

**Comment by tatsuhiro-t** [comment]
The single quote is allowed in both header field name and value, so nghttpx accepts it.
But single quote is also sent, so it is probably not working as you expect.

The example of documentation is intended for command-line usage, and those quotation is consumed by shell.  When it is used in configuration file, quotes should not be used.  I'll update documentation to emphasize this.
