### ISSUE TITLE
compile error (different than #462)

### ISSUE THREAD

**Issue by tessus** [tatsuhiro-t/nghttp2#464]
I get the following compile error:

```
make[2]: Leaving directory `/data/ext/nghttp2-1.6.0/src'
Making all in examples
make[2]: Entering directory `/data/ext/nghttp2-1.6.0/examples'
  CCLD     client
/bin/ld: /usr/local/ssl/lib/libcrypto.a(dso_dlfcn.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
make[2]: *** [client] Error 1
```

It works of course, if I add `--disable-examples` to the configure line, but I'm afraid that if that occurs when compiling the samples, it will also create problems for applications that use the shared library.

**Comment by tatsuhiro-t** [comment]
I guess that you tried to link openssl statically, right?  In that case, you need to give `LIBS=-ldl` to configure script.

**Comment by tessus** [comment]
Not specifically. My configure line looks like this:

`./configure --prefix=/usr/local/nghttp2`

I do have a separate openssl installation (static libs only) in `/usr/local/ssl`, but what I do not understand is that the system doesn't know about it, because the openssl.pc in `/lib64/pkgconfig/` points to the one that comes with the system.
So for some reason your configure script must somehow look for openssl in `/usr/local/ssl/lib` first, instead of checking the typical standard system path. This seems rather odd, because how would you know that people have a second version of openssl installed. Unless you figured that if somebody had a separate installation, they would rather use that.

**Comment by tessus** [comment]
Also, this did not happen with 1.5.0.

**Comment by tatsuhiro-t** [comment]
I was surprised to hear that 1.5.0 works fine here, since not much change has done since then.
I think this issue comes from the inflexibility of compiler command-line handling.
That is if one of the library set -I/usr/local/include or -L/usr/local/lib, then other libraries installed there may also be looked up from there.  The only compiler knows is that the set of directories to lookup and the set of the name of libraries to link.  I may be missing something, but as far as I know, there is no way to set the -I and -L option per library.

**Comment by tessus** [comment]
Ok, that I might understand, but you couldn't possibly have known that I had an ssl version installed in `/usr/local/ssl/lib`.
In my `/usr/local/lib` is no reference to my additional ssl installation.

**Comment by tatsuhiro-t** [comment]
Yeah, it is strange.
nghttp2's configure does not look up /usr/local/ssl/lib specifically.
So my guess is that some third-party libraries set a flag to refer that directory.
It may be possible that PKG_CONFIG_PATH is somehow changed to add that directory.
Or libssl.pc or libcrypto.pc in /usr/local/lib/pkgconfig may include that directory (accidentally).
This depends on the configuration of your system.  At least, we don't do any special handling for OpenSSL installations.

**Comment by tessus** [comment]
Thanks for your help. I will try to figure out what happened.
