### ISSUE TITLE
Question- confirmation about script tag for server push

### ISSUE THREAD

**Issue by dman777** [tatsuhiro-t/nghttp2#470]
After reading [nghttpx server push](https://nghttp2.org/documentation/nghttpx.1.html#server-push) I see 

> nghttpx supports HTTP/2 server push in default mode with Link header field.

I'm assuming I can not server push javascript files. Just to make sure, I would like to ask....
can I use nghttpx to push script tags?

 If not, is this just a limitation with nghttpx? Since spdy could push script tags.

**Comment by dman777** [comment]
I think I see.... Link is not the html link.... after reading http://w3c.github.io/preload/#link-type-preload

**Comment by tatsuhiro-t** [comment]
No, Link is not link element in HTML.  It is link header field in HTTP header.
So, you cannot push script tag, but you can push any resources, including javascript file.
