### ISSUE TITLE
Specify path to OpenSSL

### ISSUE THREAD

**Issue by marcusds** [tatsuhiro-t/nghttp2#473]
I want to build nghttp2 with OpenSSL 1.0.2 for ALPN support, however my system only has OpenSSL 1.0.1 installed.

I have built 1.0.2 in a different path and can use it to build Apache or cURL by setting it with --with-ssl, but I haven't found how to do this with nghttp2. Is this possible?

**Comment by Micdu70** [comment]
Hello,

You can set like below to configure (then compile) nghttp2 with a specific OpenSSL install:

```
LDFLAGS="-L/your/path/openssl/lib" OPENSSL_CFLAGS="-I/your/path/openssl/include" OPENSSL_LIBS="-L/your/path/openssl/lib -lssl -lcrypto"
```

**Comment by tatsuhiro-t** [comment]
That should work.
LDFLAGS is not needed, since required flags are set in OPENSSL_LIBS.

Alternatively, you can use PKG_CONFIG_PATH to point to the directory where openssl.pc file exists (using same naming scheme in the above post, it should be in /your/path/openssl/lib/pkgconfig).

**Comment by marcusds** [comment]
Thanks for the tips.
