### ISSUE TITLE
nghttp as HTTP/1.1 client ?

### ISSUE THREAD

**Issue by s0j0urn** [tatsuhiro-t/nghttp2#486]
Is it possible to use nghttp as HTTP/1.1 client ? 

I am looking for something that can serve as HTTP/1.1 as well as HTTP/2 client. The HTTP/2 client should be able to handle server push which nghttp does perfectly for me.

**Comment by tatsuhiro-t** [comment]
nghttp is HTTP/2 only client.  It can do HTTP Upgrade via HTTP/1.1 request, but that is limited to first upgrade request only.
curl does both HTTP/1 and HTTP/2.  libcurl supports HTTP/2 push now, but as far as I know, curl does not support server push.

**Comment by bagder** [comment]
That's correct: libcurl supports most aspects of HTTP/2 as a client as well as most HTTP/1 features, the curl tool does not (yet) offer server push support. It's nothing substantial that prevents that from being added, just that nobody has done it and it takes some thinking on how it should be done.

**Comment by s0j0urn** [comment]
@bagder Thank You.
I suppose curl's mailing list will be the right place to seek examples and ask questions about coding a libcurl based HTTP/1 client and a HTTP/2 client supporting push feature. 

@tatsuhiro-t Thank You.
We can close this question.

**Comment by bagder** [comment]
@s0j0urn : yes that's the best place!
