### ISSUE TITLE
Problem on windows makefile (makefile.msvc)

### ISSUE THREAD

**Issue by tavrez** [tatsuhiro-t/nghttp2#489]
Windows makefile for making lib tools has a little problem, in line 18, for detecting version it use a shell command:
_VERSION    := $(shell grep AC_INIT ../configure.ac | cut -d'[' -f3 | sed -e 's/-DEV], //g')

The sed part is created for DEV versions, it can't handle non-dev versions correctly, the version will become something like this: "1.7.0],"
This will make .rc file unable to compile. If you change it to:
sed -r -e 's/(-DEV)?], //g'
then it will be compiled successfully on both dev and non-dev versions

**Comment by tatsuhiro-t** [comment]
Thank you for pointing this out.  Can you make a PR for this?

**Comment by tatsuhiro-t** [comment]
#490 fixes this issue.  Thank you!
