### ISSUE TITLE
Vulnerabilities in nghttp2

### ISSUE THREAD

**Issue by noammaz** [tatsuhiro-t/nghttp2#495]
Hi,

We have found two vulnerabilities in nghttp2. Can you contact us in order to get the details? (I didn't found how to report vulnerabilities).

Thanks,
Noam Mazor
noam.mazor@imperva.com

**Comment by tatsuhiro-t** [comment]
Thank you for reporting this.  I just sent e-mail to you.

**Comment by tatsuhiro-t** [comment]
v1.7.1 fixed this.  Thank you!
