### ISSUE TITLE
HTTP/1.1 over TLS

### ISSUE THREAD

**Issue by Ne0nd0g** [tatsuhiro-t/nghttp2#496]
Is it possible to communicate with the backend over HTTP/1.1 with TLS? I messed around with configuration options, but was not able to make this happen.

Also, is there a way to override and allow blacklisted TLS cipher suites?

**Comment by tatsuhiro-t** [comment]
Currently, it is not possible to communicate using HTTP/1 over TLS.  I'm fine to add this though.

We have no option to override blacklisted cipher suites at the moment.  I'd like to ask you how you override this list; disable blacklist or narrow or expand them?

**Comment by Ne0nd0g** [comment]
Thanks for looking into this for me. You could possible allow blacklisted ciphers if they are explicitly set in with the 'ciphers' flag? Alternatively, you could add a flag that is similar to the -k or --insecure flags to explicitly allow insecure connections? Something like --allow-blacklisted-ciphers? Something requires the user to explicitly acknowledge they're enabling an insecure configuration that violates the RFC. Thanks again for your time, I appreciate it.

**Comment by tatsuhiro-t** [comment]
We implemented backend HTTP/1.1 over TLS in nghttpx.  Use --backend-http1-tls switch to enable this.
To disable HTTP/2 cipher black list in nghttpx, use --no-http2-cipher-black-list.

**Comment by tatsuhiro-t** [comment]
Now TLS can be configured per pattern basis.  Use tls keyword in --backend option to enable TLS on backend connection (e.g., `--backend='127.0.0.1,8443;;tls'`)
