### ISSUE TITLE
is h2load support ipv6 option?

### ISSUE THREAD

**Issue by superzelda** [tatsuhiro-t/nghttp2#505]
as we know that the curl -6/--ipv6, Resolve name to IPv6 address. how about h2load?

**Comment by tatsuhiro-t** [comment]
No specific option to enforce IPv6.  As a workaround, you can specify IPv6 numeric address directly in URI: `https://[::1]:8443/foo`
Please bear in mind that IPv6 numeric address must be enclosed by square brackets (`[]`).

**Comment by superzelda** [comment]
ok, that works, thanks
