### ISSUE TITLE
nghttpx and nginx backend http2

### ISSUE THREAD

**Issue by Winzigweich** [tatsuhiro-t/nghttp2#511]
hello,

it is possible to run nghttpx and nginx with http2 in backend?

after the option entry in nghttpx.conf "http2-bridge=yes" and nghttpx restart come...
503 Service Unavailable
nghttpx nghttp2/1.8.0-DEV

(here is my nghttpx.conf)
user=root
workers=4
frontend=*,443
backend=localhost,4444
#backend=unix:/var/run/nginx.sock
tls-proto-list=TLSv1.2,TLSv1.1,TLSv1.0
ciphers=ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
dh-param-file=/etc/ssl/certs/dhparam.pem
private-key-file=/opt/psa/var/certificates/cert-YX6ymS
certificate-file=/opt/psa/var/certificates/cert-YX6ymS
accesslog-file=/var/log/nghttpx/access.log
errorlog-file=/var/log/nghttpx/error.log
add-x-forwarded-for=yes
http2-bridge=yes

my nginx.conf is "listen 4444 ssl http2"

greetings frome germany. :-)

**Comment by tatsuhiro-t** [comment]
> it is possible to run nghttpx and nginx with http2 in backend?

Yes.

Are you using self-signed certificate in nginx?
Then you need to specify its certificate in `--cacert` option, or use `--insecure` option to disable certificate check as a last resort.

**Comment by Winzigweich** [comment]
hi tatsuhiro-t,

thank you. :-)

after the entry in nghttpx.conf with "insecure=yes" works it fine. 

best greetings.

**Comment by Winzigweich** [comment]
P.S.: If it is important, it is no self-signed certificate, it is geotrust certificate.

**Comment by tatsuhiro-t** [comment]
Thank you.  It probably failed to validate host name against one in the certificate.  nghttpx uses the backend hostname specified in -b option for this purpose.  It can be overridden by using --backend-tls-sni-field.

**Comment by Winzigweich** [comment]
the server hostname had actually distinguished from the domain name. have the entry in the nghttpx.conf "insecure=yes" away and "backend-tls-sni-field=fruchthof24.de" is replaced by. is working. :-)
Thank you very much for your help.
