### ISSUE TITLE
Different network results from 2 versions of h2load

### ISSUE THREAD

**Issue by Bankde** [tatsuhiro-t/nghttp2#519]
I ran 2 versions of h2load (download from macports) with following argument
`h2load -n 180000 -c 9000 -r 60 --rate-period=100ms https://192.168.1.3/p10.html`
I collected the server performance using collectl. The server I used in this test is apache 2.4.18

Result of server when testing with h2load 1.6
```
#<----CPU[HYPER]-----><-----------Memory-----------><----------Network---------->
#cpu sys inter  ctxsw Free Buff Cach Inac Slab  Map   KBIn  PktIn  KBOut  PktOut 
  92  24 38559  65727   2G 157M 992M 129M  93M 347M   2937  29839   3150   17240 
  92  24 39023  66357   2G 157M 993M 129M  93M 347M   2922  29854   3129   17105 
  88  23 37816  63462   2G 157M 994M 129M  93M 347M   2823  28697   3028   16576 
  94  28 39960  67485   2G 157M 995M 129M  93M 347M   2987  30493   3215   17562
```
Result of server when testing with h2load 1.7
```
#<----CPU[HYPER]-----><-----------Memory-----------><----------Network---------->
#cpu sys inter  ctxsw Free Buff Cach Inac Slab  Map   KBIn  PktIn  KBOut  PktOut 
  90  29 50520 139242   2G 157M 999M 129M  93M 346M   1299  10297   2621    7549 
  89  28 49972 136711   2G 157M   1G 129M  93M 349M   1268   9880   2576    7300 
  91  26 48418 136183   2G 157M   1G 129M  93M 352M   1299  10312   2617    7584 
  90  30 49333 133506   2G 157M   1G 129M  93M 348M   1284  10140   2621    7599 
  90  25 51154 138090   2G 157M   1G 129M  93M 348M   1285  10209   2602    7327 
```

The network results differ so much by 2-3 times. I have also tried with other tools like nload and iftop, the results are same as using collectl.
I'm not sure if this associate with being sampling based in 1.7 Is there any other major changes between two versions I'm missing ?

Thank in advance.

**Comment by tatsuhiro-t** [comment]
Moving to sampling based does not directly contribute network traffic reduction, but I compared v1.6.0 and latest, and saw the same results as yours.
More specifically, the total traffic of header fields in v1.6.0 is larger than latest one (4596263 vs 2736000 on some benchmark).
It turns out that this is due to the change of Date header field value, which second resolution.
We observed that sampling based code reduced memory foot print of h2load, which may speed up its internals, which means it reduced the occurrences of Date header field change, which leads to reduced header field traffic.  FYI, if Date header field is changed, it usually gets additional 13+ bytes.

**Comment by Bankde** [comment]
Thank you so much for deep analysis. That's really unexpected result. 
Do you think using v1.6.0 will reflect more realistic situation ? In my opinion, Date header field is more likely to change between requests (however, Im not sure if my statement stands true)

**Comment by tatsuhiro-t** [comment]
I think changing data header field is server's job, not something h2load can do something.  Perhaps, it is very interesting observation, that is slower client can cause server more data, while faster client causes less.  This is not something we see in HTTP/1 era.

**Comment by Bankde** [comment]
You're right, it's server job.
Unfortunately, I just realized that I tested this on Gigabit-LAN so date header might not change because of low RTT. RTT between client and server in internet will cause date header to change.
This is still very interesting, I will be careful of this issue while load-testing.

Anyway, if you don't mind, which program did you use to debug while investigating this ? You investigated it so fast into very detail like changing in date header field. That really amazed me.

**Comment by tatsuhiro-t** [comment]
I just noticed that the sum of header field block differs between v1.6.0 and v1.7.0.  The sum of header field block is displayed in h2load standard output.  So I added some debug statements in libnghttp2 code, and observed the length of compressed header block size.  I noticed v1.6.0 sometimes gets larger header block size.   Then I checked debug output of nghttpd, and see that that comes from the Date header field.

**Comment by markseger** [comment]
At least in collectl's case it's reporting the totals across ALL network devices, the theory being you're typically only stressing one interface in times of trouble.  If you really want to be 100%, you could looks at individual interfaces with -sN though if more than one the data becomes interleaved and harder to read.  you can select a specific network to look at with --netfilt eth0 for example of if you're a fan of top style output just add --home to the command line, something very handy for looking at multiple devices be they cpus, disks or networks.
-mark

**Comment by Bankde** [comment]
Thank you so much tatsuhiro, I will take a look at those result when debugging next time.

I always either use --netfilt or turned down other network interfaces, the data there should be correct already. Thank you for your concern.
