### ISSUE TITLE
Support adaptive back-end protocol

### ISSUE THREAD

**Issue by bluecmd** [tatsuhiro-t/nghttp2#520]
Hi,

Love nghttpx - it's almost exactly what I need.
I'm working on an example where the server is exporting the following services, all on :443.
- Static website
- GRPC service (Requires HTTP/2)
- WebSocket (Requires HTTP/1.1)

They are seperated by the following namespaces:
```
/routeguide.RouteGuide/  -> GRPC
/wsapp/                  -> WebSocket
/                        -> Static website
```

I managed to get everything to work just as I want it, but only in separate.
The setup is:
```
client -> nghttpx
               | -> websocket
               | -> nginx HTTP/2
               | -> grpc server
```
Running in `--http2-bridge` I can successfully call GRPC services and access nginx contents, but websockets are out of the picture. I tried putting the websocket server after nginx to let it handle the downgrade, but I think the whole Upgrade business is what's making it fail ultimately.

Running in default mode and disabling HTTP/2 in nginx makes websocket work just fine, static files as well but obviously GRPC doesn't work.

Interestingly enough the client (Chrome in this case) knows that HTTP/2 and WebSockets are incompatible and doesn't send HTTP/2 requests for those. They are accepted and later upgraded to HTTP/2 in `--http2-bridge` mode (as per documentation). And here is what I would request a feature.

Would it be possible to add a feature to just use whatever protocol the client is using to go through? Something like `--http-agnostic-bridge`.

Thanks,

**Comment by tatsuhiro-t** [comment]
This is the feature I'd like to implement for some time.
I think we can safely assume that all sane clients issues HTTP/1 request for WebSocket.

We have several options to achieve this adaptive thing.
One of them is to forward HTTP/2 frontend requests, and HTTP/1 requests excluding Upgrade stuff to HTTP/2 backend.  This would work if backend server accepts both HTTP/1 and HTTP/2 at the same port, but nginx does not if we don't use TLS.  Also we might want to select backend protocol based on request path.  If so we have to extend --backend option syntax to allow new keyword.

**Comment by bluecmd** [comment]
Wouldn't TLS be an acceptable requirement in this case? For my use case it's fine, I can just use any dummy certificate for the connection between nghttpx <-> nginx.

**Comment by tatsuhiro-t** [comment]
Yes, we can support TLS in backend.  nginx requires it if we try to make nginx handle both HTTP/1 and HTTP/2 at the same address and port pair.  Probably, we can add cleartext mode for some performance savvy usage.

**Comment by tatsuhiro-t** [comment]
We have ";" as separator in --backend option, so we might add protocol option to it.  Just like so:

```
backend=127.0.0.1,6000;/grpc;proto=h2
backend=127.0.0.1,8080;/;proto=http/1.1
```

This should read like: forward /grpc request to 127.0.0.1:6000 in HTTP/2 protocol.  All other requests are forwarded to 127.0.0.1:8080 in HTTP/1.1.

This is just an idea.

**Comment by bluecmd** [comment]
That looks good, but it would force the operator to bind the protocol. It would be cool if you could do "proto=http/1.1,h2" to say that both are acceptable if they are already in that format (to avoid the WS upgrade, but still allow H2 features)

**Comment by tatsuhiro-t** [comment]
Autodetection is nice to have.  Usually, server admin knows exact configuration about backend server.  So it is not impossible to bind the single protocol per host/request path.
We'd like to go with single protocol for the first release.  We may extend this to multiple protocol in the future.

**Comment by bluecmd** [comment]
:thumbsup:  Works for me! I'll just redirect the websocket path in nghttpx instead of further down the stack.

**Comment by tatsuhiro-t** [comment]
Current master branch implements what we agreed.
See https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx-b and https://nghttp2.org/documentation/nghttpx-howto.html#multiple-backend-addresses

To make future extensions robust, we removed --http2-brdige, --client and --client-proxy.
With the combinations of the options, these modes can be emulated.
