### ISSUE TITLE
Question related to Upgrade scenario.

### ISSUE THREAD

**Issue by vimalatadepalli** [tatsuhiro-t/nghttp2#521]
When a connection upgrades from Http/1 to Http/2 using Switch protocols method defined in rfc, should the client assume that first request sent through Http/1 as stream_id 1?
The reason i ask is because for the pcap attached, there is Http/1 request with Upgrade protocol to Http/2. Server responds back with "Switching Protocols". Client then sends magic , settings etc (but no headers). Server then responds to the initial get request(sent through http/1). "nghttp2_session" client ignores as there is no stream id 1 since it hasnt sent through this session.
How should i handle this case? 
[h2-upgrade-sample.hqx.pcap.zip](https://github.com/tatsuhiro-t/nghttp2/files/142018/h2-upgrade-sample.hqx.pcap.zip)

**Comment by tatsuhiro-t** [comment]
> When a connection upgrades from Http/1 to Http/2 using Switch protocols method defined in rfc, should the client assume that first request sent through Http/1 as stream_id 1?

Yes.  It is mandated by RFC 7540.  See https://tools.ietf.org/html/rfc7540#section-3.2

Probably, you forgot to call [nghttp2_session_upgrade2](https://nghttp2.org/documentation/nghttp2_session_upgrade2.html#c.nghttp2_session_upgrade2)?

**Comment by vimalatadepalli** [comment]
Thanks for pointing out the call. I forgot to call the upgrade method.

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
