### ISSUE TITLE
Add option to disable automatic PING reply

### ISSUE THREAD

**Issue by lomnicky** [tatsuhiro-t/nghttp2#522]
When using Nghttp2 library as a proxy, a PING frame, when received, is forwarded to the other peer, but the reply is sent by the proxy automatically. However, more logical scenario would be to wait until the other peer replies and than forward the reply. 

I suggest adding an option to disable automatic PING replies. In addition to this, please, add support to submit a PING reply (now the flags are ignored).

Current solution I am using is commenting-out code in nghttp2_session_on_ping_received and using nghttp2_session_add_ping instead of nghttp2_submit_ping.

Thanks.

**Comment by tatsuhiro-t** [comment]
I'm ok to add an option to disable automatic ping reply.  I thought that PING is rather hop-by-hop, but in general it is fine to have this kind of option.

**Comment by tatsuhiro-t** [comment]
Fix committed via e4537596372b2a7a9582a18676b0df5cc48953ae
