### ISSUE TITLE
Suggestion: wildcard host in --backend match-pattern

### ISSUE THREAD

**Issue by devlearner** [tatsuhiro-t/nghttp2#523]
[nghttpx(1)](https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx--backend): 
> `-b, --backend=(<HOST>,<PORT>|unix:<PATH>)[;<PATTERN>[:...]]`
> Set backend host and port. The multiple backend addresses are accepted by repeating this option. ...
> 
> Optionally, if `<PATTERN>`s are given, the backend address is only used if request matches the pattern. ... `<PATTERN>` consists of path, host + path or just host. ...
> If host is given, it performs <em>exact match</em> against the request host. 

Perhaps it could be useful if we could also recognize wildcard (asterisk) hosts, especially in combination with the [`--subcert`](https://nghttp2.org/documentation/nghttpx.1.html#cmdoption-nghttpx--subcert) option:
> `--subcert=<KEYPATH>:<CERTPATH>`
> Specify additional certificate and private key file. nghttpx will choose certificates based on the hostname indicated by client using TLS SNI extension. This option can be used multiple times. ...

For example:
```
nghttpx ...
  --backend=<backendA>;*.abc.com 
  --backend=<backendB>;*.def.com 
  --backend=<backendC>;/ 
  --subcert=/path/to/wildcard.abc.com.key:/path/to/wildcard.abc.com.cert 
  --subcert=/path/to/wildcard.def.com.key:/path/to/wildcard.def.com.cert 
  /path/to/catchall.key /path/to/catchall.cert
```
`*.abc.com` would be routed to `<backendA>`;
`*.def.com` would be routed to `<backendB>`;
with a catch-all backend `<backendC>`.

> The pattern matching is closely designed to ServeMux in net/http package of Go programming language. 
> `<PATTERN>` consists of path, host + path or just host. ...
> If host is given, it performs exact match against the request host

Perhaps we could make a break-of-the-rule here to recognize wildcard hosts that start with an (*) as well, since normal host names won't start with an asterisk.

So that: 
Exact hosts match takes precedence over wildcard hosts; and:
> Patterns with host take precedence over patterns with just path. Then, longer patterns take precedence over shorter ones, breaking a tie by the order of the appearance in the configuration.

Just as a suggestion :-)

Thanks!

**Comment by tatsuhiro-t** [comment]
Thank you for suggestion.  This is really interesting.

**Comment by yegors** [comment]
Any ideas on when this could potentially be implemented? It would be awesome!

**Comment by tatsuhiro-t** [comment]
Fix committed via 34d209b

**Comment by devlearner** [comment]
Thank you very much for the enhancement!  That's a very nice feature :)

**Comment by yegors** [comment]
![Bow Down](https://38.media.tumblr.com/70f04e4ea7e6df104c6e2e346fc3e589/tumblr_inline_o3c8w3TwGq1s4kk59_500.gif)
