### ISSUE TITLE
Add callback function to tell application which header field caused error

### ISSUE THREAD

**Issue by tatsuhiro-t** [tatsuhiro-t/nghttp2#527]
As [documented](https://nghttp2.org/documentation/programmers-guide.html#http-messaging), nghttp2 library checks incoming HTTP header field, and if it violates HTTP messaging rules, it resets stream with RST_STREAM.
The problem is there is no mechanism to tell the application which header field caused this.
To know its header, we have to recompile nghttp2 with --enable-debug configure option, which is very tedious.
It would be extremely useful if we have a callback to tell which header field is bad.

**Comment by tatsuhiro-t** [comment]
The proposed callback signature is something like this:

```c
typedef int (*nghttp2_on_invalid_header_callback)
            (nghttp2_session *session, const nghttp2_frame *frame,
             const uint8_t *name, size_t namelen,
             const uint8_t *value, size_t valuelen,
             uint8_t flags, int lib_error_code, void *user_data);
```

*lib_error_code* will tell what kind of error happened.  This is usually `NGHTTP2_ERR_HTTP_HEADER`.
The other parameters are the same with `nghttp2_on_header_callback`.

**Comment by LPardue** [comment]
Does this change relate to checking pseudo header field, HTTP header fields or both?

What happens if there are multiple invalid headers?

**Comment by tatsuhiro-t** [comment]
All header fields including pseudo header fields and all regular headers.

Currently, we give up the stream when first see the really invalid headers, so the only first one will be reported.

**Comment by LPardue** [comment]
Ok I understand now.

While on this area is there scope to configure the validation logic in any way? I don't have a use case for this personally but as an example a user may want to have nghttp2 validate the psuedo headers but be a bit more relaxed about the other fields, or to permit through a specific bad header without having to validate the entire set. I'm thinking aloud here so please ignore if this doesn't make sense.

**Comment by tatsuhiro-t** [comment]
First let me explain how validation goes in nghttp2.  Roughly, there are 2 mode of failure in nghttp2 header field validation.

First one is ignoring regular header field which contains illegal characters (see [RFC 7230, 3.2](https://tools.ietf.org/html/rfc7230#section-3.2)).  We just ignore them, and not send to application.  And continue to process rest of the header fields, and stream is still alive.

Second one is terminate stream with RST_STREAM.
We don't have same forgiveness for pseudo header fields about illegal characters, since they are new and specific HTTP/2, therefore there are no legacy things to think about.  So if we found illegal characters in pseudo headers, they are subject to RST_STREAM.
We also check obvious errors: name is not lowercased, pseudo header field comes after regular header fields, and disallowed header fields (e.g., connection, transfer-encoding).  We also check the content-length, and status code and if they cannot be parsed as integer, we also terminate stream.

The proposed callback is only called for the second case.  Primary purpose of this callback is inform the application of the header field which caused stream termination.  In other words, it is for debugging purpose.

As you suggested, I think it is a good idea to customize this validation into more specific area.
For example, we just let header field containing illegal characters be passed to application instead of ignoring it.  This could be achieved with this callback by changing lib_error_code and some new return values to instruct the library to handle this.  But it could be complex a bit.  Rather, it would be simpler to add session wide option (nghttp2_option) to toggle this behaviour, and leave this callback as debug usecase only.

**Comment by bagder** [comment]
For me personally, I think I would prefer a more generic "debug message callback" that would simply give me more additional information about whatever is happening. Like in the referred case, we would've been happy with an english string stating the name of the illegal header (for human consumption). I doubt many people will come up with automatic ways to handle illegal headers. Also, by making it a more generic "debug message" callback, you could use it to provide more info to several other error situations that currently return the same error code in numerous places and thus sometimes make it rather tricky to identify the exact error reason.

**Comment by tatsuhiro-t** [comment]
Thank you for the comment.
Actually, I like your idea about generic debug message callback.  If we define the new callback as debug information provider, then passing human readable text is the way to go.

**Comment by tatsuhiro-t** [comment]
Now something like this:

```c
int nghttp2_error_callback(nghttp2_session *session, const char *error_msg, size_t len,
                           int lib_error_code);
```

The len is the length of error_msg, although error_msg is guaranteed to be NULL terminated.
I'm not sure we need lib_error_code here.  If all application wants is textual message, then it is not necessary.

**Comment by LPardue** [comment]
KISS is good for me.

**Comment by tatsuhiro-t** [comment]
Indeed.  Right, let's go without error code.

**Comment by tatsuhiro-t** [comment]
I ended up `int nghttp2_error_callback(nghttp2_session *session, const char *error_msg, size_t len, void *user_data)`, and it was added by the commit 2a606bae4c1b0cd358025e37fc5adabfd12ddda1.
Sample output:

```
Invalid HTTP header field was received: frame type: 1, stream: 13, name: [upgrade], value: [h2]
```

**Comment by bagder** [comment]
Lovely!
