### ISSUE TITLE
How can I use nghttp2 to send a http/2 post request?

### ISSUE THREAD

**Issue by linyanwen** [tatsuhiro-t/nghttp2#528]
As post request include two parts:  request header and request body, and I want to use nghttp2 to encode this two parts, and then send a post request.
Can anyone show me an example? Thanks a lot!

**Comment by linyanwen** [comment]
A sample http/2 request as shown below:
HEADERS
  - END_STREAM
  + END_HEADERS
  :method = POST
  :scheme = https
  :path = /3/device/00fc13adff785122b4ad28809a3420982341241421348097878e577c991de8f0
  host = api.development.push.apple.com
  apns-id = eabeae54-14a8-11e5-b60b-1697f925ec7b
  apns-expiration = 0
  apns-priority = 10
    content-length = 33
DATA
  + END_STREAM
    { "aps" : { "alert" : "Hello" } }

How can I use nghttp2 to encode a request  with the right format as shown above?

**Comment by tatsuhiro-t** [comment]
To send request to server, consider to use [nghttp2_submit_request()](https://nghttp2.org/documentation/nghttp2_submit_request.html).

The request header fields are passed as the array of [nghttp2_nv](https://nghttp2.org/documentation/types.html#c.nghttp2_nv) object.  How to assign name/value is probably obvious.

END_STREAMS and END_HEADERS are handled by nghttp2 library.

To send request body, pass a pointer to [nghttp2_data_provider](https://nghttp2.org/documentation/types.html#c.nghttp2_data_provider).  You have to pass at least read_callback (source.ptr can be NULL).  You have to implement read_callback to write request body to the buffer nghttp2 library provides.  [Here](https://github.com/tatsuhiro-t/nghttp2/blob/fe6ccd16da67f0ec0b00a6aa16ff419f78208f82/src/nghttp.cc#L2185) is the example for read_callback.

**Comment by linyanwen** [comment]
Now I know how to send a post request with its request body.Thanks a lot.

**Comment by howardguo** [comment]
@linyanwen How to do POST with nghttp2? thanks very much:).

**Comment by msgharpu** [comment]
In send_callback can we free the data pointer after the data is sent over sockets?
