### ISSUE TITLE
submit padding api

### ISSUE THREAD

**Issue by valour01** [tatsuhiro-t/nghttp2#529]
I was wondering how to add padding in the headers, push promise and data frames if I use nghttp2 as my client library. I didn't find the related api. Many Thanks

**Comment by tatsuhiro-t** [comment]
Use nghttp2_select_padding_callback.  See https://nghttp2.org/documentation/nghttp2_session_callbacks_set_select_padding_callback.html

Note that you cannot add padding to PUSH_PROMISE as per RFC 7540.

**Comment by valour01** [comment]
So when I use the `nghttp2_select_padding_callback`. Will the library add padding into headers frame and data frame automatically? What about the case when I have continuation frame. And what is the length of the padding. Many Thanks

**Comment by tatsuhiro-t** [comment]
Probably you should read RFC 7540.  You cannot add padding to CONTINUATION.
Also please read https://nghttp2.org/documentation/types.html#c.nghttp2_select_padding_callback
which will answer your question.

**Comment by valour01** [comment]
If I understand right, the returned value of `select_padding_callback` should be between the 
`frame->hd.length` and the `max_payloadlen`. And the returned value is the original headers frame size plus padding size. Am I right?

And RFC7540 allows us to add padding to `push promise frame`. Please refer Page 73. Chapter 10.7(Use of Padding)
>Intermediaries SHOULD retain padding for DATA frames but MAY drop
   padding for HEADERS and PUSH_PROMISE frames. 

According to `RFC2119`
> MAY This word, or the adjective "OPTIONAL", mean that an item is
 truly optional. 

And according to Page 40 of RFC7540, Chapter 6.6. Push promise has a field for padding

**Comment by tatsuhiro-t** [comment]
> If I understand right, the returned value of select_padding_callback should be between the
frame->hd.length and the max_payloadlen. And the returned value is the original headers frame size plus padding size. Am I right?

Yes.

> And RFC7540 allows us to add padding to push promise frame. Please refer Page 73. Chapter 10.7(Use of Padding)

You are right.  I was confused between CONTINUATION and PUSH_PROMISE.  Sorry for that.

**Comment by valour01** [comment]
I see. Thank you.

**Comment by tatsuhiro-t** [comment]
OK, let's close the issue.
