### ISSUE TITLE
Suggestion: Custom 50x Errors

### ISSUE THREAD

**Issue by yegors** [tatsuhiro-t/nghttp2#533]
It would be great if you could skin the 50x error pages instead of showing a blank white page like this:

```
503 Service Unavailable

nghttpx nghttp2/1.5.0 at port 443
```

Right now we're planning on editing create_error_html() in the source, which is not the most elegant solution.

**Comment by tatsuhiro-t** [comment]
If I understand this issue correctly, nghttpx works correctly, but it would be better to improve error page design.  Is that correct?

**Comment by yegors** [comment]
Yes, this is not a bug, but would be a great improvement if you could override the default look of the errors by supplying a custom html page. Appropriate HTTP status code could still be sent, but the look of the page itself should be customizable.

**Comment by tatsuhiro-t** [comment]
Thank you for clarification.  I think adding option `--error-page=<STATUS>=<FILE>`, where `<STATUS>` is the 5xx (I'm not sure nghttpx servers 4xx code from itself), and `<FILE>` is the path to HTML file to serve would do.

**Comment by yegors** [comment]
Yes, that would be excellent. Thanks for all your work!

**Comment by tatsuhiro-t** [comment]
This feature has been implemented.

```
  --error-page=(<CODE>|*)=<PATH>
              Set file path  to custom error page  served when nghttpx
              originally  generates  HTTP  error status  code  <CODE>.
              <CODE> must be greater than or equal to 400, and at most
              599.  If "*"  is used instead of <CODE>,  it matches all
              HTTP  status  code.  If  error  status  code comes  from
              backend server, the custom error pages are not used.
```

**Comment by yegors** [comment]
Awesome! Thank you very much.
