### ISSUE TITLE
HTTP/2 Scheme

### ISSUE THREAD

**Issue by Ne0nd0g** [tatsuhiro-t/nghttp2#536]
I'm troubleshooting a problem when using nghttpx as proxy for connections to an Apache 2.4.18 install over HTTP/2. Server-A (192.168.56.120) receives a HTTP/2 connection on 443 and then proxies it nghttpx on 127.0.0.1:3000 and nghttpx proxies that connection to Server-B (192.168.56.111) on port 443 over HTTP/2. This works with Apache 2.4.17, but not with Apache 2.4.18. You can see the bug report here: https://bz.apache.org/bugzilla/show_bug.cgi?id=59176 . I'm running nghttpx nghttp2/1.9.0-DEV with:

`nghttpx --frontend=127.0.0.1,3000 --frontend-no-tls --backend='192.168.56.111,443;/;proto=h2' --backend-tls -k -L INFO --host-rewrite`

When processing this connection:
```
GET / HTTP/1.1
host: 127.0.0.1:3000
pragma: no-cache
cache-control: no-cache
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
accept-encoding: gzip, deflate, sdch
accept-language: en-US,en;q=0.8
x-forwarded-for: 192.168.56.115
x-forwarded-host: 192.168.56.120
x-forwarded-server: www.example.com
connection: Keep-Alive
```

I get this HTTP/2 request:
```
:method: GET
:scheme: http
:path: /
host: 192.168.56.111
pragma: no-cache
cache-control: no-cache
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
accept-encoding: gzip, deflate, sdch
accept-language: en-US,en;q=0.8
x-forwarded-host: 192.168.56.120
x-forwarded-server: www.example.com
x-forwarded-for: 192.168.56.115
x-forwarded-proto: http
via: 1.1 nghttpx
```

Shouldn't the scheme be https?

**Comment by tatsuhiro-t** [comment]
If older apache works, then it sounds like apache's problem, but I'm not sure about it.

> Shouldn't the scheme be https?

No, since the connection nghttpx received was HTTP/1.1 over cleartext TCP, and the request had no request header field to indicate it was from TLS connection.

**Comment by tatsuhiro-t** [comment]
Note that HTTP/2 separates connection and scheme which each request has.  It is completely valid to send request with HTTP (not HTTPS) scheme on TLS connection (e.g., HTTP/2 secure proxy).

**Comment by Ne0nd0g** [comment]
Awesome, thank you for answering my question and sharing that information.
