### ISSUE TITLE
Why do nghttp2 send a goaway frame?

### ISSUE THREAD

**Issue by fatjimmy** [tatsuhiro-t/nghttp2#539]
I was writing a program of sending notifications to apns using nghttp2. And I'm using a multi-thread model to handle my requests. The problem is that I can send only one successful notification to apple in each thread. Part of the log is below:
write:50 52 49 20 2a 20 48 54  54 50 2f 32 2e 30 0d 0a 0d 0a 53 4d 0d 0a 0d 0a （the magic number starting the session）
read :00 00 18 04 00 00 00 00  00 00 01 00 00 10 00 00 03 00 00 01 f4 00 05 00  00 40 00 00 06 00 00 1f 40 (a setting frame returned by apns)
write:00 00 06 04 00 00 00 00  00 00 03 00 00 00 64 (a setting frame)
...
write: ....(data frame)
read: ...(header frame)
These frames of the first notification seem normal.
After the first notification was successfully handled, I got an error "closed with HTTP/2 error code 7" when I tried to send another notification in the same thread.
I notice that the first frame of the second notification sent by nghttp2 is a goaway frame.
write:00 00 08 07 00 00 00 00  00 00 00 00 00 00 00 00
So I wonder why nghttp2 will send a goaway frame to apns while I did't use relative API to close my stream.

**Comment by tatsuhiro-t** [comment]
Without more complete frame loggings, it is hard to say what happened.
The goaway frame has the error code 0, which is NO_ERROR.
As far as I know, nghttp2 does not send this without application calls nghttp2_submit_goaway or nghttp2_session_terminate_session with NGHTTP2_NO_ERROR.
nghttp2 may send GOAWAY if it detected abnormal behaviour from peer, but it generally has nonzero error code in it.

**Comment by fatjimmy** [comment]
I think I may know where the problem is now. I write a on_stream_close_callback similar to the code below which is in fact part of your example program tcp-client.c. I think I shouldn't call nghttp2_session_terminate_session. Because in your example you just use only one stream, and the session should be terminated when the stream closes. So if I have multiple streams in use, I shouldn't call the nghttp2_session_terminate_session function in the on_stream_close_callback. But where should I put this function in? Is there a callback for detecting the connection getting an error or receiving a goaway frame ?
```
static int on_stream_close_callback(nghttp2_session *session, int32_t stream_id,
                                    uint32_t error_code, void *user_data) {
  struct request *req;
  int rv;

  (void)user_data;

  req = nghttp2_session_get_stream_user_data(session, stream_id);
  if (!req) {
    return 0;
  }

  if (error_code != NGHTTP2_NO_ERROR) {
    fprintf(stderr, "stream %d closed with HTTP/2 error code %d\n", stream_id,
            error_code);
  }

  rv = nghttp2_session_terminate_session(session, NGHTTP2_NO_ERROR);
  if (rv != 0) {
    fprintf(stderr, "error: (nghttp2_session_terminate_session) %s\n",
            nghttp2_strerror(rv));
    return NGHTTP2_ERR_CALLBACK_FAILURE;
  }

  return 0;
}
```

**Comment by tatsuhiro-t** [comment]
It depends on the nature of the application.  Some application wants to drop connection when it gets response completely.  Some application just waits until server terminates connection.
You can do this in on_stream_close_callback or create timer around event loop.

Typically, application uses nghttp2_session_want_read and nghttp2_session_want_write after calling nghttp2_session_{mem_}send and nghttp2_session_{mem_}write to determine whether it should break event loop.
nghttp2 automatically sets these function call's return value to 0 if it detects error or server/client performed graceful shutdown.
