### ISSUE TITLE
Delayed connection teardown (h2 backend)

### ISSUE THREAD

**Issue by devlearner** [tatsuhiro-t/nghttp2#549]
hi tatsuhiro,

i happen to notice this issue when i test run the latest master in nghttpx
grateful if u could take a look at it :-)

i'll keep it brief and briefly describe my test case scenario:
```
nghttpx -f 127.0.0.1,1111 -b 127.0.0.1,3333;;proto=h2 --frontend-no-tls -L INFO
```
i use a socat listening at the backend:
```
socat TCP4-LiSTEN:3333,bind=127.0.0.1 -
```
then i use a client (socat or curl or nghttp) to issue a request to nghttpx:
```
nghttp http://127.0.0.1:1111/dummy
```
as can be observed, the backend is a dummy that doesn't respond.
i then press ctrl-C to terminate the client connection.
as expected, nghttpx submits rst_stream to the backend, as seen in the log:
```
[INFO] shrpx_client_handler.cc:468 [CLIENT_HANDLER:0x3759f030] Deleting
[INFO] shrpx_client_handler.cc:491 [CLIENT_HANDLER:0x3759f030] Deleted
[INFO] shrpx_downstream.cc:160 [DOWNSTREAM:0x375a6688] Deleting
[INFO] shrpx_http2_downstream_connection.cc:56 [DCONN:0x375a6d10] Deleting
[INFO] shrpx_http2_downstream_connection.cc:153 [DCONN:0x375a6d10] Submit RST_STREAM for DOWNSTREAM:0x375a6688, stream_id=1,error_code=2
[INFO] shrpx_http2_session.cc:683 [DHTTP2:0x375a7298] RST_STREAM stream_id=1 with error_code=2
[INFO] shrpx_http2_session.cc:639 [DHTTP2:0x375a7298] Remove downstream
[INFO] shrpx_http2_downstream_connection.cc:89 [DCONN:0x375a6d10] Deleted
[INFO] shrpx_downstream.cc:190 [DOWNSTREAM:0x375a6688] Deleted
[INFO] shrpx_http2_session.cc:734 [DHTTP2:0x375a7298] Stream stream_id=1 is being closed with error code 2
```
pausing here, however, somehow nghttpx doesn't seem to immediately remove the downstream connection (as seen, the backend socat stays open in the console, meaning the connection is not teared down yet, immediately after the rst_stream)
a few seconds later ...
```
[INFO] shrpx_http2_session.cc:96 [DHTTP2:0x375a7298] SETTINGS timeout
[INFO] shrpx_http2_session.cc:1581 [DHTTP2:0x375a7298] No more read/write for this session
[INFO] shrpx_http2_session.cc:217 [DHTTP2:0x375a7298] Disconnecting
[INFO] shrpx_http2_session.cc:217 [DHTTP2:0x375a7298] Disconnecting
[INFO] shrpx_http2_session.cc:209 [DHTTP2:0x375a7298] Removed from http2_freelist
```
it seems that, for some reason, nghttpx doesn't until the next natural timeout "disconnect" the downstream and remove the backend connection "from http2_freelist".
trying again with `--backend-tls`, there also seems to be a delay before disconnecting and removing from http2_freelist the backend connection

(just to note that with h1 backend (`-b ... ;proto=http/1.1`) the backend connection is immediately closed as expected, so it seems to be h2-specific)

just as a hunch, i didn't notice this before, so i suspect (simply speculate) it might be an unexpected side-effect with the major rewrite of the backend-servers structuring (particularly with the newly introduced http2_freelist maybe?)

(but btw, the new `--backend` is easier to use with new `proto=` functionality, which is really useful!)

thank you in advance :)

many thanks!

**Comment by tatsuhiro-t** [comment]
This is normal since nghttpx just terminated one backend logical stream, and not HTTP/2 session entirely.  Notice that we multiplex multiple frontend streams to one backend HTTP/2 session, and we don't want to terminate backend HTTP/2 connection when just closing frontend connection.
I think this behaviour has persisted from the earlier nghttpx release.

**Comment by devlearner** [comment]
ah.... my bad, i think i suddenly got confused w/ h1 concepts ;-D
thanks for your explanation!

**Comment by devlearner** [comment]
> I think this behaviour has persisted from the earlier nghttpx release.

yeah, indeed ! i pulled an old release from my archive back in 2015 and the same behaviour exists :)
very sorry for the confusion  (probably not thinking straight today) :-D

btw as a side note, i notice sth interesting that sometimes arguments need not exact,
for example, `--backend-tls[-sni-field]=`
i find that so long as i type one or more chars in the [square brackets], like `--backend-tls-sni=` or even `--backend-tls-=` (to set it apart from `--backend-tls`) it automatically got recognized as `--backend-tls-sni-field=` (which is quite interesting to me:) )
of course if the sequence doesn't match (like `--backend-tls-g=`) it'll throw an error
(i only pass it as cmd line args so i don't know the behaviour of parsing a config file)

anyway, thanks for the improvements esp the new features in recent releases, they are really useful :)

**Comment by tatsuhiro-t** [comment]
You unlocked the mythical behaviour of GNU [getopt_long()](http://man7.org/linux/man-pages/man3/getopt.3.html)!

Well, that was a joke, this behaviour is documented in the above link.  More specifically:


>Long option names may be abbreviated
  if the abbreviation is unique or is an exact match for some defined
  option.

**Comment by devlearner** [comment]
glad to know :D
